### ISSUE TITLE
/tmp directory by default in setup function on Windows environments

### ISSUE THREAD

**Issue by mmazzariol-sn** [gabordemooij/redbean#130]
When creating a new Redbean setup without parameters in a Windows environment I got:

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [14] unable to open database file' in C:\xyz\rb.php:53
Stack trace:
#0 C:\xyz\rb.php(53): PDO->__construct('sqlite:/tmp/red...', NULL, NULL, Array)

Since /tmp is not present in Windows environment is it possible adding a check in Redbean and eventually create the sqlite db in a known directory such as C:\ ?

**Comment by luciferz2012** [comment]
I got a similar problem. If no parameter is provided, the database is set to something like this: 'sqlite:/C:\Users\LUCIFE~1\AppData\Local\Temp/red.db'

Then the tutorial 'dram.php' exited when it ran to the connect function.

If I change the path to 'sqlite:test.db', it can run properly.

I am not sure if it is the problem of permission or something else.

**Comment by gabordemooij** [comment]
I'm not an expert on Windows, since I have been using Linux/UNIX since 2005, I only used Windows XP at work as a desktop for a while (til 2009). I thought the Temp directory on Windows was always writable, just like on Linux/UNIX, however this seems not the case?
