### ISSUE TITLE
R::close, R::setup results in previous db connection staying default

### ISSUE THREAD

**Issue by katanacrimson** [gabordemooij/redbean#155]
After opening an sqlite connection to a local database and closing it through `R::close()`, I'm trying to initiate a connection to a mysql database with another call to `R::setup()` (and am confirming that it's being made, as the connection should error out) only to find that redbean is opening up the previously opened-and-closed sqlite database.

As `R::setup()` is being called with no active connections available, shouldn't the sqlite connection should be replaced by the in-progress mysql connection?

**Comment by saurabhaec** [comment]
R::close(); 
R::addDatabase( DB_WRITE_NAME, 'mysql:host='.DB_WRITE_HOST';dbname='.DB_WRITE_NAME  , DB_WRITE_USER , DB_WRITE_PASSWORD );

R::selectDatabase(DB_WRITE_NAME);

R:testConnection();
