### ISSUE TITLE
Shared object not loading but the data is there

### ISSUE THREAD

**Issue by krisives** [gabordemooij/redbean#251]
I have the following tables:
- **user**: Login accounts
- **program**: Sales programs that users enroll into and are created/owned by a single user

Each program has a "manager", which is a 'user' bean:

```
$manager = R::load('user', $managerID);
$program->manager = $manager;
```

Inspecting the database yields what I expect, which is a `manager_id` column with a foreign key constraint to the `user.id` - However I get unexpected results like this:

```
$program = R::load('program', $programID);
var_dump($program->manager->name);
var_dump($program->manager_id);
```

The `manager_id` value is there, and the record for that user ID exists, but `$program->manager` will be an empty bean object with ID zero.

I am open to provide more information and if needed try to extract this into a microtest. Sadly this is for a closed-source client and I can't publish all the code.

**Comment by krisives** [comment]
Haha did you ever keep that $5 of coin I sent you?

**Comment by gabordemooij** [comment]
Lost it, I exported the wallet when I migrated to a new laptop, however the exported files weren't working. Very frustrating! Maybe it was a bug, maybe it was my own mistake, I don't know. Anyway it was a useful experience into the bitcoin universe. I have written a couple of Ethereum apps lately for clients.
