### ISSUE TITLE
Functionality not available when installing with composer

### ISSUE THREAD

**Issue by mozey** [gabordemooij/redbean#273]
The web page mentions:

_This means the R-class in the all-in-one pack contains some plugins that are not available in the aliased Facade Class of the composer package. I therefore recommend to just download the all-in-one package._

Does that mean there is missing functionality when using composer? 

Can the missing plugins be installed using composer?

**Comment by abouvier** [comment]
You can compile `rb.php` like this:
```json
{
    "require": {
        "gabordemooij/redbean": "^4.3"
    },
    "scripts": {
        "post-update-cmd": [
            "cd vendor/gabordemooij/redbean && php replica2.php onlyphp"
        ],
        "post-install-cmd": [
            "@post-update-cmd"
        ]
    },
    "autoload": {
        "files": [
            "vendor/gabordemooij/redbean/rb.php"
        ]
    }
}
```
