### ISSUE TITLE
Connection errors needs to be more verbose

### ISSUE THREAD

**Issue by alrik11es** [gabordemooij/redbean#361]
While preparing the configuration of RB on a server I was getting an error message like this:

PDOException [ Error ]:
Could not connect to database (d0b81ebd1e17b4ebeb4f0ead3b4e935ad).

I was becoming crazy so I set up a simple connection with PDO

``` php
try{
    $dbh = new pdo( $dsn,
                    $user,
                    $pass,
                    array(PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION));
    die(json_encode(array('outcome' => true)));
}
catch(PDOException $ex){
    die(json_encode(array('error'=>print_r($ex, true),'outcome' => false, 'message' => 'Unable to connect')));
}
```

So the real message was:

PDOException Object ( [message:protected] => could not find driver....

I think that this kind of messages should be more intuitive.
I was using "gabordemooij/redbean": "3.*" from composer.

**Comment by alystair** [comment]
Sorry for bumping this ancient issue - but I just went through a similar experience only to figure out the issue via a simple raw PDO try/catch (the server's account whitelist wasn't resolving hostnames in a timely manner).

Connectivity issues should be covered in the documentation's R::setup section, at least the rational described here re: security so developers can quickly get a more verbose error :)
