### ISSUE TITLE
Table prefixes or underscore in table name

### ISSUE THREAD

**Issue by Keeo** [gabordemooij/redbean#388]
Looking for the way how to add table prefix i found others asking the same thing. Response was always same - not supported. Well thats nice, but when you are working with existing schema you cant change it. So the solution is to use other ORM? Actively disallowing underscores in table names make it look even worse, or is there actually reason for not allowing R::dispence("foo_bar")? Anyhow changing regex in dispense works for my one little table.

**Comment by alexweissman** [comment]
I know this is an old thread, but what if RedBean allowed table prefixes, but used its own convention for those as well?  For example, [the `$` character is a valid MySQL table character](http://dev.mysql.com/doc/refman/5.0/en/identifiers.html).  So a "prefixed" RedBean table might look like `tbl$product`, `tbl$product_shop`, etc.  Then it would just be a matter of parsing out everything before the `$`.

I agree with you that table prefixes are bad form, but people are going to keep on using them as long as Wordpress has the web by the balls.

There are also some cases (again, where someone has made a stupid decision) when a developer is only allowed to use one database by their hosting service.
