### ISSUE TITLE
Redbean not using cursors

### ISSUE THREAD

**Issue by emasab** [gabordemooij/redbean#394]
Hi, I was using redbean for the migration of a mysql db. I noticed that when you you use R::getAll
the RPDO class makes a call to the method fetchAll of the PDOStatement. 

This loads all the result set in ram and can fill all the memory available if the result set is huge. Also, using the skip and limit approach is not viable as when the skip parameter is very high the query slows down because the db has to read many rows before coming to the right results. 

Instead, if you just return the statement and iterate over it with foreach, you fetch one row at a time, so you don't have to use the skip parameter and the result set can as large as you want.

I made it work extending the RDBO and overriding the runQuery function, the improvement was huge. The change was this:

```php
$this->resultArray = $statement; //->fetchAll( $fetchStyle );
```

I hope this feature can be included in the next releases.

Thanks for ReadBeanPHP
Emanuele Sabellico

**Comment by gabordemooij** [comment]
Implemented basic support for cursors.
