### ISSUE TITLE
Incorrect documentation example for models ?

### ISSUE THREAD

**Issue by Phyks** [gabordemooij/redbean#409]
Hi,

On [this page](http://redbeanphp.com/models) of the doc, I think there may be some wrong example code. Using

```
//with namespace Model
define('REDBEAN_MODEL_PREFIX', '\\Model\\')

class \Model\Band extends \RedBeanPHP\SimpleModel { ... }
```

I get a PHP parser error (expecting token ident (string) and not namespace separator(\)).

I may have missed something, and it may be an error from my part, but I think it would be better if one could simply copy/paste the examples from the doc and get some basic working system.

For what it's worth, here is the working snippet I use:

```
namespace Model;
class Model extends \RedbeanPHP\SimpleModel { … }
```

Thanks

**Comment by nonzer0value** [comment]
Your class name is the same as the namepace... I used this just fine:

```php
define('REDBEAN_MODEL_PREFIX', '\\MyStuff\\Model');
```

Then...

```php
namespace MyStuff;

use Psr\Log\LoggerAwareTrait;
use RedBeanPHP\SimpleModel;

class Model extends SimpleModel
{
  use LoggerAwareTrait;

  public function dispense()
  {
    $this->logger->debug('GOT THIS', ['event' => __METHOD__]);
  }  
}
```

This is my base Model class. I anticipate the need to add common functionality in the future via custom "FUSE" methods, so I've decided that my models are not going to _directly_ inherit from `SimpleModel`.

Moving on...

```php
namespace \MyStuff\Model;

use MyStuff\Model;

class CoolModelThingy extends Model
{
}
```

To ensure a logger gets injected (via `MyStuff\Model::setLogger`) whenever a  `Model` object is instantiated, I pass a closure to `SimpleFacadeBeanHelper::setFactoryFunction()` as described [here](http://www.redbeanphp.com/models). I import my dependency-injection system into the closure's scope to give the factory function access to my logger service.

YMMV, but for me it works as expected.

~nzv
