### ISSUE TITLE
$adapter->getAssoc - multiple columns

### ISSUE THREAD

**Issue by razvanioan** [gabordemooij/redbean#413]
If I run this: `R::$adapter->getAssoc("SELECT col1, col2 FROM table");`

I get the correct result. Associative array with `col1` values as keys.

However, I need to return multiple values, and have tried: `R::$adapter->getAssocRow("SELECT col1, col2, col3 FROM table);`

It returns a non-associative array with the three columns as values: `array(0 => array('col1' => 'val1', 'col2' => 'val2', 'col3' => 'val3'));`

instead of: `array('val1' => array('col2' => 'val2', 'col3' => 'val3'));`

Am I missing something in here ?

**Edit:**

I just took a look on the `rb.php` and found that only `adapter->getAssoc` returns values of the first column as keys, but it doesn't work with more than two columns (like other adapters do).

I will try to figure it out how I can override this method or create new one without messing up the framework source.

**Comment by razvanioan** [comment]
I couldn't find how I can extend a DBadapter method (using R::ext() for sure doesn't work)

I would change this method like the following (just adding the more than 2 columns option):
```php
public function getAssoc( $sql, $bindings = array() )
{
	$this->sql = $sql;

	$this->signal( 'sql_exec', $this );

	$rows  = $this->db->GetAll( $sql, $bindings );

	$assoc = array();
	if ( !$rows ) {
		return $assoc;
	}

	foreach ( $rows as $row ) {
		if ( empty( $row ) ) continue;

		if ( count( $row ) > 2 ) {
			$key   = array_shift( $row );
			$value = $row;
		} elseif ( count( $row ) > 1 ) {
			$key   = array_shift( $row );
			$value = array_shift( $row );
		} else {
			$key   = array_shift( $row );
			$value = $key;
		}

		$assoc[$key] = $value;
	}

	return $assoc;
}
```

**Comment by gabordemooij** [comment]
Incorporated the suggested change in the master branch, you can safely edit the source now.
