### ISSUE TITLE
how can i set collation to utf8_unicode_ci

### ISSUE THREAD

**Issue by r3wt** [gabordemooij/redbean#414]
That is my db collation, but redbean insert with utf8mb4

**Comment by gabordemooij** [comment]
I recommend to change your collation then, utf8_unicode_ci may cause data loss:
http://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc

**Comment by gabordemooij** [comment]
https://news.ycombinator.com/item?id=7317717 (the data loss example)

**Comment by r3wt** [comment]
I don't get it. Is this your explantion for the multibyte encoding? To prevent data loss?

Sent from my Windows Phone
________________________________

**Comment by gabordemooij** [comment]
utf8_unicode_ci will truncate your data if you insert a turd emoji (for instance), unless your application handles these cases I think that collation is quite dangerous to use (in my opinion it's broken). utf8mb4 is the same as utf8ci but supports 4 bytes (like the standard), so you can store all utf8 code points plus you don't have to worry about MySQL's insane error handling. I think that's pretty reasonable.

**Comment by r3wt** [comment]
Alright thank you for the knowledge, but I would still prefer the choice of a different encoding. Not all applications take public input so subjecting to the encoding that is slower full text search is suboptimal,  not to mention the support of unneeded characters. I like that this is the default but could be overwritten in the dispense, setup, or store method. Other than this small gripe I think red bean is great. My productivity has doubled when using it in development then I can easily translate Auer to stored procedure later

Sent from my Windows Phone
________________________________
