### ISSUE TITLE
The documentation does not clearly state what the output of an empty result set would be

### ISSUE THREAD

**Issue by r3wt** [gabordemooij/redbean#415]
I've tried my script with null and empty and neither one seems to work. i get a notice later in the script about an undefined index, when i am trying to sort this multidimensional array once based upon votes, once upon views. i need to catch an empty result set from both of the queries in the `foreach` loop and then manually patch in the values. any ideas? the documentation doesn't mention anything.

```php

foreach($videos as &$video){
	if(!file_exists($cache_path.$video['hash'].'.json')){
		$video['votes'] = R::getRow('SELECT COUNT(CASE WHEN vote_up = 1 THEN 1 END) up, COUNT(CASE WHEN vote_down = 1 THEN 1 END)down FROM vote WHERE video_id=:video LIMIT 1',
			['video'=>$video['id']]
		);
		if(empty($video['votes'])){
			$video['votes'] = ['up'=>0,'down'=>0];
		}
		$video['views'] = R::getCell('SELECT COUNT(id) AS views FROM view WHERE video_id=:video LIMIT 1',
			['video'=>$video['id']]
		);
		if(empty($video['views'])){
			$video['views'] = 0;
		}
		fwrite(fopen($cache_path.$video['hash'].'.json','w'),json_encode($video));
		$cat = $video['category'];
		if(!is_scalar($video)){
			$categories[$cat][] = $video;
		}
	}
}
```

I'm not really sure why it isn't working. FWIW, i am running under HHVM 3.5.0

**Comment by gabordemooij** [comment]
Ask questions on the forum please.

**Comment by gabordemooij** [comment]
I have no idea what's going on in this script, this question is way too vague.
For what it's worth: R::getCell alsways returns a scalar (or NULL) while R::getRow etc always return arrays.
