### ISSUE TITLE
Row versioning support

### ISSUE THREAD

**Issue by geemang2000** [gabordemooij/redbean#417]
Is there support for versioning ? My requirements are:
a) Timestamp on record creation
b) Create a new record for each update
c) Retrieve history of a record (listing all the versions that exist)
d) Get the current version on regular find
e) Easy way to mark a record as current

**Comment by gabordemooij** [comment]
These are all very easy to do with RedBeanPHP, but it's a bit too high level (application level) to build this directly into RedBeanPHP.

**Comment by nicolas-leclerc** [comment]
Hi
thanks for redbean !

I will be interested by a sample code for Row versioning support
