### ISSUE TITLE
The ownerId bean property is not converted to snake_case

### ISSUE THREAD

**Issue by CarlosLlongo** [gabordemooij/redbean#418]
Hi,

This is my test code:
```php
$oBean = \R::dispense('test');
$oBean->ownerId = 1;
$oBean->userId = 2;
$oBean->testId = 3;
        
\R::store($oBean);
```
I would expect to find a table test with the fields owner_id, user_id, and test_id. The last two are created as expected, but ownerId is not:

![redbean-ownerid](https://cloud.githubusercontent.com/assets/6555848/6489352/fa4296a4-c29d-11e4-80e7-a9aa72ae0b04.png)

Any idea why this happens?

Thanks!

**Comment by shark0der** [comment]
Seems to be a conflict with relationships: http://redbeanphp.com/one_to_many
The check is done at line 1955:

**Comment by gabordemooij** [comment]
Thanks for reporting this, fixed: https://github.com/gabordemooij/redbean/commit/72ea1a3069c3412148182aa5dac158021fa8cd7b
