### ISSUE TITLE
How do I get insert id after using R::exec

### ISSUE THREAD

**Issue by RamadhanAmizudin** [gabordemooij/redbean#419]
Hi, for the odd reason I had to use R::exec function to insert new data. 
The problem is, how do I get insert id after doing R::exec?

**Comment by gabordemooij** [comment]
R::getAdapter()->getInsertID();

**Comment by gabordemooij** [comment]
https://github.com/gabordemooij/redbean/commit/7402111f05b4b38825709b59190b975d18e50678

;)

**Comment by RamadhanAmizudin** [comment]
thanks! :D
