### ISSUE TITLE
Missing RB4 alias documentation

### ISSUE THREAD

**Issue by shark0der** [gabordemooij/redbean#420]
`alias` and `fetchAs` methods are not documented in RB4 which made me think they're obsolete but afterwards I found that `alias` is mentioned on ["Other relations" page under "Aggregation"](http://redbeanphp.com/other_relations#aggr) section.
I think it would be a good idea to include `alias` and `fetchAs` in the RB4 docs.

Also, the project/teacher/student example is a little bit confusing (maybe it's just me!). In my project I had the `brand` bean and had to implement related brands - a many-to-many, self-referenced table.
I end up doing something like this:

```
// dispose
$brand = R::dispose('brand');
list($related_brand_1, $related_brand_2) = R::dispose('brand', 2);
list($relation_1, $relation_2) = R::dispose('relation', 2);

// link
$relation_1->brand = $brand;
$relation_1->alias('related')->related = $related_brand_1;

$relation_2->brand = $brand;
$relation_2->alias('related')->related = $related_brand_2;

$brand->ownRelationList = [$relation_1, $relation_2];

// save
R::storeAll([$brand, $related_brand_1, $related_brand_2]);

// load
$related_brands = $brand->aggr('ownRelationList', 'related', 'brand');
```

I hope I'm doing it right :)

BTW, thanks a lot for `aggr` - saved my life :D

**Comment by gabordemooij** [comment]
fetchAs and alias are explained on page 'One-to-Fixed' http://www.redbeanphp.com/one_to_fixed

That chapter might have to be renamed someday :/
While it's a proper title in 'relational terms' absolutely nobody seems to click on that chapter :)

Your solution seems right to me. Self referential many-to-many is the most difficult case in RedBeanPHP. Hope aggr() makes your life a little easier.

If you have any suggestions for the manual please let me know.

**Comment by shark0der** [comment]
I completely overlooked that whole page and the name "one-to-fixed" made me think of it something completely different: bean of type `A` can have exactly x beans of type `B` related to it (more like a one to many relationship but a fixed number of possible relations). Perhaps "one-to-fixed" isn't really the best name for this because self-referencing is actually a truly many-to-many relationship (the only difference is the fact that the related beans are of the same type - that's it). I suggest changing the page title to "Aliasing". Even the first phrase on that page says "Sometimes you want to refer to a bean using a different name.".

**Comment by gabordemooij** [comment]
fixed.

http://www.redbeanphp.com/aliases

**Comment by shark0der** [comment]
Awesome!
