### ISSUE TITLE
Update Composer

### ISSUE THREAD

**Issue by kordianbruck** [gabordemooij/redbean#421]
Would be awesome to get composer support back!

**Comment by gabordemooij** [comment]
Last time I tried to added Composer support I got all kinds of trouble. So here is the thing, I'm considering to add Composer support again but I'm not going to change the layout of this repository, implement all kinds of PHP standards I don't agree with etc. Just send me the composer.json you want and I'll update the version strings for you.

**Comment by kordianbruck** [comment]
Isn't this enough?
```
{
    "name": "gabordemooij/redbean",
    "description": "ORM layer that creates models, config and database on the fly",
    "require": {
        "php": ">=5.3.0"
    }
}
```

**Comment by simirimia** [comment]
Just added a pull request:
https://github.com/gabordemooij/redbean/pull/422. 
Autoload entry in composer.json is also neccessary.

**Comment by kordianbruck** [comment]
awesome, thanks!
