### ISSUE TITLE
Possible memory leak in 4.x release

### ISSUE THREAD

**Issue by jamesjnadeau** [gabordemooij/redbean#424]
Using the latest 4.1.4 compiled release from redbeanphp.com:
I was running an import of 100's of thousands of csv rows. I was having an issue with memory usage growing over time. I tried isolating everything I was doing, but still the leak persisted.

Finally, after some hair pulling :) I switched back to the 3.5 version, and my memory usage is stable. The switch was painless though

 No clue where it could be coming from. When I get a chance I'd like to test this out with the new php debugger in 5.6. 

I'm using a  R::find to check for an existing row, and then R::dispense, and R::store if I need to add the row. Turning off either of these call's did not remove the memory leak for me(if I recall correctly, I was throwing a lot of stuff at it to try and isolate the issue.

**Comment by gabordemooij** [comment]
Might be the query cache, interesting issue.

**Comment by gabordemooij** [comment]
I think this fixes the issue.

https://github.com/gabordemooij/redbean/commit/5892a16b78c26a049e7295b1bdf0369ecdbcb331

**Comment by jamesjnadeau** [comment]
I can confirm that in a limited test, this fixed my issue! Thank you so much for your time!

Just a suggestion, but perhaps the 20 you set as the default number of queries to cache should be configurable in some way. I probably won't ever set this, but just came to mind when I was looking over your solution.

**Comment by gabordemooij** [comment]
agreed
https://github.com/gabordemooij/redbean/commit/9fde8524d69436099909e34cd84ed5bf29943fa5

**Comment by bilogic** [comment]
Hi,

I'm running an import of ~200 lines of CSV with each line being processed by several models.
I have cached disabled, but memory is leaking and the import of each line gets slower and slower.
1st row takes 1 sec, 2nd row takes 1.5 sec, 3rd row takes longer etc. If I start directly on the 3rd row, it takes 1 sec.

If I remove all codes from the models, the leak stops.

I'm wondering if there is a proper way to destruct beans? I tried writing my own but leaks still happen. I can paste the codes here if it helps. Basically I would like to call the destructor after I'm done with each line.

Thank you.

**Comment by jamesjnadeau** [comment]
@bilogic I'd recommend starting your own issue and referencing this one, rather than piggy backing on my issue. Your's seems related, but not the same.

**Comment by bilogic** [comment]
Ok, sorry about that.

**Comment by jamesjnadeau** [comment]
@bilogic No worries what-so-ever, best of luck!
