### ISSUE TITLE
help needed - create two connections at the same time

### ISSUE THREAD

**Issue by monbro** [gabordemooij/redbean#428]
Hi, I added already a question into the forum: https://groups.google.com/forum/?fromgroups=#!searchin/redbeanorm/connections%7Csort:date/redbeanorm/lG8HAkrQr7U/28kpHgf_hWsJ

I want to create two connections (represented by two variables) to different tables of the same database. Unfortunately I could not figure out yet how to do so. Maybe someone can give me a hand? Thank you very much!!

**Comment by monbro** [comment]
Okay i just had a read of https://github.com/gabordemooij/redbean/issues/337. Any updates on this?

**Comment by monbro** [comment]
okay after wanting to flip my table, I simply copied the Facade class and named it to FacadeTwo. Then I simply do the same configuration for a new instance of this class and will simply select a different database then for the original Facade.

I am really not happy with this, but this seems to be the easiest workaround so far.

**Comment by gabordemooij** [comment]
Well, if you like instances, why are you using a *static* facade? Why not simply use the objects 'behind' the facade?

**Comment by monbro** [comment]
@gabordemooij Well I am already happily using the shortcut functions from the Facade within my app as it is quick and easy to work with the whole ORM then. Isn't that the point of redbeans and furthermore the facade?
