### ISSUE TITLE
Is it possible to escape a colon in a bound parameters, to prevent it from being treated as a bound parameter?

### ISSUE THREAD

**Issue by r3wt** [gabordemooij/redbean#429]
In the screenshot, i'm using Regular expression to search in a table that contains some json. problem is, when adding a bound parameter to the query, it treats the json seperator : as the start of a new named parameter. is there a work around for this?

**Fig1: Query is valid**
![img](http://puu.sh/gVmsl/d791e121ac.png)
**Fig2: Redbean seems to be treating the colon in the REGEXP as a bound parameter**
![img2](http://puu.sh/gVmRW/9c1f2afb0a.png)

**Comment by diego-vieira** [comment]
What if you use `?` to pass the parameters?

```php
R::getAll('product', 'category = "bolt" AND brand = ? AND specs REGEXP ? AND specs REGEXP ? LIMIT 0, 12', array('Excalibr', 'your regex', 'your regex'));
```

**Comment by r3wt** [comment]
@diego-vieira  i might try that next to see what happens, but from my quick parusal of the source redbean converts numbered keys in bind statements to slotted statements ie, like `'slot'.$i`

**Comment by gabordemooij** [comment]
Strange, this test code works as expected:

    echo R::findOne('book', ' title REGEXP :title OR title REGEXP :title ', array(
        ':title' => 'Lots of :colons !'
    ));

**Comment by gabordemooij** [comment]
I use REGEXP and JSON a lot myself ;)

**Comment by r3wt** [comment]
@gabordemooij save me! (plz)

**Comment by gabordemooij** [comment]
Can you send me a standalone code snippet that produces the issue?

**Comment by gabordemooij** [comment]
Tried again, this query also does not give an error, although it finds nothing...

    require 'rb.php';
    $p = R::dispense('product'); 
    $p->category = 'bolt'; 
    $p->brand = 'Excalibur';
    $p->specs = json_encode(array('Length'=>18, 'Weight'=>250));
    R::store($p);

    R::fancyDebug(true);
    $q = R::getAll('SELECT * FROM product WHERE category="bolt" AND brand=:brand AND specs   REGEXP :length AND specs REGEXP :grains LIMIT 0,12 ', array(
	':brand' => 'Excalibur',
	':length' => '"(.*\"*.Length.*\":\"*.18.*\"*.)"',
	':grains' => '"(.*\"*.Weight.*\":\"*.250.*\"*.)"' 
    ));

**Comment by r3wt** [comment]
You are using colons directly in the keys though. I am not

**Comment by gabordemooij** [comment]
That might be the issue, the colon seems to be 'required' however PHP will try to fix it if it has been omitted, maybe PDO gets confused by then: http://stackoverflow.com/questions/9778887/is-the-leading-colon-for-parameter-names-passed-to-pdostatementbindparam-opt

**Comment by gabordemooij** [comment]
However, even without the colon, the query still works over here. Are you using the latest beta?

**Comment by r3wt** [comment]
no, i'm using stable release downloaded from redbean website with wget

**Comment by gabordemooij** [comment]
Try the new version 4.2, maybe this has been fixed

**Comment by gabordemooij** [comment]
It will be released in a few minutes... (always April 1)

**Comment by gabordemooij** [comment]
Yup, released

http://www.redbeanphp.com/download

**Comment by gabordemooij** [comment]
Added unit test for this issue

https://github.com/gabordemooij/redbean/commit/0ebffcaa0559fc6dd07f58b5bb21160452048a26

**Comment by r3wt** [comment]
Awesome, thank you @gabordemooij  for all of your help! I'll try it out and report back with the results.

**Comment by r3wt** [comment]
@gabordemooij 

It still doesn't work

I'm running HHVM:

```

HipHop VM 3.5.0 (rel)
Compiler: tags/HHVM-3.5.0-0-ga90f4733cfa0d8fefdafc7433f758f78cdc75424
Repo schema: b88b6fee8ef78ab638506d212abcbefe74a276ac

```

**Comment by gabordemooij** [comment]
Hm, interesting, that raises several questions...

* Have you tried the (traditional) Zend Engine ?
* Does my example above also trigger the error (findOne) ?

**Comment by r3wt** [comment]
@gabordemooij  i can't do find one. its one of those product pages where they use select box to sort and add parameters to the query. its expected to return array of results. I cannot use Zend Engine either. yuck

**Comment by gabordemooij** [comment]
You can copy-paste it in a simple stand-alone test file and run it via CLI?
I tried to test with HHVM before but Travis has an incomplete test environment for HHVM (it lacks postgres support for instance) and it takes too much time for me to prepare a virtualbox for every single version of PHP.

**Comment by r3wt** [comment]
The function is several hundred lines long, and is integrated into a large MVC app built with Slim Framework. i will try to prepare you a model and test file, but it might not be possible

**Comment by gabordemooij** [comment]
You don't have to use the real function. We're trying to find out if RedBeanPHP or PDO confuses the colons in the SQL, so you can simply copy-paste the query in a file and run it.

Just do:

    R::setup();
    R::store(R::dispense('book')->setAttr('title'));

and fire the findOne query above..

or am I missing somthing here?

**Comment by gabordemooij** [comment]
meanwhile I will prepare an HHVM image...

**Comment by r3wt** [comment]
using your test file:

![img](http://puu.sh/gY6fl/c29a8e58a6.png)

```php

require 'rb.php';

R::setup();
R::store(R::dispense('book')->setAttr('title'));

echo R::findOne('book', ' title REGEXP :title OR title REGEXP :title ', array(
    ':title' => 'Lots of :colons !'
));


```

**Comment by gabordemooij** [comment]
see my update, I was in hurry...

**Comment by r3wt** [comment]
so basically i have a giant function that runs and generates a query for the results, and then also for the total count of a query(count is used to get 'count /perpage' to generate pagination)

then i run the queries like this

```php
try{
		if(empty($params)){
			$data = R::getAll($query);
			$total = R::count('product',$param_string);
		}else{
			$data = R::getAll($query,$params);
			$total = R::count('product',$param_string,$params);
		}
	}
	catch(exception $e){
		if($debug){
			$msg = 
			'<pre>'
			.print_r(
				[
					'query'=>$query,
					'params'=>$params,
					'param_string'=>$param_string,
					'error'=>$e->getMessage()
				], 
				true
			).
			'</pre>';
			$app->e($msg);	
		}else{
			$data = [];
			$total = 0;	
		}
	}
```

**Comment by r3wt** [comment]
if you will notice, this error doesn't happen when only binding the two regexp's. it happens when something else is bound prior to binding the regexps, like in the example where brand is bound then the two regexps are bound later in the query. it is bizarre to me, i can't grasp why but it is probably my fault too

**Comment by gabordemooij** [comment]
Just tried your example on HHVM 3.6.1 on Debian Wheezy but seems to work fine ?!???!

**Comment by r3wt** [comment]
so strange. i wish i knew why this was happening

**Comment by gabordemooij** [comment]
Hm wait
I think the issue is with count, you pass param_string which has the regexes filled in but not the :brand filled in and you still pass the params?

**Comment by gabordemooij** [comment]
Maybe I dont understand, why pass $params if you already fill in the params in $param_string and why are the regexes filled in properly but not the brand?

**Comment by gabordemooij** [comment]
Where does $param_string come from ?

**Comment by gabordemooij** [comment]
by the way, the colon test passes for hhvm on Travis:

https://travis-ci.org/gabordemooij/redbean/jobs/56786410

However they seem to use a 32bit SQLite binding, hm, that's a shame.

**Comment by r3wt** [comment]
`$param_string` and `$params` are different `$params` are the params *FOR BOTH QUERIES* `$param_string` is the second argument for `R::count()`...

**Comment by gabordemooij** [comment]
No need, I can now reproduce the issue and fix it:

This will cause the error (and this is what happens right now in your code, I use findOne, but it does not matter, same applies to count/getAll):

    $param_string = '
    category="bolt" AND brand=:brand  AND specs REGEXP "(.*\"*.Length.*\":\"*.18.*\"*.)"  AND specs REGEXP "(.*\"*.Weight.*\":\"*.250.*\"*.)"
    ';
    R::findOne('product', $param_string, array(
    ':brand' => 'Excalibur',
    ':length' => '"(.*\"*.Length.*\":\"*.18.*\"*.)"',
    ':grains' => '"(.*\"*.Weight.*\":\"*.250.*\"*.)"'
    ));

This code fails because you provide 3 parameters yet $param_string contains only ONE slot.
This code fixes the issue:

    $param_string = '
    category="bolt" AND brand=:brand  AND specs REGEXP "(.*\"*.Length.*\":\"*.18.*\"*.)"  AND specs REGEXP "(.*\"*.Weight.*\":\"*.250.*\"*.)"
    ';
    R::findOne('product', $param_string, array(
    ':brand' => 'Excalibur',
    ));

So, like I said in the previous post, the contents of $param_string does not match the bindings in $params. It has nothing to do with RedBeanPHP or PDO confusing the colons, it's simply because $params has *too many* bindings for the query you provide.

Anyway, my email is gabor at redbeanphp dot com.

**Comment by r3wt** [comment]
Wow. so this entire time the problem existed between keyboard and chair...

**Comment by gabordemooij** [comment]
Luckily we solved it :)

**Comment by r3wt** [comment]
@gabordemooij It goes without saying, i am very thankful for your help. At the same time, i am sorry that i wasted your time with this non issue. I am feeling the shame haha

**Comment by gabordemooij** [comment]
No problem, just happy it wasnt a bug :)
