### ISSUE TITLE
Memory leak in 4.2 beta 8 using findCollection

### ISSUE THREAD

**Issue by valtonia** [gabordemooij/redbean#430]
Running a test using findCollection on a large resultset shows a memory leak:

PHP 5.5.9 with memory limit set to 128MB on Ubuntu 14.04

    R::setup("mysql:host=localhost;dbname=db", "user", "pass");
    R::freeze(TRUE);
    
    $all = R::findCollection('booking_pax', 'booking_id >= :booking_id', [':booking_id' => self::BOOKING_ID]);
    
    while($r = $all->next())
    {
    }

The query returns ~700K records of <1KB each.  Memory is exhausted after iterating ~28K records.  My expectation would be that this code should be able to iterate the entire result set without using much memory - especially considering that there is no code inside the while-loop.

**Comment by gabordemooij** [comment]
I cannot reproduce this issue, on PHP 5.4 this code does not leak memory.
If I add an array $c and put all the records in the array I see a leak but that's to be expected.
Is there any possibility you are collecting the beans somewhere, some caching maybe?

**Comment by valtonia** [comment]
Hi. Apologies for raising this issue in error.  
I was originally running the test inside a framework.  After reading your comment I re-ran the test in a standalone environment and there is no memory leak.

Actually I'm quite relieved because I really want to use RB in a project and this could have been a show-stopper.

Thanks for checking this for me.

**Comment by gabordemooij** [comment]
No problem. Good to hear there is no memory issue. Good luck with your project!
