### ISSUE TITLE
Trying to wrap Redbean and getting error from my autoloader.

### ISSUE THREAD

**Issue by r3wt** [gabordemooij/redbean#431]
@gabordemooij  - could you please give me an insight into what it happening here, and why i am unable to use Redbean in this way
```
namespace Foo\Bar;

class DB implements ApplicationDataMethods
{
	function __construct($db_config)
	{
		$this->configure($db_config);
	}	
	
	public function configure($c)
	{
		\R::setup('mysql:host='.$c['host'].';dbname='.$c['name'],$c['user'],$c['pass']);
	}
	
	public function fetchUserDetailsByEmail($email)
	{
		return \R::getRow('SELECT * FROM user WHERE email=:email',[':email'=>$email]);
	}
	
	public function isEmailInUse($email)
	{
		$res = \R::getCell('SELECT id FROM user WHERE email=:email',[':email'=>$email]); // 1 true, 0 false
		return (bool) $res;
	}
	
	public function get_model($type,$id=false)
	{
		if($id){
			return (\R::load($type,$id));
		}else{
			return (\R::dispense($type));
		}
	}
	
	public function store_model($model)
	{
		return (\R::store($model));
	}
}
```
The error i get is:
```
error: Foo::autoload() Class not found! (Model_User)|/usr/share/nginx/html/libs/Foo/autoload.php|11
```

It appears that Redbean is trying to instantiate some type of model in my namespace? how can i prevent this behavior?

**Comment by r3wt** [comment]
So oddly i was able to resolve the issue by creating an empty model. Is there someway to disable this feature? It kind of defeats the purpose of using Redbean if you're going to force me to use an anti-pattern

**Comment by gabordemooij** [comment]
Your autoloader is broken, see the forum / github for many similar issues.
Boils down to the fact that the autoloader throws an exception when PHP 'asks' (not requires...) whether it exists - this is a very common bug in autoloaders.

**Comment by r3wt** [comment]
Alright @gabordemooij thanks for the clarification. Its nice to know i can just remove the exceptions from my autoloader in production and remove all of the models if i don't end up needing them
