### ISSUE TITLE
Current Timestamps

### ISSUE THREAD

**Issue by renomx** [gabordemooij/redbean#436]
Hi all,  i've been searching if RedBeanPHP is capable of creating default fields with timestamps for a table, e.g. 

If i am creating a books table and i want to have the created_at and updated_at fields created automatically with the default value been the actual date.

R::dispense('book', true, 'UTC');

Maybe the third parameter being the timezone.

I don't know if a feature like this exists already and if it does exist my most sincere apologies!

Thanks.

**Comment by gabordemooij** [comment]
You can add this sort of logic in the model.
Simply create a model like: Model_Book and add these fields in the update() method. When you save the bean, the update() method in the model will be invoked automatically: http://www.redbeanphp.com/models

**Comment by renomx** [comment]
Thank you very much Gabor, sorry for not answering sooner but this is exactly what i was looking for.
