### ISSUE TITLE
if table doesn't exist, redbean created an int(11) unsigned column for any string property ending in an numeric value like "abc123"

### ISSUE THREAD

**Issue by r3wt** [gabordemooij/redbean#438]
else i have no idea what happened. here's the code that resulted in this (seemingly) unexpected behavior.

```php
//assume that $tx is an model of type "transaction"

$db = \App\DB::getInstance(); //returns an instance of DB abstraction layer built on Redbean.
$prefix = 'abc';
$tx = $db->model('transaction');
$tx->tx_id = $db->getUnusedTxId($prefix);


//public function getUnusedTxId($prefix)
public function getUnusedTxId($prefix,$trys = 0)
{
	$prefix = str_replace(
		[' ','_','.','&',','],
		'',
		$prefix
	);
	if($trys > 100 && strpos($prefix,'-') === false){
		$prefix .= '-';
	}
	$word = '';
	for($i = 0; $i < 4; $i++){
		$word .= strval(rand(0,9));
	}
	$tx = $prefix.$word;
	if( !empty( \R::getRow('SELECT id FROM transaction WHERE tx_id=:tx AND active="1"',[':tx'=>$tx]) ) ){
		$tx = $this->getUnusedTxId($prefix,++$trys); //recursion
	}
	return $tx; //so function would return $prefix + 4 charachter numeric string.
}
```

The first run of this code resulted in the following `tx_id`:

 `Morris0120`

redbean created and `INT(11)` column, which resulted in a stored value of `0`

going to the db and manually changing column to varchar solved the issue.

**Comment by r3wt** [comment]
was able to confirm the issue. i will prepare a test case if necessary.

**Comment by gabordemooij** [comment]
Thanks for reporting this. I just read the post, I will research this issue.

**Comment by gabordemooij** [comment]
Unfortunately I have been unable to confirm this issue.


Code:

     R::nuke();
     $test = R::dispense('test');
     $test->text = 'test123';
     R::store($test);
     print_r(R::inspect('test'));

Output:

     Array
     (
         [id] => int(11) unsigned
         [text] => varchar(191)
     )

**Comment by r3wt** [comment]
the name of your column needs to end in `_id`

**Comment by gabordemooij** [comment]
Ah, I see.

_id is a reserved prefix in RedBeanPHP, it denotes a reference to an database key.

This is part of the RedBeanPHP schema policy.
