### ISSUE TITLE
How do I call Database escape function manually?

### ISSUE THREAD

**Issue by RamadhanAmizudin** [gabordemooij/redbean#439]
example: mysqli_real_escape_string, for postgress, etc.

**Comment by gabordemooij** [comment]
You dont have to use that function, use bindings instead.
Old style database functions are deprecated in PHP and they are not being used in RedBeanPHP. Instead you can use the PDO functions, to get the PDO object:

     $pdo = R::getDatabaseAdapter()->getDatabase()->getPDO();
     $pdo-> some raw pdo command... ( ... )

**Comment by gabordemooij** [comment]
If you have any more questions, please ask them using our RedBeanPHP forum:

https://groups.google.com/forum/?fromgroups#!forum/redbeanorm

There are many community members that can assist you with RedBeanPHP questions.
