### ISSUE TITLE
Multiple Facade

### ISSUE THREAD

**Issue by gregoirer** [gabordemooij/redbean#440]
First of all thank you for this very good ORM you make.I use it every day with joy.
This message it's not an issue but more a suggestion/discussion. 
I have lot of code with \R::xxx but I need now to connect to several other databases. With your design I should add before \R::xxx call \R::selectDatabase(YYY). So for each R call I will have finally two lines of code. It will work but I would prefer not to change the existing code. 
To keep it elegant it will be convenient for each database to do something like that
S extends RedBeanPHP\Facade{};
T extends RedBeanPHP\Facade{};

but unfortunately Facade is made of static properties. With non static variables it will work like a charm and this change may be transparent. What do you think ?

**Comment by gregoirer** [comment]
In fact my suggestion will not work :( . Sorry for the noise.

**Comment by gabordemooij** [comment]
You can use RedBeanPHP without the facade:
http://www.redbeanphp.com/non_static

Another possibility is to write a little plugin, wrapping the methods you need and make them pre-select the correct database first.
