### ISSUE TITLE
Error: A database has already be specified for this key

### ISSUE THREAD

**Issue by sclearion** [gabordemooij/redbean#441]
Is there a solvent workaround for "A database has already be specified for this key" when unit testing. If they key is already specified then why is it not invoked or used when called again? The Non-Static way is  verbose and is too coupled for our standards.

**Comment by sclearion** [comment]
Nevermind, we found the src of the exception and will hack it accordingly.

**Comment by maheshkajale** [comment]
I got the same error.

A database has already be specified for this key. in /var/www/html...

I have already setup one database and want to connect another database then I used R::addDatabase() function to add new databse and R::selectDatabase() function to select that database.

code is

define('dsn2', 'pgsql:host=localhost;dbname=mydb';
R::addDatabase('DB2', dsn2, 'dbusers', 'dbpasss');
R::selectDatabase('DB2');

**Comment by gabordemooij** [comment]
Sorry, there is no way around this. Some people got burned by the database keys, so I implemented this protection mechanism.

**Comment by Terkhos** [comment]
I'm having this same problem but i ain't using addDatabase, i only use setup, what could be causing this problem ? To make it work again i have to set R::$toolboxes = []; on the addDatabase method inside de Facade.php

**Comment by paooolino** [comment]
Sorry for reopening this. 

I'm facing the same problem and looked into the source code. 

Maybe I'm missing something, but sending R::close() I thought the current database "key" would have been removed. 

If it's not possible, we should have a method to clear the $toolboxes[$key] array, if not for production, just for tests. What do you think?
