### ISSUE TITLE
Getting  'Base table or view not found' with simple R::findOne, R::find, R::count before table exists

### ISSUE THREAD

**Issue by robertleeplummerjr** [gabordemooij/redbean#444]
Query
```php
R::count( 'group', ' name = ? ', [ 'Anon' ] );
```

Redbean latest
On: Ubuntu 15.04 with php 5.6.4

Oddly this happened just after I installed xdebug.

**Comment by robertleeplummerjr** [comment]
Stack trace:
Fatal error: Uncaught [42] - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'Enpowi.group' doesn't exist trace: #0 /home/robert/Projects/Enpowi/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php(312): RedBeanPHP\Driver\RPDO->runQuery('SELECT COUNT(*)...', Array) #1 /home/robert/Projects/Enpowi/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php(349): RedBeanPHP\Driver\RPDO->GetAll('SELECT COUNT(*)...', Array) #2 /home/robert/Projects/Enpowi/vendor/gabordemooij/redbean/RedBeanPHP/Adapter/DBAdapter.php(164): RedBeanPHP\Driver\RPDO->GetOne('SELECT COUNT(*)...', Array) #3 /home/robert/Projects/Enpowi/vendor/gabordemooij/redbean/RedBeanPHP/QueryWriter/AQueryWriter.php(988): RedBeanPHP\Adapter\DBAdapter->getCell('SELECT COUNT(*)...', Array) #4 /home/robert/Projects/Enpowi/vendor/gabordemooij/redbean/RedBeanPHP/Repository.php(526): RedBeanPHP\QueryWriter\AQueryWriter->queryRecordCount('group', Array, ' name = ? ', Array) #5 /home/robert/Projects/Enpowi/vendor/gabordemooij/redbean/RedBeanPHP/OODB.php(457): RedBe in /home/robert/Projects/Enpowi/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php on line 171

**Comment by robertleeplummerjr** [comment]
So after turning off xdebug, the issue "went away", but after putting an echo out on the line throwing it, it looks like the issue persists, xdebug was just not allowing it to continue when it happened.  It looks like there are quite a few errors when handling each use case.  Are there plans on handling these errors?

**Comment by gabordemooij** [comment]
I will have a look into this issue.
RedBeanPHP inspects the error from the database, if the database is capable of providing proper SQL ANSI error codes, it will only allow the error to bubble op if the database is frozen.

**Comment by gabordemooij** [comment]
I read some test code and it turns out count() is an exception.
Count will just return 0 if you try to count something that does not exist.

**Comment by robertleeplummerjr** [comment]
Shouldn't you have the situation rather than throw an exception?

**Comment by gabordemooij** [comment]
I dont understand what you mean.
You count something that does not exists, so it returns 0.
I don't know why xdebug throws an exception, I get no exceptions here. If I turn on R::debug() I see the error appear but the script continues as expected.

**Comment by gabordemooij** [comment]
Might be an xdebug configuration issue?
http://stackoverflow.com/questions/2904105/disabling-xdebugs-dumping-of-caught-exceptions

**Comment by robertleeplummerjr** [comment]
Xdebug is just more verbose.  The exception isn't being thrown there, it is
thrown in php.  It has been my experience that try and catch are not the
ideal way to handle these scenarios, especially if you know that in a
certain context a specific error would be thrown...  That being said,
redbean is not a normal project.  What it tries to accomplish is quite
amazing, and perhaps there is a specific reason why an exception it thrown
rather than handling the scenario.
