### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by tleb** [gabordemooij/redbean#449]
It seems to me that the [redbean website](http://redbeanphp.com) is down, message:

```
Connection refused: redbeanphp.com:80
```

Same with [`www.redbeanphp.com`](http://www.redbeanphp.com):

```
Connection refused: www.redbeanphp.com:80
```

**Comment by tleb** [comment]
Ok, it is accessible through `https`, but it has certificate issues.

**Comment by r3wt** [comment]
i've had similar issues with the website. it comes and goes.

**Comment by gabordemooij** [comment]
It should be availabe through http

**Comment by tleb** [comment]
It does, no more problems.
