### ISSUE TITLE
master vs RedBeanPHP3_5_X branch 

### ISSUE THREAD

**Issue by bilogic** [gabordemooij/redbean#451]
Hi,

I like to understand what is the difference between ```master``` and ```RedBeanPHP3_5_X``` branch.

I have some custom changes that was based off ```RedBeanPHP3_5_X``` https://github.com/gabordemooij/redbean/commit/ac9f76cc76bc9532ad87f585ea30999345c03d32

However the file ```redbean\RedBean\BeanHelper\facade.php``` is missing in master branch's https://github.com/gabordemooij/redbean/commit/30daba702e340fc94a25a4901c35ff538d1d21f8

I would like to rebase my custom changes onto the ```master``` branch to enjoy the newer features found in 4.x, thus my question in the first sentence. Thank you.

**Comment by bilogic** [comment]
I did a search and suppose ```SimpleFacadeBeanHelper.php``` in ```redbean\RedBeanPHP\BeanHelper``` is the file I'm looking for.

However, my question kind of remains, how will ```master``` branch evolve in the foreseeable future?
Will it get renamed into another ```RedBeanPHPxxxxx```? Thank you.

**Comment by gabordemooij** [comment]
Hi,

Hi RedBeanPHP3_5_X is the latest version of RedBeanPHP 3.5 LTS, this was the version before the 4.X series. This branch will only receive maintenance updates, patches and security updates. RedBeanPHP 3.5 will be supported like this until October 2016 (end of life date). I recommend to switch to RedBeanPHP 4.2 (master) as soon as possible. Most classes from 3.4 are still available in 4.2 but the 4-series use namespaces. Some names have been changed slightly to make them more descriptive.

Cheers,
Gabor

**Comment by bilogic** [comment]
Hi Gabor,

Thanks for the info. In your road map, will ```master``` be eventually renamed? (To ```RedBeanPHP4_2_x``` or whatever?)

**Comment by gabordemooij** [comment]
Depends, if I decide to deprecate 4.X it will be 'branched off'. Until then, master will always be the latest 4.X, which reminds me, I will soon clean-up the branches so all branches except 3.5 and master will soon be removed. To find a specific 4.X release you can use a tag (see github releases), if you want to patch a specific version you can branch off that tag.

**Comment by bilogic** [comment]
ok, I'm assuming "branched off" means renaming current ```master``` to ```RedBeanPHP4_2_x```. I assume this because the current ```master``` started somewhere in the middle of this repository, not since day 1. Some issues that will happen with this approach:

1. when the current ```master``` branch is renamed to ```RB42``` and eventually stopped (end of life), followers of the current ```master``` will be led into a dead end by ```RB42``` while a new ```master``` grows.

1. because a new ```master``` is created, new followers can't really track back its entire history.

1. and when this new ```master``` is eventually renamed, it breaks continuity again.

You mentioned ```tag``` and that confuses me now about your future plans. If I may suggest an alternative which I like to see:

1. ```master``` will always stay as the branch for version releases using ```tags```, this has the benefit of finding earlier specific releases like you mentioned. It must never be renamed due to problems I highlighted earlier.

1. for your policy of providing only security patches to deprecated branches, you can apply these updates onto branches "growing" out of their respective ```tags```

1. this way, new comers are unlikely to fork off these updates and folks at those ```tags``` can decide if they want to just receive the security patches or follow you forward into the latest ```master```

Of course you have your own considerations, but I only wish to share with you what I feel is a better approach. Thank you.
