### ISSUE TITLE
Json

### ISSUE THREAD

**Issue by MatthDefrenne** [gabordemooij/redbean#453]
I would like convert result like this : "R::findAll("books")" TO Json. BUT look my result : 

{"1":{},"2":{},"3":{}}"

Probably because the attribut of Object is protected, so what is the solution ?

**Comment by tleb** [comment]
[There](http://bfy.tw/U2t) you [go](http://stackoverflow.com/a/6068822).

**Comment by gabordemooij** [comment]
Hope this link to the doc resolves the issue. If not, please feel free to ask for further help on our forum.
