### ISSUE TITLE
One to many

### ISSUE THREAD

**Issue by andrewtheone** [gabordemooij/redbean#456]
Hey!
I'm in a hurry right now. My task now is to build a newsletter service for our company, I want to go with RedBean b/c its flexibility.
As any other newsletter service we will have a emails table, lists table and campaigns table along with clicks table and unsubscription table.

As I noticed RedBean supports joins, and one to many and many to many, etc relations.

My question is: Our emails table consists about 200k records. And when I'd like to print out a list of campaigns I'd like to display how many clicks did the campaign have. -We have to store each click in a new record b/c we'd like to target our audience by their interest so it's good to know which email clicked which link, and from those link clicks create a new list which only be sent to those certian subscribers.

Question is:
-Does RedBean autimatically grabs our related records when dispensing a bean or only when accessing the "list" attribute?
-If so when accessing the List attribute, then can I perform a count() operation on it?

Will it be efficient at 200k recors? - I'll put indexes...

**Comment by r3wt** [comment]
You should do it with raw SQL for optimal performance. I do all my joins with raw SQL. query you describe seems pretty simple.
