### ISSUE TITLE
Notice caused by  R::selectDatabase

### ISSUE THREAD

**Issue by NorHei** [gabordemooij/redbean#458]
When selecting a nonexistent Database like   
R::selectDatabase( 'defaulddt' );

I get a php notice. 

Notice: Undefined index: defaulddt in /var/www/web999/html/crudsomewhere_de/classes/rb.php on line 10280

Version 4.2.3 .   PHP 5.6 fast CGI

**Comment by gabordemooij** [comment]
Thanks for reporting this issue.
I think I am going to change this so the function will throw an exception instead.

**Comment by NorHei** [comment]
This would be really nice!
