### ISSUE TITLE
SQLite DATE/DATETIME Error

### ISSUE THREAD

**Issue by wanjochan** [gabordemooij/redbean#462]
For using SQLte with RB4,

When try to set value 'yyyy-mm-dd' or 'yyyy-mm-dd hh:mm:ss', the logic make the value into zero. I believe it's kinda bug instead of designed so.

**Comment by gabordemooij** [comment]
That's strange, I'll have a look.

**Comment by gabordemooij** [comment]
Seems to work just fine over here:

    require 'rb.php';
    R::setup();
    $bean = R::dispense('bean');
    $bean->date = '2015-01-01 10:00:00';
    R::store($bean);
    $bean = $bean->fresh();
    echo $bean;

outputs:

    {"id":"2","date":"2015-01-01 10:00:00"}
