### ISSUE TITLE
Non Static Facade is highly suggested.

### ISSUE THREAD

**Issue by wanjochan** [gabordemooij/redbean#463]
For the RedBean Quick Users,

The Static Facade is very productive for the quick programing.  But it is not insufficent to use for the case that more-than-one different DB connections needed, e.g. in a tool script we need to read from database A and update the database B.  

So a Non-Static Facade is highly suggested.   ( For my cases, I copy the class Facade and copy as RedBeanPHP\FacadeNonStatic and fixed some static-nonstatic issues.  )

**Comment by gabordemooij** [comment]
You can select another database like this:

R::selectDatabase('database-a');

So, you can simply switch between Dbs. Unless you're planning to do a threaded migration script there should be no problem.

**Comment by wanjochan** [comment]
Understood.
But selectDatabase() will switch the innner db to new one, then the following operations of the Facade is targeted onto the new one. 
That will pretty hurt the use case that need to keep more than one DB connected (e.g. to do the data processing from one to another).
Maybe the requirement (need more than one DB connection at same time) is rare,  it seems still common in DBA routines.


I copy and modifed slightly from Facade class as FacadeNonStatic class for this cases



------------------ Original ------------------
