### ISSUE TITLE
Issue when the "dispensing" a table with capital letters

### ISSUE THREAD

**Issue by mathematixy** [gabordemooij/redbean#467]
if ( !preg_match( '/^[a-z0-9]+$/', $type ) ) {
			throw new RedException( 'Invalid type: ' . $type );
		}

**Comment by gabordemooij** [comment]
This check prevents all case sensitivity issues from various database platforms, configurations and operating systems from raining down on me. It's a safety net. You have to bypass it yourself. I recommend to only use lower-case characters.

**Comment by mathematixy** [comment]
Unfortunately: This would limit the usability of RedBeanPhp...
