### ISSUE TITLE
as per manual load returns id==0 if nothing found

### ISSUE THREAD

**Issue by nekromoff** [gabordemooij/redbean#469]
however other functions findOne etc. return empty array and this is confusing to the new users.

i think the redbean should be consistent in all queries, excluding only direct SQL queries.

**Comment by gabordemooij** [comment]
R::load() does this on purpose. This technique allows you to reuse the same code for adding and editing entries in the database. R::findOne returns NULL not an array. R::find ALWAYS returns an ARRAY so if it finds nothing it returns an empty one.
