### ISSUE TITLE
not possible to use IN (:parameter) in getAll etc.

### ISSUE THREAD

**Issue by nekromoff** [gabordemooij/redbean#470]
$history=R::getAll('history','xyz IN (:current)',['':current'=>implode(array(12,14,30,54),",")]);

in parameter declaration won't work, neither will just passing an array

**Comment by gabordemooij** [comment]
You need to use R::genSlots(), see: http://www.redbeanphp.com/finding

Also: http://stackoverflow.com/questions/920353/can-i-bind-an-array-to-an-in-condition

**Comment by nekromoff** [comment]
ok, thank you.

**Comment by nekromoff** [comment]
well, actually, it's not working, because documentation does not say how to
combine such a query:
SELECT `history`.* FROM `history` WHERE action IN ('RETURN','FORCERETURN')
AND parameter=:standid AND bikenum IN (:slot2) ORDER BY time DESC LIMIT 1
-- keep-cache
An error occurred: SQLSTATE[HY093]: Invalid parameter number: mixed named
and positional parameters

$action=array('RETURN','FORCERETURN');
         $history=R::find('history','action IN ('.R::genSlots($action).')
AND parameter=:standid AND bikenum IN ('.R::genSlots($currentbikes).')
ORDER BY time DESC LIMIT 1',$action,[':standid'=>$standid],$currentbikes);

**Comment by nekromoff** [comment]
it's possible to replace it by this:
FIND_IN_SET(action,:action) AND parameter=:standid AND
FIND_IN_SET(bikenum,:currentbikes) ORDER BY time DESC LIMIT 1

but supposedly FIND_IN_SET has performance issues

**Comment by gabordemooij** [comment]
You need to flatten the parameter array for use with IN.
