### ISSUE TITLE
Tag version 4.3 release

### ISSUE THREAD

**Issue by nochso** [gabordemooij/redbean#472]
Could you please tag the version 4.3 release? It's available on the website, but I'd rather be able to specify the version via composer.

Recommending to require `dev-master` is *dangerous*. Looking at the Travis build history, there have been failing commits on branch master. Should someone run a `composer update` at the wrong time, that user will be using a broken build of redbean.

Please keep the release tags on Github up to date. If you do, you can change the readme to recommend running a simple `require gabordemooij/redbean` instead. This will look for the latest tagged release instead of accidentally requiring a broken commit.

**Comment by gabordemooij** [comment]
Okay, I added the tag.
In contrast to other projects RedBeanPHP's dev-master is not dangerous at all. Yes, there have been failing builds but RedBeanPHP's test suite is very, very draconic. There have been no major issues for years.
