### ISSUE TITLE
Exception: MYSQL Error 2006 Server has gone away

### ISSUE THREAD

**Issue by neilmillard** [gabordemooij/redbean#474]
I'm using ResquePHP, which means the workers are idle for periods of time.
Should the drivers or DBadapter check the connection with mysql_ping or similar and not assume the connection is still open?

**Comment by gabordemooij** [comment]
MySQL has the ability to automatically reconnect so this is very strange. Have you checked the MySQL manual pages about this issue? There seems to be some configuration issues that might trigger this behavior: https://dev.mysql.com/doc/refman/5.7/en/gone-away.html

**Comment by gabordemooij** [comment]
mysql_ping is deprcated, so I cant use that.

**Comment by neilmillard-msm** [comment]
Does this help?
https://gist.github.com/extraordinaire/4135119

**Comment by vwroad87** [comment]
I dealing with MS  SQL,  that is Microsoft SQL server 2008 R2 so no this
does not address my issue.

thanks,

dp

**Comment by neilmillard** [comment]
As I'm using R:: with resque jobs, it may be the case that the connection isn't available to child fork.
You can also encounter this error with applications that fork child processes, all of which try to use the same connection to the MySQL server. This can be avoided by using a separate connection for each child process.
I might have to catch the Exception, then try again once. As you say the client should reconnect.
Thanks

**Comment by vwroad87** [comment]
Microsoft SQL Server not MySQL.   I didn't say anything.
