### ISSUE TITLE
RedBeanEnterprise  MS SQL Connector

### ISSUE THREAD

**Issue by vwroad87** [gabordemooij/redbean#475]
Hi

I have written RedBeanEnterprise 3 or 4 times asking for assistance/paid support for a MS SQL connector.   I have heard nothing?

**Comment by gabordemooij** [comment]
I'll forward your message to them.

**Comment by gabordemooij** [comment]
Unfortunately they dont seem to care, I've removed them from the website.

**Comment by gabordemooij** [comment]
I'll try to contact one of the developers in my network.
Meanwhile, maybe this can be of some use: http://www.limebean.net/

**Comment by vwroad87** [comment]
Okay anyone else you know that od interested in this work let me know.
Thx

**Comment by gabordemooij** [comment]
Really sorry for their service, very dissapointed.

**Comment by vwroad87** [comment]
You mentioned you were gonna reach out to your developer network to see if you could find someone I could contract to produce this MS SQL (2008+) connector.   Anything?

thanks

**Comment by gabordemooij** [comment]
Sorry no luck yet :(

**Comment by vwroad87** [comment]
Another week and everyone is still booked it seems.   We are still looking for a dev to do this connector to MS SQL.      There was a branch somewhere with an attempt  but I've lost it now, if you can remember where that was I would appreciate the info.

**Comment by skafandri** [comment]
@vwroad87 Still interested in a MS SQL connector?
