### ISSUE TITLE
set PDO::ATTR_EMULATE_PREPARES to true need some time

### ISSUE THREAD

**Issue by server-may-cry** [gabordemooij/redbean#477]
I wish to emulate prepare sql statement. Is there any way to do it?
like this:
```php
$pdo = R::getPDO();
$pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, true);
R::setPDO($pdo);
```
if ping to SQL server is big it can help improve speed

**Comment by tleb** [comment]
```php
class Foo
{
    public $var;
}

class Bar
{
    protected $foo;

    public function setFoo(Foo $foo) {
        $this->foo = $foo;
    
    public function getFoo() {
        return $this->foo;
    }
}

$bar = new Bar;
$bar->setFoo(new Foo);

$foo = $bar->getFoo();
$foo->var = true;

$bar->getFoo()->var; #=> true
```

No need for `R::setPDO($pdo)`.

**Comment by server-may-cry** [comment]
I wish to set [PDO::ATTR_EMULATE_PREPARES](http://php.net/manual/ru/pdo.setattribute.php) to [RedBeanPHP\Driver\RPDO](https://github.com/gabordemooij/redbean/blob/master/RedBeanPHP/Driver/RPDO.php) connection.
It can improve speed of my application. [stackoverflow](http://stackoverflow.com/a/10455228)

**Comment by tleb** [comment]
And this code doesn't work?

    $pdo = R::getPDO();
    $pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, true);

**Comment by gabordemooij** [comment]
http://stackoverflow.com/questions/10113562/pdo-mysql-use-pdoattr-emulate-prepares-or-not

**Comment by server-may-cry** [comment]
Unfortunately there is no static function getPDO or the same
in my example ping between PHP server and PostgreSQL server is about 100ms (severs located in different countries)
for execute
```php
R::find( 'users', 'id = ?', [$userId] );
```
query i need ta wait 100ms to connect to db, 100ms to send prepare query, 100ms to send data on prepared query
then i need to update user last login date
again 100ms prepare update user, 100ms send update user data
summary 200ms lost for prepare query. If query will be prepared on PHP, i will not lose this time.

**Comment by gabordemooij** [comment]
Ah I see. Have you tried this (or am I missing something here?):

    $pdo = R::getDatabaseAdapter()->getDatabase()->getPDO();

**Comment by server-may-cry** [comment]
@gabordemooij sory, no.
that solve my problem.
thank you
```php
$pdo = \R::getDatabaseAdapter()->getDatabase()->getPDO();
$pdo->setAttribute(\PDO::ATTR_EMULATE_PREPARES, true);
\R::getDatabaseAdapter()->getDatabase()->setPDO($pdo);
```
