### ISSUE TITLE
Load method does not work

### ISSUE THREAD

**Issue by AsemKhatib** [gabordemooij/redbean#478]
I'm trying to update one row using Load method , I use Redbean via composer , so I use the namespace Facade I could load or findOne the row but when I want to update it It just add new row with the updated value , If I use getRow in diffrent part of the application it works so it's not a problem of the Facade , could you please help me with that ?

```php
use RedBeanPHP\Facade;

$qid = 1;
$questionUpdate = Facade::load('questions', $qid);
// OR
$questionUpdate = Facade::findOne('questions', 'id = :qid', [':qid' => $qid]);

$questionUpdate->question = $question;
Facade::store($questionUpdate);
```

**Comment by vwroad87** [comment]
I just do this myself, redbean 4.2+ seems to work anyway

$questionUpdate = Facade::findOne('questions', 'id = ?', [$qid]);

**Comment by AsemKhatib** [comment]
I did not pay attention that $qid was null , just saw it when I debug it , it was my mistake both Load and fineOne work just fine , thanks @vwroad87
