### ISSUE TITLE
Foreign keys aren't created for tables named after SQL keyword (mysql backend)

### ISSUE THREAD

**Issue by linger** [gabordemooij/redbean#480]
Trying the next code I observe that a foreign key is not created for table `alarm` pointing to table `constraint`, field `id`:

~~~
require_once __DIR__.'/vendor/autoload.php';

use RedBeanPHP\R;

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

R::setup("mysql:host=localhost;dbname={$_ENV['MYSQL_DATABASE']}", $_ENV['MYSQL_USERNAME'], $_ENV['MYSQL_PASSWORD']);

#
# metrics
#
$metrics = R::dispense('metrics');
$metrics->name = 'diskfree';
$metrics->min = 0.0;
$metrics->max = 0;
$metrics->unit = 'megabyte';
R::store($metrics);

#
# constraint
#
$constraint = R::dispense('constraint');
$constraint->metrics = $metrics;
$constraint->threshold = 1000.0;
$constraint->critical  = 100.0;
R::store($constraint);

#
# record
#
$record = R::dispense('record');
$record->origin  = 'localhost';
$record->time    = time();
$record->metrics = $metrics;
$record->value   = 5320.0;
R::store($record);

#
# alarm
#
$alarm = R::dispense('alarm');
$alarm->constraint  = $constraint;
$alarm->origin      = 'localhost';
R::store($alarm);

R::trash($alarm);
R::trash($record);
~~~

The same happens if I rename bean type `constraint` to `check` or `condition`. I renamed it to `probe` and observed the constraint was then created.

**Comment by vwroad87** [comment]
You are not telling RebBean about any relationships between these beans,
you are just creating beans and storing them?

Please read the section on Relationships in the manual and follow the
examples.

http://redbeanphp.com/index.php?p=/one_to_many

**Comment by linger** [comment]
I know this. I tried also to insert `$constraint->ownAlarmList = [$alarm]`-type expressions but it didn't work.

For other types of beans it works using the same kind of code I wrote before. It works if I rename the `constraint` as `probe`, for example (RedBean identifies the relation from the other side when i wrote `$alarm->probe = $probe`).

**Comment by gabordemooij** [comment]
You need to use xownList but your complaint is correct as well. Fixed the issue. See unit test for the expected behaviour and usage.

**Comment by gabordemooij** [comment]
Thanks for reporting this issue.

**Comment by linger** [comment]
Thanks for your quick response. This is my fist issue opened on github :-)

I prefer not to rely on xownList because I implemented some code on the model hooks and I rely on `after_delete()` for some bean types to find orphaned table records on child tables and delete them with `R::trash()` ensuring execution of all code in the model.

For what I can see `xownList` uses database triggers in order to delete database record bypassing the model logic (logging record deletion).

**Comment by gabordemooij** [comment]
Not triggers, just foreign keys cascades. If you dont use xownList, the foreign keys will be generated as well but you'll have to configure them yourself :/ sorry...

**Comment by gabordemooij** [comment]
BTW, this is totally unrelated but I am so *excited* I just cant hold it to myself. I felt too limited by PHP as a language so I just created my own server-side programming language to replace the entire PHP stack.... I just finished the compiler and it friggin' works!!! http://citrine-lang.org/ sorry, just want to share my excitement!

**Comment by gabordemooij** [comment]
Back on topic: I recommend not to do clean up in the model, the database can do this for you and it's far more reliable (you dont have to write the code, the db folks did, so you cant create bugs :) ).

**Comment by linger** [comment]
Sorry, I mean to say that :-). They are `ON DELETE CASCADE` for `xownList` and `ON DELETE SET NULL` for `ownList`. I use `ownList`s or just take the relation from the other end (many-to-one). Then I use the `delete()` in order to allow or forbid object deletion and `after_delete()` to cleanup orphans.

BTW i'll take a look at your new language. I have always wanted to create my own ;-)

Congrats!!

**Comment by linger** [comment]
I know it's better to rely on the database for this sort of tasks, but I haven't found the way to do this way in my apps for now :-)

OFF TOPIC: reading about your language for some time I'm wondering about an experiment creating my own little language for kids (a sort of Tcl) using dynamic scope! I think it's easier to introduce the scope concept using this strategy (not to mention it's also easier to implement). The few languages I know which use dynamic scope are bash shell, newlisp, most of logo dialects, rebol (I think) and perl (using `local` instead of `my` to declare variables).

Good luck on your adventure, and keep enjoying it :-) 

PD: sorry for bad english.

**Comment by gabordemooij** [comment]
Ok, I understand, it has to be integrated somehow in the domain logic.

OFF TOPIC: Awesome! Please share whenever you have created something..!
