### ISSUE TITLE
Innecessary 'Model::update()' calls?

### ISSUE THREAD

**Issue by linger** [gabordemooij/redbean#481]
Hello.

I'm elaborating on my own model for my app. To test that an object property is not modified after initial storage I define the following methods:

~~~
class Model extends \RedBeanPHP\SimpleModel {        
    function requireUnchanged($property) {
        $bean = $this->bean;

        if ($bean->hasChanged($property)) {
            throw new Exception($bean->getMeta('type').": changing readonly property '$property'");
        }
    }
}

class Something extends Model {
    function update() {
        if ($this->bean->id) {
            # bean is not new
            $this->requireUnchanged('someproperty');
        }
    }
}
~~~

Under some circumstances this code doesn't work as intended, throwing an exception. An `update()` call is being made when no explicit changes are waiting to be synchronized from the bean to the database. This happens for example sometimes on accessing indirect properties like `$aBean->property->otherproperty`. Following this `update()` a SQL 'UPDATE' doesn't execute (the bean really didn't changed).

How can I detect (or avoid) this kinds of `update()` calls? Is this really a bug and this call (`update()` not followed by an SQL statement (INSERT on creation, or UPDATE) should never happen?

Thank you.

**Comment by gabordemooij** [comment]
'Under some circumstances' ? Can you provide a small code example illustrating this scenario?

**Comment by linger** [comment]
I have found this problem under real-world usage. This is a code fragment generating this behabiour:

~~~

$app->post('/api/cron/check/{unit_name}', function($unit_name) use ($app) {

    $unit = R::findOne('unit', 'name = ?', [$unit_name]);

    foreach (R::find('watchdog', 'unit_id = ?', [$unit->id]) as $watchdog) {

        $time = $watchdog->computeTimeout();
        $metrics = $watchdog->metrics;
        $domain  = $watchdog->domain;

        $timeouts = [];

        foreach ($domain->sharedOriginList as $origin) {
            if (empty(R::find('record', 'metrics_id = ? AND origin_id = ? AND time >= ?', [$metrics->id, $origin->id, $time]))) {
                if (empty(R::find('timeout', 'watchdog_id = ? AND origin_id = ?', [$watchdog->id, $origin->id]))) {
                    $timeout = R::dispense('timeout');
                    $timeout->watchdog = $watchdog;
                    $timeout->origin   = $origin;

                    $timeouts[] = $timeout;
                }
            }
        }
        R::storeAll($timeouts);
        return count($timeouts);
    }
});

~~~

In the `Model` class, which all my models inherit from, I define an `after_update()` function like this:

~~~
function after_update() {
        $bean = $this->bean;
        error_log($bean->getMeta('type')."({$bean->id}): ".json_encode($bean->export()));
}
~~~

And the above code (a Silex HTTP request handler) generates the following output:

~~~
domain(1): {"id":"1","pattern":"*","regex":"[a-z0-9-]+([.][a-z0-9-]+)*","priority":"1"}
watchdog(1): {"id":"1","value":"5","metrics_id":"1","domain_id":"1","unit_id":"4"}
timeout(2): {"id":"2","watchdog_id":"1","origin_id":"2"}
timeout(3): {"id":"3","watchdog_id":"1","origin_id":"1"}
~~~

I could append the bootstrap code generating the data model or the app code as a whoole if you need it (I would like to publish the app here on github but for now I feel my code quality is not good enough and also the few code comments are in spanish).

Sorry for not being able to provide a more concise example.

**Comment by gabordemooij** [comment]
I will investigate this issue...

**Comment by gabordemooij** [comment]
I think know what you mean.


    $b = R::dispense('book');
    $b->ownPage[] = R::dispense('page');
    R::store($b);
    $p = R::findOne('page');
    var_dump($p->hasChanged('book'));
    $p->book; //accessing it will mark as changed
    var_dump($p->hasChanged('book'));

The reason why RedBeanPHP marks the property as changed it because it compares the property with its contents at load-time. This behaviour has also been documented in the API.
You could solve this issue by testing whether this property existed in the first place (using isset).

**Comment by linger** [comment]
Thanks! This is just how I solved it:

~~~

class Model extends \RedBeanPHP\SimpleModel {

    # ...
    
    function have($property) {
        return isset($this->bean[$property]) || isset($this->bean[$property.'_id']);
    }
    
    function requireUnchanged($property) {
        $bean = $this->bean;

        if ($bean->have($property) && $bean->old($property) != null && $bean->hasChanged($property)) {
            throw new Exception($this->getType().": changing readonly property '$property'");
        }
    }
    
    function after_update() {
        $bean = $this->bean;
        error_log($bean->getMeta('type')."({$bean->id}): ".json_encode($bean->export()));
    }
}

~~~

And then, for example:

~~~

class Metrics extends Model {

    # ...
    
    function validate() {
        # ...
    }

    function update() {
        $bean = $this->bean;
        
        if ($bean->id) {
            # we check that "write-once" fields have not changed
            $bean->requireUnchanged('name');
            $bean->requireUnchanged('unit');
        }

        $bean->validate();
    }
}

~~~

I suppose this is also related with other question I have been investigating. When I check a bean that I have just imported for the presence of a value in a property named after other bean (I think it's called a link property) I need to do the workaround exposed in `Model::have()` function above. When I tried before, using `isset()`, it fails. The following is a figured example:

    # we are updating a product info from an HTML form...
    #
    # NOTE: $_POST is like ["id" => "1", "catalog_id" => "1", "description" => "My first product", ...]
    
    $product = R::dispense('product')->import($_POST);
    
Later, when calling `Product::validate()` from `Product::update()` to validate the changes
    
    if (! isset($product->catalog)) {
        # FIXME: this could fail even if `$product->catalog` would return a valid object
        throw new Exception("Product needs to be in a catalog");
    }

    # NOTE: yes, I know would be better to left this checks to the database, but my real example
    #       is a bit more complex and has more bussiness logic inside it :-)
    
The correct test in this case would be `! isset($product['catalog'] && ! isset($product['catalog_id'])` which is what I do in the above `Model::have()` function.

Then, could I assume this is expected behaviour?

Going back to the original question, now the problem that remains unsolved for me is how I can detect when an `update()` call is not to be followed by an SQL `INSERT` or `UPDATE` statement, or an `after_update()` is not preceded by one, so the logging code at `Model::after_update()` reflects the real changes made on the database.

Thanks, very much.
