### ISSUE TITLE
How to check if a bean will perform a insert or a update ?

### ISSUE THREAD

**Issue by kainxspirits** [gabordemooij/redbean#484]
I made a model with 'fused' methods in which I do some check to validate my bean before calling the store function.
Though, I didn't find any method allowing to check if the actual query will be a INSERT or UPDATE. 

That's not really an issue when dispening a new bean. But when using the findOrCreate method, if a bean has been found I would like to skip some part of the validation process.

Is there a way to retrieve this information ? (I searched through the doc, but couldn't find something related to this) If that's not the case that would be a good idea to implement a new method that indicates if the bean is completly new or if it comes from database.

**Comment by gabordemooij** [comment]
A bean will be inserted when the id = 0.

    if (!$bean->id) //it's going to INSERT

Please dont file questions as bugs, it will take longer for your question to be answered and it's annoying, use the forum instead: https://groups.google.com/forum/?fromgroups#!forum/redbeanorm
