### ISSUE TITLE
Postgres boolean datatype

### ISSUE THREAD

**Issue by wilzoka** [gabordemooij/redbean#485]
Hey, i create a field with boolean datatype in postgres, when im load it using R::Load() then store without change the boolean value, i get a exception with invalid boolean datatype.

When var_dump the bean i got the boolean field like this: 'boolfield':false
and to work the R::Store i need to change to: $bean->boolfield = 0
so i can store.
do you'll fix it?

**Comment by gabordemooij** [comment]
You need to explicitly cast booleans in Postgres, I cant change that, it's the way Postgres works.
