### ISSUE TITLE
Release v4.3.1 not published on packagist

### ISSUE THREAD

**Issue by rikvdh** [gabordemooij/redbean#487]
Hi,

For some reason v4.3 is, but v4.3.1 isn't.
Is there a reason for this?
Can this be fixed?

Greetings,

Rik

**Comment by gabordemooij** [comment]
Solved, sorry I forget to click the update button on packagist all the time, why cant they do this automatically? strange...

**Comment by tleb** [comment]
Settings > Webhooks & services > Add service > packagist.

**Comment by gabordemooij** [comment]
I did all that, long ago, but for some reason it simply doesnt work and I dont know why.

**Comment by tleb** [comment]
It's either the token which is not valid anymore or the domain which is not marked as https.
