### ISSUE TITLE
Download url gives access denied

### ISSUE THREAD

**Issue by necenzurat** [gabordemooij/redbean#489]
```
http://www.redbeanphp.com/downloadredbean.php
```
Gives Access Denied :cry:

**Comment by gabordemooij** [comment]
where did you find that link? 
on the download page, the download link should work: http://www.redbeanphp.com/index.php?p=/download

http://www.redbeanphp.com/RedBeanPHP4_3_1.tar.gz


I removed the 'in-between' PHP script.

**Comment by necenzurat** [comment]
I had it for my redbeanphp composer hack.
Can you make a php script that has the latest version? Would be nice.

On Sunday, February 7, 2016, Gabor de Mooij <notifications@github.com>
wrote:

> where did you find that link?
> on the download page, the download link should work:
> http://www.redbeanphp.com/index.php?p=/download
>
> http://www.redbeanphp.com/RedBeanPHP4_3_1.tar.gz
>
> I removed the 'in-between' PHP script.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gabordemooij/redbean/issues/489#issuecomment-180879504>
> .
>


-- 

--
*Costin Moise* aka necenzurat

Tel: *+4 0726.459.188* | Github <https://github.com/necenzurat> | Linkedin
<http://www.linkedin.com/in/necenzurat>

**Comment by gabordemooij** [comment]
fixed

**Comment by necenzurat** [comment]
thank you!
