### ISSUE TITLE
R::setup with $tunnel

### ISSUE THREAD

**Issue by y4nnick** [gabordemooij/redbean#490]
Would be nice if R::setup would take an ssh2_tunnel parameter to connect with a database over an ssh tunnel.

For example:
```
    $connection = ssh2_connect('123.123.13.1', 22);
    ssh2_auth_password($connection, 'user', 'pass');
    $tunnel = ssh2_tunnel($connection, '127.0.0.1', 3306);
    R::setup("mysql:host=127.0.0.1;dbname=name","root","rootpass",$tunnel);
```

**Comment by y4nnick** [comment]
For example:
```
    $connection = ssh2_connect('123.123.13.1', 22);
    ssh2_auth_password($connection, 'user', 'pass');
    $tunnel = ssh2_tunnel($connection, '127.0.0.1', 3306);
    R::setup("mysql:host=127.0.0.1;dbname=name","root","rootpass",$tunnel);
```

**Comment by gabordemooij** [comment]
I think this should be a plugin or something, not something for the core as this is a very exceptional scenario.

**Comment by y4nnick** [comment]
Is this possible, since PHP PDO doesn't support ssh tunnels?  If you could give me a hint how i could implement it, i would write an plugin.

**Comment by gabordemooij** [comment]
I have never seen it. I fear you'll have to create your own PDO-compatible object (connect using sockets) and pass it to RedBeanPHP (setup accepts PDO objects). Lot of work...
