### ISSUE TITLE
PDO Exception not clear

### ISSUE THREAD

**Issue by flip111** [gabordemooij/redbean#491]
https://github.com/gabordemooij/redbean/blob/feb86ccd5612856519d76befcd7aac9c98a28538/RedBeanPHP/Driver/RPDO.php#L314

This hides the original exception and doesn't give you much info.

Original exception: Uncaught PDOException: could not find driver
RedbeanPHP exception: Uncaught PDOException: Could not connect to database (?)

**Comment by gabordemooij** [comment]
The original exception includes your password.

**Comment by flip111** [comment]
Maybe parse the original message?

**Comment by gabordemooij** [comment]
No, that sounds like a lot of code to accomplish very little.
