### ISSUE TITLE
ConvertToBean

### ISSUE THREAD

**Issue by flip111** [gabordemooij/redbean#493]
Could a `ConvertToBean` method be added, which takes a single row, such as the one returned from `R::getRow()`.

**Comment by gabordemooij** [comment]
convertToBeans already exists:
http://www.redbeanphp.com/index.php?p=/querying

**Comment by flip111** [comment]
yes the plural version already exist, can we add a method for singular?

**Comment by gabordemooij** [comment]
Yes of course, I'll flag this conversation as a reminder.

**Comment by gabordemooij** [comment]
implemented in master
