### ISSUE TITLE
about table name

### ISSUE THREAD

**Issue by sunmenghua** [gabordemooij/redbean#495]
I have a double about table name. 

http://www.redbeanphp.com/index.php?p=/crud
```
$page = R::dispense('page'); //valid

$page = R::dispense( 'Page' ); //invalid: uppercase
$page = R::dispense( 'cms_page' ); //invalid: _
$page = R::dispense( '@#!' ); //invalid
```

http://www.redbeanphp.com/index.php?p=/fluid_and_frozen
```
R::freeze( ['book','page','book_page'] );
```

How do I dispense a new bean object with type 'book_page'?

**Comment by gabordemooij** [comment]
Those beans get dispensed whenever you use a sharedList: $book->sharedTag will generate book_tag beans in the background, that's why you should not dispense them yourself.

**Comment by sunmenghua** [comment]
You are right. 
Thank you for your reply.

**Comment by sunmenghua** [comment]
I have other question about relation load.
```
$products = R::findAll('product');
foreach ($products as $product) {
    // load shop
    $product->shop;
}
```
In this way, n+1 sql ran.
Do you have any suggestions? Like Eloquent's Lazy Eager Loading.

**Comment by gabordemooij** [comment]
Why not use a good old SQL query here ? If it's for a list in a view, I recommend to use plain SQL. Otherwise take a look at findMulti()  http://www.redbeanphp.com/index.php?p=/finding
