### ISSUE TITLE
Counting

### ISSUE THREAD

**Issue by andrewtheone** [gabordemooij/redbean#496]
Hey, im trying to count the rows... but somehow it just returns '1' however debug tells me its 4

SELECT COUNT(*) FROM `newsitem` where site in ('both', 'prod') AND ( (title like ?) ) GROUP BY slug -- keep-cache
Array ( [0] => %a% ) 
resultset: 4 rows

and the result of R::count is 1..

**Comment by gabordemooij** [comment]
Can you please provide a concrete snippet of code that demonstrates this issue? Which I can run in CLI mode?
