### ISSUE TITLE
Debugging page broken link (website)

### ISSUE THREAD

**Issue by Filisko** [gabordemooij/redbean#497]
Hi, I just found a broken link at the end of the [debugging page](http://www.redbeanphp.com/index.php?p=/debugging).

![img](https://cloud.githubusercontent.com/assets/8798694/14403775/39dab8ac-fe64-11e5-94a4-9bdfddb667bc.PNG)

"Learn about [relations](http://www.redbeanphp.com/one-to-many) in RedBeanPHP." relations points to  an unexistent one-to-many page instead of pointing to the good one http://www.redbeanphp.com/one-to-many.

Just a little mistake.

**Comment by gabordemooij** [comment]
fixed, thanks for reporting!
