### ISSUE TITLE
Alternative syntax

### ISSUE THREAD

**Issue by Harvie** [gabordemooij/redbean#499]
Hello,
i have some suggestions about redbean syntax.

Currently it's invoked like this:

```
$product = R::dispense('product');
$product->price = 50;
R::store($product);
R::trash($product);  
```

But i think it would make more sense to be invoked like this:

```
$product = new RedBean('product');
$product->price = 50;
$product->store();
$product->trash();
```

Loading can be done like this:

```
$product = new RedBean('product')->load($id);
//or this: (both should work)
$product = new RedBean('product');
$product->load($id);
```
I believe that both of these can be implemented concurently, so user can choose whatever he likes more. I personally prefer the second one much more. It should be very simple to implement. Like few lines of code. Thanks.

**Comment by r3wt** [comment]
Curious to know how much you have examined the Redbean codebase. Its > 10k LOC, IIRC, and its spread out across many classes in order to properly seperate concerns. `R` is just a Facade, and by that its just a convenient wrapper over the top of these various components. I see no reason this should be supported by the library its self, but you could implement it yourself relatively easy.

**Comment by Harvie** [comment]
I din't examined redbeans codebase in depth, but your example just proves me right, that this can be implemented in few lines of code.

Reason i use framework is to write less code, not to implement new API. Because of that i would like to see this implemented in RedBean itself. So i don't have to implement it over and over again in every project. If redbean has 10k LOC, i don't see how adding these 20 lines could do harm.

It would just make things look more elegant like real "ActiveRecord" without need for calling any external static method or etc... Except for eg. freezing model and other stuff that affects more than one class.

**Comment by Filisko** [comment]
In my opinion, I see it useless. You could just do something like what @r3wt did.

**Comment by Harvie** [comment]
Well. I can also use SQL directly... But that's not why i use frameworks.

**Comment by Orrico** [comment]
As you said, it's just a matter of preference and not an improvement in the performance or usability, even a framework issue. So you should follow the suggestion and create your own pattern, if it pleases you more.

**Comment by filisko** [comment]
t RedBeanPHP is not just a simple ORM framework, it has a different point of view about some things, and some of it main priorities is to keep things simple, and that is why people like it.

And lol, RedBean is probably the most flexible ORM out there, and you already have a solution about how to do what you wanted to do.

I think that this issue could be closed.

**Comment by Harvie** [comment]
I am not suggesting to make something more complicated, i am just suggesting to keep stuff simple, but use (or at least optionaly offer) proper/cleaner syntax.

**Comment by wanjochan** [comment]
@Harvie   Official team may seldom encouter the case about "connect 2 or above db at same time.  What I did to solve your case is to copy Facade into FacadeNonStatic and do some search and replace...  It's painful, especially need to do that patch once a new version of RB release.... but anyway, I do wish official team consider to patch it in the future...

**Comment by Orrico** [comment]
@r3wt, I implemented your model like this:
```
abstract class Database {
    protected $pdo;
    protected $bean;
    protected $type;

    public function __construct($db, $type) {
        $this->type = $type;
        $this->bean = \R::dispense($type);

        /** optional use of PDO */
        $this->pdo = $db;
    }

    public function __get($k) {
        return isset($this->bean->{$k}) ? $this->bean->{$k} : null;
    }

    public function __set($k,$v) {
        $this->bean->{$k} = $v;
    }

    public function findAll($limit=100, $order='id DESC') {
        return \R::findAll($this->type, 'ORDER BY ' . $order . ' LIMIT ' . $limit);
    }

    public function store() {
        return \R::store($this->bean);
    }

    public function delete() {
        return \R::trash($this->bean);
    }

    /** Used for development only */
    public function reset() {
        return \R::wipe($this->type);
    }
}
```

but when i try to use _load_ or _findOne_ methods throw a error because i shouldn't use PHP variables in my query in this cases:
```
public function findOne($val, $field='id') {
    $bindings[] = $val;
    return \R::findOne($type, $field . ' = ?', $bindings);
}

public function load($id) {
    return \R::load($type, $id);
}
```

what would be the best solution?

**Comment by SusanthCom** [comment]
I ❤️ the simplicity of using R:: 

RedBean Quick Tour >>http://redbeanphp.com/index.php?p=/quick_tour
Copy Paste:

**Quick Tour in 5 minutes**
RedBeanPHP focuses on the developer,... you!
It does not focus primarily on performance, **object orientedness, correctness or proper design**.
No, RedBeanPHP's purpose is to boost your productivity.
As such, RedBeanPHP is not just an ORM, it's also a development tool.

RedBean FAQ >> http://redbeanphp.com/index.php?p=/about
Copy Paste:

**Why do you use so much static functions? What about coupling?**

That's only the Facade. Behind the facade you will find a landscape of elegant classes, see the API for advanced usage/more information. The API closely resembles the interface of the facade class.

**Is it wrong to use the static facade functions?**

If you're not planning to swap frameworks regularly you can rely on the easy-to-use static facade functions like R::dispense() and R::load() etc. People often complain about static methods but in reality many of those so-called pure OOP style projects tend to become heaps of powerless miniature objects and countless wirings. I don't believe that works very well.
