### ISSUE TITLE
why redbean error not working in try catch if there is any error like duplicate key 

### ISSUE THREAD

**Issue by saurabhaec** [gabordemooij/redbean#502]
why redbean error not working in try catch if there is any error like duplicate key

**Comment by filisko** [comment]
Hi @saurabhaec,
Could you put an example of how you're doing it? It should throw a **RedBeanPHP\RedException\SQL** exception.

So, if user "saurabhaec" would be already stored in the database and it's unique, the next code would make RedBeanPHP throw an exception and catch it.
```php
try {
    R::exec("INSERT INTO `user` ( `saurabhaec`");
} catch (RedBeanPHP\RedException\SQL $e) {
    echo $e->getMessage();
}
```

**Comment by saurabhaec** [comment]
try {
   $autologin = R::dispense('autologin');
  $autologin->macid = $macid->id;
  $autologin->userid = $userid->uid;
  R::store($autologin);

} catch (Exception $e) {
    echo $e->getMessage();
}

**Comment by filisko** [comment]
If there would a be duplicate key, it would throw an SQL error, are you sure that it is not being inserted successfully in the database? are you sure that your unique keys are ok? as I told you before, you should check first if there are any duplicates by yourself with a SELECT, and in case there are not any duplicates, insert/update (whatever you want to do).

**Comment by gabordemooij** [comment]
Closed because of lack of activity.
