### ISSUE TITLE
R::dispense( 'table_name' ) throw RedBeanPHP\RedException: Invalid type: table_name

### ISSUE THREAD

**Issue by vkill** [gabordemooij/redbean#508]
The test script like this.

```php
<?php

/*
redbean 4.3.2
php 7.0.8
*/

require __DIR__ . '/vendor/autoload.php';

use RedBeanPHP\R;

R::setup( "mysql:dbname=db_name", 'root' );

R::dispense( 'table_name' );

/*
PHP Fatal error:  Uncaught RedBeanPHP\RedException: Invalid type: table_name in /path/vendor/gabordemooij/redbean/RedBeanPHP/Util/DispenseHelper.php:60
Stack trace:
#0 /path/vendor/gabordemooij/redbean/RedBeanPHP/Facade.php(559): RedBeanPHP\Util\DispenseHelper::dispense(Object(RedBeanPHP\OODB), 'table_name', 1, false)
#1 /path/x.php(9): RedBeanPHP\Facade::dispense('table_name')
#2 {main}
  thrown in /path/vendor/gabordemooij/redbean/RedBeanPHP/Util/DispenseHelper.php on line 60
*/

R::getRedBean()->dispense( 'table_name' );
// nothing wrong with it


```

**Comment by SusanthCom** [comment]
Table name must not have '_' by convention.
Please Read : http://redbeanphp.com/index.php?p=/prefixes

**Comment by vkill** [comment]
oh, @SusanthCom  thanks :)

**Comment by codeg8** [comment]
Gives me error on :  

Invalid type: accessToken

is camelCasing also not allowed ?

**Comment by igorPopryduhin** [comment]
Why not use the underscore character?
👀

**Comment by Ashokverma** [comment]
Having the same error Fatal error:  Uncaught TypeError: RedBeanPHP\Util\DispenseHelper::dispense(): Argument #1 ($oodb) must be of type RedBeanPHP\OODB, null given, called in /Applications/XAMPP/xamppfiles/htdocs/rapidadmin/rb-mysql.php on line 12859 and defined in /Applications/XAMPP/xamppfiles/htdocs/rapidadmin/rb-mysql.php:16057
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/rapidadmin/rb-mysql.php(12859): RedBeanPHP\Util\DispenseHelper::dispense(NULL, 'book', 1, false)
#1 /Applications/XAMPP/xamppfiles/htdocs/rapidadmin/index.php(21): RedBeanPHP\Facade::dispense('book')
#2 {main}
  thrown in /Applications/XAMPP/xamppfiles/htdocs/rapidadmin/rb-mysql.php on line 16057
