### ISSUE TITLE
Search suggestion for web site

### ISSUE THREAD

**Issue by SusanthCom** [gabordemooij/redbean#509]
Hi,

suggestion to improve the site http://redbeanphp.com/ by adding search.

I wish, if there was a search facility like [found here](http://www.slimframework.com/docs/) provided by [Algolia](https://www.algolia.com/ref/docsearch/)

Current website  http://redbeanphp.com/ is clean and well documented !
RedbeanPHP is an Amazing work !!! Keep rocking @gabordemooij ❤️❤️

Thank You

**Comment by SusanthCom** [comment]
Since this suggestion is of low priority; and googling like this  [site:redbeanphp.com nuke](https://www.google.com/search?q=site:redbeanphp.com+nuke) works fine, Am closing this :)

**Comment by mnrahimi** [comment]
Hi, Susanth,

**It is a good suggestion please open it back**, I was going to open this issue, but when did a quick search within all the issues I found it and thought it will be closed by other reason by the project members.

**I also saw your reason for closing this issue** but I think that is not enough user experience.

**Comment by SusanthCom** [comment]
@mnrafg  Done :)

**Comment by gabordemooij** [comment]
Thank you for the compliments but I have very little time - sorry :(
