### ISSUE TITLE
Improved table naming scheme

### ISSUE THREAD

**Issue by SusanthCom** [gabordemooij/redbean#510]
Hi,

Currently ReadBean defaults, reserves `_` to represent _many to many_ mapping and don't allow `_` to be used in table names.

Though this limitation could be bypassed [by following this](http://redbeanphp.com/index.php?p=/prefixes)

An improved default naming scheme would be : 
- Allow **`_`** in table naming
  
  > now `student_skill`, `teacher_skill`, `support_staff_skill` ... become valid default names
- Use **`___`** as a default  to represent _many to many_ mapping. ( 3 underscore is more readable; even 2 will do ). 
  
  >  now `client_user`,  `system_user`, `technical_skill` represent tables
  > where as `client_user___technical_skill` and `system_user___technical_skill` represents _many to many_ mapping.

Hai @gabordemooij and team members, my humble opinion is that, making this suggested behaviour as default by keeping backward compatibility, makes ReadBean more beautiful ( especially for early ReadBean adopters ).

Hats off to ❤️RedBeanPHP❤️ team, for your wonderful work !!!

Those who support this view, please up vote 👍 to let the team know how important it is 😄 

Thnak you all
Susanth

**Comment by surikat** [comment]
+1

**Comment by SusanthCom** [comment]
@surikat through you, I reached RedBean Inspired [DataMap](http://redcatphp.com/datamap-orm), which is  part of [RedCat](https://github.com/redcatphp/datamap). Thank You 😸

**Comment by gabordemooij** [comment]
Thanks SusanthCom for your comment. I know the naming scheme is a bit controversial. However many database already use the single underscore for linking tables. In my experience it's always possible to avoid using the '_' for regular tables, it just takes a little more imagination sometimes to come up with a good name for the bean.

**Comment by SusanthCom** [comment]
Hi @gabordemooij,

Thank you Very much for fast response.

I respect your view wholeheartedly and love ❤️RedBeanPHP❤️.
Will try creative mode, for single word naming OR will follow [the alternative provided by you](http://redbeanphp.com/index.php?p=/prefixes)

But from an ORM user's perspective, One can see, many of leading open source projects are using `_` in table names extensively.
* [wordpress db structure](https://codex.wordpress.org/Database_Description) **Graphics**
* [drupal db structure](https://www.drupal.org/node/2360815) **Graphics**
* [joomla db structure](https://docs.joomla.org/J1.5:Database_structure)
* [pagekit db structure](https://www.ostraining.com/blog/general/pagekit/)
* and Many more ...

If you still opt to stick to the current implementation as default. **Thats fine** 👍 
From the clean source code, documentation and [RoadMap](http://redbeanphp.com/index.php?p=/roadmap) its clear that you and team invested much time and effort in coding and **filtering out** the user requests.
Hats off 🎩🎩 

At lease a flag based implementation, roughly, something like below, **will be a big help !!!**
> **R::fancyTableName( boolean $toggle = TRUE  )**
> Turns on the `fancyTableName` mode.
> In `fancyTableName` mode:
> * `_` is allowed in table names.
> * `___` is used in table names when mapping many to many relations.

Advantages of Implementation :
* Users of RedBeanPHP can trigger the suggested scheme **in just one line** !!! 
* No more `constant` definition or `R::renameAssociation()` calls !
* No more `R::xdispense()` just do it in one way, always : `R::dispense()` !
* More **freedom** in Table Naming scheme !
* Better readability of database schema ( for those who love that way )
* Wide range of users will feel, very comfortable to use RedBeanPHP
* More **Productive** and **Happy** 😄😄  users
* More Users get attracted to ❤️RedBeanPHP❤️

ThankYou
Susanth

**Comment by SusanthCom** [comment]
Hi @gabordemooij,

Thank you Very much for fast response.

I respect your view wholeheartedly and love ❤️RedBeanPHP❤️.
Will try creative mode, for single word naming OR will follow [the alternative provided by you](http://redbeanphp.com/index.php?p=/prefixes)

But from an ORM user's perspective, One can see, many of leading open source projects are using `_` in table names extensively.
* [wordpress db structure](https://codex.wordpress.org/Database_Description) **Graphics**
* [drupal db structure](https://www.drupal.org/node/2360815) **Graphics**
* [joomla db structure](https://docs.joomla.org/J1.5:Database_structure)
* [pagekit db structure](https://www.ostraining.com/blog/general/pagekit/)
* and Many more ...

If you still opt to stick to the current implementation as default. **Thats fine** 👍 
From the clean source code, documentation and [RoadMap](http://redbeanphp.com/index.php?p=/roadmap) its clear that you and team invested much time and effort in coding and **filtering out** the user requests.
Hats off 🎩🎩 

At lease a flag based implementation, roughly, something like below, **will be a big help !!!**
> R::setup( string $dsn = NULL, string $username = NULL, string $password = NULL, boolean $frozen = FALSE, **string $fancyTableName = FALSE**  )
> if `$fancyTableName` is TRUE.
> * `_` is allowed in table names.
> * `___` is used in table names when mapping many to many relations.

Advantages of Implementation :
* Users of RedBeanPHP can trigger the suggested scheme **during setup itself** !!! 
* No more `constant` definition or `R::renameAssociation()` calls !
* No more `R::xdispense()` just do it in one way, always : `R::dispense()` !
* More **freedom** in Table Naming scheme !
* Better readability of database schema ( for those who love that way )
* Wide range of users will feel, very comfortable to use RedBeanPHP
* More **Productive** and **Happy** 😄😄  users
* More Users get attracted to ❤️RedBeanPHP❤️

ThankYou
Susanth
