### ISSUE TITLE
Partial Freeze: Columns  

### ISSUE THREAD

**Issue by trentramseyer** [gabordemooij/redbean#513]
I like the partial freeze by table however, I would like to have the ability to freeze columns in a table. Or some option to Only Add New Columns but do not Alter Old 

Quite often we add a new variable to a bean and that alters the previous ones we already modified properly. I also don't want to send string to a number field and have it alter on accident or widen ( i want it to leave truncated)

**Comment by gabordemooij** [comment]
You can control this from within your model. Are you familiar with SimpleModel ? It's an ad-hoc model you can connect to a bean which gives you the opportunity to validate the bean before it gets send to the database.
