### ISSUE TITLE
SQLSTATE[01000]: Warning: 1265 Data truncated for column

### ISSUE THREAD

**Issue by nekromoff** [gabordemooij/redbean#516]
`UPDATE stands SET standDescription='xyydysyd', serviceTag=0, latitude='', longitude='' WHERE id='3'`

An error occurred: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'latitude' at row 1

Is it possible to set IGNORE flag, so constraints such as this one (empty string) are not enforced?

**Comment by gabordemooij** [comment]
You mean that these exceptions are caught in fluid mode ?

**Comment by gabordemooij** [comment]
Is this happening in fluid or frozen mode ?

**Comment by nekromoff** [comment]
frozen

**Comment by gabordemooij** [comment]
I suppose you just have to widen the column manually then
