### ISSUE TITLE
findOrDispense() is not properly documented

### ISSUE THREAD

**Issue by John5** [gabordemooij/redbean#522]
I want to get a single bean. First I was using findOrCreate(), but that stores the bean right away, which returns a single bean. I then replaced it with findOrDispense(). The documentation says "if no beans are found, it dispenses a bean of that type.", but omits the fact that the bean is wrapped in an array. It is a bit strange that these two methods have completely different return values.

Having a convenience method like findOneOrDispense() would be useful in this case.

**Comment by gabordemooij** [comment]
Fixed comments, these will generate correct API docs when next version is released.

**Comment by bpruneau** [comment]
This method raise a notice:
"Only variables should be passed by reference"
It refers to the use of reset() function.
I propose to replace...
```
return reset( self::findOrDispense( $type, $sql, $bindings ) );
```
with:
```
$arrayOfBeans = self::findOrDispense( $type, $sql, $bindings );
return reset($arrayOfBeans);
```
