### ISSUE TITLE
Meta Data: hasChanged

### ISSUE THREAD

**Issue by sah-comp** [gabordemooij/redbean#523]
The following hasChanged() will not give TRUE in RedBean 3.5, even if the column type is varchar. I didn't check newer versions though.

```php
$bean = R::dispense( 'post' );
$bean->value = '01';
R::store( $bean );
$bean->value = '1';
if ( $bean->hasChanged( 'value' ) {
  // do something
}
```

**Comment by gabordemooij** [comment]
The following code displays 'changed!' over here:

    $bean = R::dispense( 'post' );
    $bean->value = '01';
    R::store( $bean );
    $bean->value = '1';
    if ( $bean->hasChanged( 'value' )) die('changed!');

using RedBeanPHP 3.5.13 (latest of 3.5 series)

**Comment by sah-comp** [comment]
I will investigate further into my code surrounding this fragment. I'm using R::graph() to convert a POST form to a bean and then call R::store() while the hasChanged happens in Model::update().

```php
public function update()
{
    if ( $this->bean->buyer !== $this->bean->old('buyer') ) {
        // this works for me in the meantime
    }
}
```

**Comment by sah-comp** [comment]
As I didn't find out why hasChanged() failed on me and because RB 3.5 has reached EOL this month, I close this issue and will happily hop on Version 4 of Redbean.
