### ISSUE TITLE
Guidelines to add a new DB Support

### ISSUE THREAD

**Issue by nocodelab** [gabordemooij/redbean#524]
Hello folks!
I would like to integrate SAP HANA in RedBean.
SAP Hana can be already used in PHP with its ODBC driver.

Is there anyone that can guide me on how to integrate this DB in RedBean? I really love this ORM and I would like to continue using it also in projects where I'm forced (sigh!) to use the SAP platform.

Thanks in advance!

**Comment by gabordemooij** [comment]
Hi,

Unfortunately I have no tutorial for you. But adding support for a new DB in RedBeanPHP generally means you have to code a new QueryWriter, look in the folder QueryWriter for examples, i.e. Postgres, CUBRID, MySQL etc... 

All QueryWriters have to implement the QueryWriter Interface.
That's basically all there is to it.

If you have any questions feel free to ask.

cheers
Gabor
