### ISSUE TITLE
findOrCreate string viewed as int

### ISSUE THREAD

**Issue by stijnboa** [gabordemooij/redbean#525]
`$m = \R::findOrCreate('category', ['code' => (string)$me->menuid]);`

// the value of $me->menuid => '00000'

results in query:
`SELECT `category`.*  FROM `category`  WHERE ( `code` IN ( 00000 )  )`

Which returns all rows where a string is filled in (searches for integer 0)

To fix this the resulting query should be (quotes):

`SELECT `category`.*  FROM `category`  WHERE ( `code` IN ( '00000' )  )`

Redbean version 4.3

**Comment by gabordemooij** [comment]
Thank you for reporting this issue.
I will look into this.

**Comment by stijnboa** [comment]
Thanks!
