### ISSUE TITLE
Problem with multiple insert 

### ISSUE THREAD

**Issue by saurabhaec** [gabordemooij/redbean#526]
i have code like 

$nofoextramac = count($config_rule['data']);
if ($nofoextramac) {
        $policiesmapper = R::dispense('policiesmapper', $nofoextramac);
         for ($i = 0; $i < $nofoextramac; $i++) {
              $policiesmapper[$i]->mac = $config_rule['data'][$i]['mac'];
                    $policiesmapper[$i]->pid = $policy_no;
              }
                R::storeAll($policiesmapper);
}

$config_rule['data'] have only one record and $policy_no is int number  then getting error msg 
when $config_rule['data']  have multiple items then its work fine.
ERROR : "OODB Store requires a bean, got: integer"

What is problem with given code.

**Comment by gabordemooij** [comment]
hard to say, can you post a var_dump of $policiesmapper ?

**Comment by saurabhaec** [comment]
object(RedBeanPHP\OODBBean)#54 (10) {
  ["properties":protected]=>
  array(1) {
    ["id"]=>
    int(0)
  }
  ["__info":protected]=>
  array(5) {
    ["type"]=>
    string(14) "policiesmapper"
    ["sys.id"]=>
    string(2) "id"
    ["sys.orig"]=>
    array(1) {
      ["id"]=>
      int(0)
    }
    ["tainted"]=>
    bool(true)
    ["changed"]=>
    bool(true)
  }
  ["beanHelper":protected]=>
  object(RedBeanPHP\BeanHelper\SimpleFacadeBeanHelper)#47 (0) {
  }
  ["fetchType":protected]=>
  NULL
  ["withSql":protected]=>
  string(0) ""
  ["withParams":protected]=>
  array(0) {
  }
  ["aliasName":protected]=>
  NULL
  ["via":protected]=>
  NULL
  ["noLoad":protected]=>
  bool(false)
  ["all":protected]=>
  bool(false)
}
