### ISSUE TITLE
Feature: generate update SQL for only properties that have changed

### ISSUE THREAD

**Issue by malhal** [gabordemooij/redbean#529]
This is strange to me because I've used RedBean for a long time and never noticed this. When I find a bean, set a property and store it, it generates an SQL update for all properties not just the one that was changed. I'd like to propose a feature to only update the changed columns mostly for performance reasons but also for safety. e.g. I've been using the new JSON columns and found although the data is successfully stored in the database, the update fails to set it again after it was read out by the find.

**Comment by gabordemooij** [comment]
Certainly interesting, thank you for reporting this.

Why does the JSON column fail ? What kind of error message does it produce ?
I presume this is a Postgres database ?

As for the update procedure, I don't see anything wrong with it, I think it's actually more safe than the alternative. Even if you don't change a value you might want to let it 'remain the same' because it is somehow related to the other properties of the bean. If you only update the ones you've changed you have to keep track of those subtle differences. Now, it's just like a file: you overwrite the contents but in a cohesive manner allowing no room for inconsistent records. Please correct me if I'm wrong.

**Comment by malhal** [comment]
It failed because of an invalid control character \u001f and only on the update not on the insert. However my workaround involved replacing that character on the insert so to allow the future updates which is setting all columns again to work. You'll see the char after "Multi beat mode" at line 109, col 894 in the JSON at this link: https://itunes.apple.com/lookup?bundleId=com.ssworks.DrBetotteTC 
The update not working was not specific to RedBean as if editing the field with Sequel Pro that failed to update the column while that char was still present.

		$json = json_encode($value, JSON_FORCE_OBJECT);
		// remove the control code that MySQL can't handle
		$fixedJson = preg_replace('/\\\\u001f/', '', $json);
		$app->json = $fixedJson;
		R::store($app);

This is with MySQL 5.7.16

I think transactions give you all the safety you need in the situation you describe. 

However it seems I jumped the gun when mentioning performance problems as I did some quick research and it seems if the new data matches the current in the column then MySQL doesn't write it again. "If you set a column to the value it currently has, MySQL notices this and does not update it.": http://dev.mysql.com/doc/refman/5.7/en/update.html
No info on what the performance of this checking is tho, e.g. for large BLOBs or JSON I'd imagine the algorithm has an impact.

I think if this was to be implemented it's simply an improvement to "tainted" to be per property rather than per bean, and then the update query only includes columns that exist in the tainted array.

**Comment by gabordemooij** [comment]
Unfortunately I have very little time right now, since I started my own company. So I wont have time for new features.

**Comment by gabordemooij** [comment]
Seems like I finally getting some time after all, I will look into this asap.

**Comment by malhal** [comment]
Cool, I suppose you could keep an array of the properties that have been set, and then only include those in the update command. Probably no need to check for equality.

**Comment by gabordemooij** [comment]
I created a fix for #547 maybe this issue might benefit as well.
