### ISSUE TITLE
 'Invalid type: userData'

### ISSUE THREAD

**Issue by flik** [gabordemooij/redbean#539]
require 'rb.php';

R::setup( 'mysql:host=localhost;dbname=mysite', 'root', 'xxxxx' );

$post = R::dispense( 'userData' );
$post->title = 'My holiday';
$id = R::store( $post );
echo $id; 

[Mon Jan 30 07:51:31.374662 2017] [:error] [pid 4962] [client 127.0.0.1:48082] PHP Fatal error:  Uncaught exception 'RedBeanPHP\\RedException' with message 'Invalid type: userData' in /home/flikx/Documents/up/blueprint-cms-n/api2/cv/rb.php:12667\nStack trace:\n#0 /home/flikx/Documents/up/blueprint-cms-n/api2/cv/rb.php(10715): RedBeanPHP\\Util\\DispenseHelper::dispense(Object(RedBeanPHP\\OODB), 'userData', 1, false)\n#1 /home/flikx/Documents/up/blueprint-cms-n/api2/cv/index.php(8): RedBeanPHP\\Facade::dispense('userData')\n#2 {main}\n  thrown in /home/flikx/Documents/up/blueprint-cms-n/api2/cv/rb.php on line 12667

**Comment by r3wt** [comment]
@flik Redbean does not support camelcase or snakecase naming conventions for tables. you can override this behavior as follows:

```php
R::ext('xdispense', function( $type ){ 
        return R::getRedBean()->dispense( $type ); //disable schema naming rules check by dispensing the type anyway.
});
```
In general this is not advisable, but if you wish to do it here is some more info:
http://www.redbeanphp.com/index.php?p=/prefixes
