### ISSUE TITLE
exportAll takes much more time than foreach with $item->export()

### ISSUE THREAD

**Issue by aleroma** [gabordemooij/redbean#541]
Situation:
in db there is an email list table with columns `id`, `email` and `date`

this code takes 1 min 40 sec:
$email_list = R::findAll('email');
$email_array = R::exportAll($email_list, TRUE);
var_dump($email_array);

but this takes only 1 sec:
$email_list = R::findAll('email');
foreach ($email_list as $item) {
    var_dump($item->export());
}

Is this a bug?

**Comment by gabordemooij** [comment]
This might have something to do with selecting 'export parents' options (2nd param). Yes this can be slow. Is this a bug? Probably not, exportAll can be slow if used with large collections. Consider using findMulti, batching or just a plain query.

**Comment by marios88** [comment]
Just run into this issue. Definitely not a bug and works as intended producing the correct results, but takes a long time with a large dataset.  
Can confirm this happens when `parents = true`

My suggestion would be to add your answer to the OP as a note in the manual
> exportAll can be slow if used with large collections. Consider using findMulti, batching or just a plain query

**Comment by Lynesth** [comment]
@marios88 @gabordemooij I made another issue on this matter so that we can keep this one closed :)
Please see #702
