### ISSUE TITLE
Damaged data!

### ISSUE THREAD

**Issue by Priler** [gabordemooij/redbean#542]
Hi.
I've got awful problem with RedBean PHP.
It's damages data from database.

Here is normal mysqli_query() result:
![mysqli_query()](http://storage6.static.itmages.com/i/17/0210/h_1486735424_3664035_1a2a9f56b7.png)

Here is what RB result with the same query:
![RedBean](http://storage5.static.itmages.com/i/17/0210/h_1486735578_9578601_0beafd1959.png)

The question is: "WTF?"
Where did RB lost this field value?

**Comment by Priler** [comment]
I've tested it with raw PDO code, and it's cuts data off.
Don't know why yet, but it's definitely not RB issue.

**Comment by vwroad87** [comment]
Never use underscorce field names, RB uses underscore names for its link
fields.

**Comment by Priler** [comment]
@vwroad I know.
