### ISSUE TITLE
SQLite via RedBean has no foreign key support. R::trash() with xownAnythingList don't work.

### ISSUE THREAD

**Issue by hausl** [gabordemooij/redbean#545]
In **SQLite** the _xownAnythingList_ with the _DELETE CASCADE_ beyond is only working, if the foreign key suppport within SQLite is enabled. This is currently not the case if RedBeanPHP connects the **SQLite** Database.

This is quite stupid, because the child items will always remain in the database and invalid FK. exists. If i delete the parent entry id 1 the childs still remain with parent_id 1, but this exists not anymore.

So i suggest to run automaticly on connect the following SQL-statment in SQLite, to activate the foreign key support within **SQLite** DB.

`PRAGMA foreign_keys = ON;`

I found this by doing a lot of debugging and research to the web an now make the R::setup as followed:

```
R::setup('sqlite:dbfile.sqlite');
R::exec('PRAGMA foreign_keys = ON');
```

Now the _DELETE CASCADE_ works fine, as it should. But at first i had absolutly no idea what went wrong.

See also here:

> 2.  Enabling Foreign Key Support 
> ...
> `sqlite> PRAGMA foreign_keys = ON;`
> ...
> **Foreign key constraints are disabled by default (for backwards compatibility),** so must be enabled separately for each database connection. (Note, however, that future releases of SQLite might change so that foreign key constraints enabled by default. Careful developers will not make any assumptions about whether or not foreign keys are enabled by default but will instead enable or disable them as necessary.) 

https://www.sqlite.org/foreignkeys.html

Greets

**Comment by r3wt** [comment]
@hausl This is very helpful work, but i should inform you that @gabordemooij is very busy at the moment. We hear from him every month or so. So if you would like to see something fixed, it would be best to submit a PR and wait for him to show up again. be sure and mention this issue in your PR so it can be linked.

**Comment by filisko** [comment]
Wow, that's a good catch @hausl

**Comment by hausl** [comment]
Well, i can make an PR, but im not sure where ists correct to place the adding code.

Maybes here, in the constructor of RPDO, after the Line 238?
https://github.com/gabordemooij/redbean/blob/a5f8c0966cac313d2a1db10726eb04a2cef71952/RedBeanPHP/Driver/RPDO.php#L238-L239

**Comment by hausl** [comment]
`, it would be best to submit a PR and wait for him to show up again. be sure and mention this issue in your PR so it can be linked.`

I'll check that.

**Comment by hausl** [comment]
https://github.com/gabordemooij/redbean/pull/548

**Comment by gabordemooij** [comment]
Thanks for your PR.
I will have more time for RedBeanPHP again very soon, so you can expect more activity on my part again.

Strange thing with this issue... it seems not all SQLite distributions are affected. Over here, I ran a simple test with a fresh SQLite installation:


```

R::setup();
$book = R::dispense('book');
$page = R::dispense('page');
$book->title = 'mijn boek';
$page->number = 1;
$book->xownPageList[] = $page;
R::store($book);
echo R::count('page');
echo "\n";
R::trash( $book );
echo R::count('page');
echo "\n";
exit;
```

and it outputs:

```
1
0
```

but then I discovered SQLite was actually not installed at all... ? I could not find the SQLite3 command on the CLI. So I installed SQLite3 using apt-get and guess what... it breaks :/


```
1
1
```
So I added the requested pragma to the setup. I implemented it a bit different, hope you dont mind, feel free to discuss.

**Comment by hausl** [comment]
Thank you. Of course i dont mind your way to implement ;)
