### ISSUE TITLE
R::findOneOrDispense (and maybe others) skips type validation

### ISSUE THREAD

**Issue by josejulio** [gabordemooij/redbean#546]
```php
R::dispense('buy_from');
```
Will throw `'RedBeanPHP\RedException' with message 'Invalid type: buy_from'`

While
```php
R::findOneOrDispense('buy_from', 'key = :key', array('key' => 'disable_type_checking'));
```
Doesn't throw any exception and creates the table buy_from.

While `_` isn't officially supported, it works on my sharedList by using this hidden feature.
e.g.
```php
$item->sharedBuyFromList[] = $buyFrom;
```

Is there any reason that `_` isn't officially supported? I don't recall reading about it on the site.

**Comment by hausl** [comment]
> Is there any reason that  _  isn't officially supported? I don't recall reading about it on the site.

See here:

> `  $page = R::dispense( 'cms_page' ); //invalid: _`
http://www.redbeanphp.com/index.php?p=/crud -> "Conventions"

> `In RedBeanPHP, the underscore '_' is used to denote a relation between two tables. `
http://www.redbeanphp.com/index.php?p=/prefixes -> "Prefixes"

**Comment by josejulio** [comment]
I don't know how i missed that part, thank you!

**Comment by hausl** [comment]
> `R::findOneOrDispense('buy_from', 'key = :key', array('key' => 'disable_type_checking'));`
> Doesn't throw any exception and creates the table buy_from.

@gabordemooij, isn't this a bug?

**Comment by gabordemooij** [comment]
Okay, sorry my fault, I will look into this.

**Comment by gabordemooij** [comment]
This issue has been fixed in the master branch.
