### ISSUE TITLE
offsetExists not implemented the same as offsetGet

### ISSUE THREAD

**Issue by dominics** [gabordemooij/redbean#549]
Imagine you have a simple `Post` object, which has a `person_id` and is supposed to be associated to a `Person`.

```php
$post = R::findOne('post');

$a = $post->person ?? null;
$b = $post->person;
$c = $post->person ?? null;

var_dump($a ? 'Person A is named ' . $a->name : 'No person A');
var_dump($b ? 'Person B is named ' . $b->name : 'No person B');
var_dump($c ? 'Person C is named ' . $c->name : 'No person C');
```

I would expect to either have the person's name in the output three times, or 'No person' in the output three times. What actually happens is that $a is `null`, so the first access fails, but the other two succeed.

I'm guessing this happens because the implementation of `offsetExists` doesn't agree with `offsetGet` around relations. If that's as designed then it should be noted prominently: it certainly seems surprising that the existence of an offset is determined by whether it has been accessed yet (rather than whether is has been set yet).

**Comment by gabordemooij** [comment]
This is by design, but I'll take another look at it. Thanks for brining this up.
Maybe we need to extend the docs here.

**Comment by gabordemooij** [comment]
Yes this is by design, it's because the person bean gets loaded when it's necessary. Because this operation is quite heavy it's postponed until the last moment.
So, to check if a person has been asscociated you do:

`$post->person === null;

However, this might need some improvement.
We could extend the __isset function to check for related beans as well. Good idea.

**Comment by gabordemooij** [comment]
I tried to fix this issue but it seems this might break compatibility.
So I opted to offer another check:

`$post->exists('person')`

this will do exactly what you want, i.e. check the person_id and not load the entire person bean.

**Comment by dominics** [comment]
:+1: Thanks!
