### ISSUE TITLE
Legacy versiosn download

### ISSUE THREAD

**Issue by KSVQ** [gabordemooij/redbean#550]
Hi there! 

I absolutely love your ORM :) and I have a major issue. I need to download the version of redbean that works with php 5.2. I don't have the option to have the server upgraded to 5.3 or higher. It is outside my control unfortunately and I really hate the idea of writing my own prepared statements.

Where ever I look, I can't find any of the older versions of RB? Can you please point me in the right direction? I know older versions are no longer supported and I am ok with that. I just need it to work on PHP 5.2.

Do you have a repository with legacy versions? Could I somehow get my hands of PHP 5.2 compatible version.

I really hope you can help.

Thanks!

**Comment by gabordemooij** [comment]
Hi, version 3.5 is still available:

http://www.redbeanphp.com/index.php?p=/download

PHP 5.2 (2006) is a bit problematic though, some PDO features are missing.
Make sure you also run the P533 patch.

Please keep me informed in case of problems, happy to help. I try to make RedBeanPHP available for as much PHP versions as possible, including legacy ones!

**Comment by gabordemooij** [comment]
You can also take a version from the archive (but to be honest I'm not sure thats wise, these are very old):

http://www.redbeanphp.com/downloads/index.php

**Comment by KSVQ** [comment]
Awesome, I took this one from the archive RedBeanPHP3_5beta9.tar.gz. For now it works okay. I don't have overly complicated requirements luckily. It is an old university server that they don't want to upgrade because a lot of old apps are built on 5.2.

I've seen this patch page before. Are you saying that applying a patch to a NEW version should make RB compatible with older version of PHP or applying the patch to version 3.5?

Thanks! :)

**Comment by gabordemooij** [comment]
Sorry for my late reply, very busy over here.. but also working on next RedBeanPHP version ;)
The patch fixes an issue with RB and PHP < 5.3.3, so if you apply the patch to a new RedBeanPHP version it will be compatible with PHP 5.3 - PHP 5.3.3 as well. It's also required for PHP 5.2 and earlier but the patch will not be enough, there are some features lacking concerning PDO in PHP 5.2. However maybe you dont need those at all.
