### ISSUE TITLE
Packagist outdated

### ISSUE THREAD

**Issue by noplanman** [gabordemooij/redbean#551]
Hi, I've noticed that [Packagist](https://packagist.org/packages/gabordemooij/redbean) is still on 4.3.3.

Mind updating so that we get all the new fixes?

Thank you! :tada:

**Comment by aleroma** [comment]
Subscribe!

**Comment by gabordemooij** [comment]
ok done

sorry I never use composer or packagist I'm an old fashioned guy if it comes to packaging systems.
