### ISSUE TITLE
installation - no rb.php

### ISSUE THREAD

**Issue by dlaugh14** [gabordemooij/redbean#552]
Hi, 

I really enjoy using redbean. I have a set up right now where we are using this, but for some reason I was told to try to get a php package from github. Here I followed the instructions and went over to the http://www.redbeanphp.com/index.php?p=/install website. There it states that there should be a rb.php file to include. Even in the rb-p533.php file it is trying to open that. Where is this file and what is it that I am misunderstanding. Sorry if it's something stupid! Thanks

**Comment by gabordemooij** [comment]
The rb.php file contains the entire RedBeanPHP codebase in one file. It can be downloaded from the site: http://www.redbeanphp.com/index.php?p=/download, you can also build it yourself using replica.php. You dont need to use the all-in-one file version though, it's just for convenience.
