### ISSUE TITLE
Setting a time zone?

### ISSUE THREAD

**Issue by KSVQ** [gabordemooij/redbean#553]
When using R::isoDateTime(), is there a way to set a time zone.

On my dev machine (Windows) the time I get is off by 6 hours whereas on the host machine (Linux) I do get the correct time.

**Comment by filisko** [comment]
Perhaps you could use PHP's function **[date_default_timezone_set](http://php.net/manual/en/function.date-default-timezone-set.php)**.

**Comment by KSVQ** [comment]
I'll try that. It's a good suggestion. Thanks.

I am still curious as to whether the RB function can handle this though.

**Comment by gabordemooij** [comment]
RedbeanPHP just uses the date() function with a time() call. It's only for the basic needs.
