### ISSUE TITLE
Facade::findOneOrDispense(): Only variables should be passed by reference

### ISSUE THREAD

**Issue by dominics** [gabordemooij/redbean#554]
`Facade::findOneOrDispense()` is implemented with the following:

```php
[...]
return reset( self::findOrDispense( $type, $sql, $bindings ) );
```

But [`reset(&$array)`](http://php.net/manual/en/function.reset.php) expects to be passed its parameter _by reference_  (as do the other functions that modify/use the internal array pointer, like `next()`, `current()` or `key()`). So this code produces an `E_NOTICE`-level error:

```
Notice: Only variables should be passed by reference
```

(I note that before PHP7 this was only an `E_STRICT`, so maybe people didn't notice/had their strict errors disabled.)

**Comment by gabordemooij** [comment]
thanks
