### ISSUE TITLE
[Feature] Support for CockroachDB

### ISSUE THREAD

**Issue by mayel** [gabordemooij/redbean#555]
I wonder if there's any interest in testing and officially adding support for [CockroachDB](https://www.cockroachlabs.com/product/cockroachdb-core/)?

**Comment by gabordemooij** [comment]
Interesting project, I would welcome a plugin for this!

**Comment by eubyte** [comment]
So, are there any plans to add CockroachDB support? I hoped it would be added in v5.1. Thank you!
