### ISSUE TITLE
TimeData collector with PHPDebugBar?

### ISSUE THREAD

**Issue by wolfheart** [gabordemooij/redbean#556]
I want to **add timedata information to be displayed** via PHPDebugBar. I'm using https://github.com/Filisko/debugbar-redbean right now.

Setting `R::debug(true, 3);` only shows the SQL statements in the PHPDebugBars tab _Database_, but not in the tab _Timeline_, where I wanted the information too.

Then I was playing with the API http://phpdebugbar.com/docs/base-collectors.html#timedata . But the only solution I could find was to modify `Facade::query()` to the following snippet (kind of pseudo code). I couldn't modify it via extending the class due to the functions `private` flag.

Is there **any more elegant solution** to this **without modifying** `Facade.php`? Maybe some kind of hook? Otherwise I would have to fork Redbean?

```php
private static function query( $method, $sql, $bindings )
{
	$debugbar['time']->startMeasure(__METHOD__, $sql); // <<< START
	if ( !self::$redbean->isFrozen() ) {
		try {
			$rs = Facade::$adapter->$method( $sql, $bindings );
		} catch ( SQLException $exception ) {
			if ( self::$writer->sqlStateIn( $exception->getSQLState(),
				array(
					QueryWriter::C_SQLSTATE_NO_SUCH_COLUMN,
					QueryWriter::C_SQLSTATE_NO_SUCH_TABLE )
				)
			) {
				$debugbar['time']->stopMeasure(__METHOD__); // <<< STOP
				return ( $method === 'getCell' ) ? NULL : array();
			} else {
				$debugbar['time']->stopMeasure(__METHOD__); // <<< STOP
				throw $exception;
			}
		}
		$debugbar['time']->stopMeasure(__METHOD__); // <<< STOP
		return $rs;
	} else {
		$debugbar['time']->stopMeasure(__METHOD__); // <<< STOP
		return Facade::$adapter->$method( $sql, $bindings );
	}
}
```

Thanks, Michael

**Comment by gabordemooij** [comment]
So, to be clear the feature request to add hooks to the query method for performance monitoring?

**Comment by wolfheart** [comment]
Yes! 👍

**Comment by gabordemooij** [comment]
I have looked at your issue but to me it seems simpler to just override the Adapter?
That way, you don't need any hooks in the facade (which seems the wrong place anyway, because the facade is supposed to have the least amount of task specific code):

```
$oldToolbox =  R::getToolbox();
$writer = $oldToolbox->getWriter();
$oodb   = $oldToolbox->getRedBean();
$adapter = $oldToolbox->getDatabaseAdapter();

class PerformanceAdapter extends \RedBeanPHP\Adapter\DBAdapter {
        public function getCell( $query, $bindings = [] ) {
                die('measuring performance...');
        }
}

$database = $adapter->getDatabase();
$newAdapter = new PerformanceAdapter( $database );
$toolbox =  new \RedBeanPHP\Toolbox( $oodb, $newAdapter, $writer );
R::configureFacadeWithToolbox( $toolbox );
R::getCell( 'select * from books' );
```

This little test seems to work over here.
I think this might solve your problem? If you need any further assistance feel free to ask.

**Comment by wolfheart** [comment]
Ok, I'll have a look at that. But most of the times I use `R::getAll()/exec()`

Do I have to overwrite each of `DBAdapter::get()/getAssoc()/exec()` then?

**Comment by gabordemooij** [comment]
My example was just that... an example ;)

Yes you have to wrap every method but in the end that's just a couple of copy-pastes.
It's more elegant than building it right into the facade and having every call for everyone check and invoke that hook.

**Comment by wolfheart** [comment]
Thank you! It worked fine! 👍
