### ISSUE TITLE
one to many relationship - error: "Cannot redeclare class.."

### ISSUE THREAD

**Issue by michau85** [gabordemooij/redbean#557]
Hello,
I have a problem with creation one to many relationship. I'm trying to reconstruct tutorial's example. I receive an error: 'Fatal error: Cannot redeclare class Model_Category' . Please help me. Below my controller code:
     
     $c = R::dispense('category');
     $c->name = 'Antiques';
     $vase = R::dispense('product');
     $vase->price = 25;
     $c->ownProductList[] = $vase;
      R::store($c);

and Mode_category code:

    class Model_Category extends RedBean_SimpleModel {
                
    }

Orginal tutorial example is working good. Thanks in advance.

**Comment by gabordemooij** [comment]
Looks like a bug in your autoloader

Op 11 jun. 2017 10:26 a.m. schreef "michau85" <notifications@github.com>:

**Comment by gabordemooij** [comment]
Did you solve this issue already?
If you need help we need more details, it is probably an issue with the class that loads your models. Have you tried basic PHP require statements?

**Comment by gabordemooij** [comment]
For questions the forum is usually a better place: https://groups.google.com/forum/?fromgroups#!forum/redbeanorm

**Comment by michau85** [comment]
You're right. I tried require_once and evrything works! Thanks.!

**Comment by r3wt** [comment]
@gabor perhaps its time to make a troubleshooting faq page and a link to it in tge readme. If you think that would help, let me know how i may be of service in making that happen

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gabordemooij** [comment]
I was thinking along the same lines, this question turns up frequently, feel free to create a first draft if you like.
