### ISSUE TITLE
Hiding Attributes From Serialization

### ISSUE THREAD

**Issue by alzalabany** [gabordemooij/redbean#558]
is there any way to automaticly hide a property on Serialization ?

example on user bean, i dont want to return password property when i fetch users.

may be something like setting $hidden on Model can be done like its done on Eloquent ?
```

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = ['password'];
    /**
     * The attributes that should be visible in arrays.
     *
     * @var array
     */
    protected $visible = ['first_name', 'last_name'];
}
```

**Comment by gabordemooij** [comment]
No, but you can use native PHP array_filter to filter the entry out of the array. Use export() to create a native array representation of a bean.

**Comment by gabordemooij** [comment]
For questions the forum is usually a better place: https://groups.google.com/forum/?fromgroups#!forum/redbeanorm
