### ISSUE TITLE
Redbean integration with Codeigniter 3 as a library

### ISSUE THREAD

**Issue by marios88** [gabordemooij/redbean#560]
Could not find a ready made library for CI 3 so here it is!

save rb.php to
`application/third_pary/rb.php`

save Rb.php (code below) to 
`application/libraries/Rb.php`

You can now load redbean as a library in CI, allowing use as R:: everywhere you want

```
<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
class Rb {
    protected $CI;
    function __construct() {
        // Include database configuration
        $this->CI =& get_instance();

        require_once APPPATH.'third_party/rb.php';
        // Database data
        $this->CI->load->database();
        if(!R::testConnection()){
            R::setup("mysql:host=".$this->CI->db->hostname.";dbname=".$this->CI->db->database,$this->CI->db->username,$this->CI->db->password);
            if(ENVIRONMENT === 'development'){
                R::debug( TRUE, 3 );
            }
        }
    } //end __contruct()
} //end Rb
```

**Comment by gabordemooij** [comment]
Very nice! thank you!

**Comment by gabordemooij** [comment]
Would you mind creating a plugin or something for this?  I would like to point visitors to this script so they can use it.

**Comment by adrianmak** [comment]
As far as I knew readbeanphp, tables are created dynamically.
How readbeanphp to interact CI model ?
any example code ?
