### ISSUE TITLE
How rb.php is generated?

### ISSUE THREAD

**Issue by jairocgr** [gabordemooij/redbean#565]
Hi,

I would like to know how rb.php is generated? Wich tool/library is used to pack the whole RedBeans library into a single php file?

I need do develop a php library that must be distribuited without composer, and i like this "one file, whole library" approach.

thanks,

**Comment by daviddeutsch** [comment]
http://www.redbeanphp.com/index.php?p=/replica

https://github.com/gabordemooij/redbean/blob/master/replica2.php
