### ISSUE TITLE
question

### ISSUE THREAD

**Issue by SaphiLC** [gabordemooij/redbean#566]
I know this is not the place to ask stuff but for some reason whenever i post in the google "forum", it doesnt get published. im new to redbean, i want to get x table from the database with all its relations, for example, i want to get all the books from the database and i want to know in what store is each book, how can i do that? im not used to redbean terms :(

thanks :)

also, why dont you guys open a gitter.im channel? :)

**Comment by benmajor** [comment]
It might be worth reading through the useful online documentation, as this is all covered over there, specifically in these sections:

[Finding](https://redbeanphp.com/index.php?p=/finding)
[Many-to-Many Relationships](https://redbeanphp.com/index.php?p=/many_to_many)

**Comment by SaphiLC** [comment]
thanks, i already read all the documentation before making the question, instead of being cryptic you could simply say what to use since as i said, im not used at all with the weird terms this ORM uses and the examples are not very clear at all and dont cover all usages, for example, in this case i want to get a business, that business have a city id, that city id have a region id, that business also have a shop id and that shop id also have products inside, thats not explained in the docs and the docs only cover 1 example and thats it, so its not really useful. Not hating or anything, i like redbean, but its annoying to learn thanks to the weird names and the not so useful documentation :S
The workaround i made was this
`
$query = $this->db::findAll('business', 'ORDER BY name ASC LIMIT 10');
foreach($query as $data)
{
	$business				= new \stdClass();
	$business->id			= $data->id;
	$business->photo		= $data->photo;
	$business->activity		= $data->activity->name;
	$business->name			= $data->name;
	if($data->city->name !==  $data->city->region->name)
	{
		$business->location	= $data->city->name . ', ' . $data->city->region->name . ', ' . $data->city->region->state->name;
	}else{
		$business->location	= $data->city->region->name . ', ' . $data->city->region->state->name;
	}
	$business->url			= $this->app->get('BASE') . '/negocio/' .
		\Web::instance()->slug($data->city->region->name) . '/' .
		\Web::instance()->slug($data->activity->name) . '/' .
		\Web::instance()->slug($data->name) . '/' .
		'ubicacion/' . $data->id;

	$array_business[]		= $business; // this array will be looped to show the businness in the view
}
`
but i doubt thats an efficient way of solving the issue

**Comment by benmajor** [comment]
I'm sorry, and not to sound obtuse or anything, but these terminologies are not unique to RedBean and they're quite simple to learn once you break them down. 

When you mention the business having a city ID and region ID, that's a [many-to-one relationship](http://redbeanphp.com/index.php?p=/many_to_one). I assume only one business can own a shop? If so, why is it a separate bean anyway? The shop > product model is a [one-to-many relationship](http://redbeanphp.com/index.php?p=/one_to_many).

**Comment by SaphiLC** [comment]
yah, my bad, forgot i changed that, user owning the businnes(one user can own many business), city and activity are the only relations
