### ISSUE TITLE
RedBeanPHP: how to add timestamp, unique default?

### ISSUE THREAD

**Issue by elieobeid7** [gabordemooij/redbean#567]
I'm using the latest stable version, if I have to update for version 5, let me know.

    $user = R::dispense('user');
    $user->fname = 'man';
    $user->lname = '00';
    $user->setMeta("buildcommand.unique" , array($user->email='e@e.com'));
    $user->pass = password_hash('password', PASSWORD_DEFAULT);

    $user->gender=0; // I want this to have a default value of 0 if I don't insert anything
    $user->verified=1;
    $user->lastModified = date('Y-m-d G:i:s'); // I want this to be a timestamp, right now it's stored as datetime
    $id= R::store($user);

`lastModified` is stored as datetime. I want `gender` and `verified` to have a default value of 0. I want `email` to be unique.

I tried every solution I could find on stackoverflow and nothing works

    $user->setMeta("buildcommand.unique" , array(array('email')));

**Comment by Lynesth** [comment]
Hello,

Regarding the defaults, it is not possible. You have to check beforehand and modify the value accordingly.

Regarding the unique index, you can do this :
```php
$user = R::dispense('user');
$user->setMeta('sys.uniques', array('email')); /* can be removed afterwards */
$user->fname = 'Bob';
$user->lname = 'Sponge';
$user->email = 'bs@deepinthe.sea';
R::store($user);
?>
```
This way, the **email** field will be unique in your database. This does not mean that RedBean will check it for you when you create a new user, as it will simply raise a database exception.

You could also simply set the unique index directly in your database manager (like phpmyadmin).

Lyn.
