### ISSUE TITLE
Preference for class_alias vs use?

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#568]
Is there a specific reason the Readme suggests the use of `class_alias()` when installing RB via Composer, as opposed to the `use` statement? For example, the following works just as well:

    use \RedBeanPHP\R as R;

As far as I can tell, there is no requirement for back-scoping of `R` in this instance.

**Comment by gabordemooij** [comment]
I have no idea, I do not actively maintain Composer packages, I only focus on the tarballs. Do you recommend a change?

**Comment by benmajor** [comment]
Well it may be largely academic for a lot of projects, but using `use-as` may have some advantages, especially when a project requires its own namespace.

**Comment by gabordemooij** [comment]
Feel free to send a pull request for the README, I'm looking forward to it ;)
To be honest I never use Composer.

**Comment by benmajor** [comment]
Please see https://github.com/gabordemooij/redbean/pull/571
