### ISSUE TITLE
Make the filter function in Look optionnal

### ISSUE THREAD

**Issue by Lynesth** [gabordemooij/redbean#569]
Hey there,

Could you please change the look function code in a way we can set the $filter parameter to NULL or FALSE (or even an empty string) if we don't need any function ?

I guess that just means changing line 66 of Look.php as follow :
```php
if (!empty($filter)) {
    $values[] = call_user_func_array( $filter, array( $row[$key] ) );
} else {
    $values[] = $row[$key];
}
```

Thank you very much for RedBean ;)

Lyn.

**Comment by gabordemooij** [comment]
sure, I'll look into this
