### ISSUE TITLE
Change sorting of one-to-many

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#570]
By default, the `ownChildList` property of a bean in RedBean is sorted by the `id` of `Child`. What is the recommended method to change the sorting of related beans? For example, consider the following example:

```
$clothing = R::load('clothing', 1);

$size58 = R::dispense('size');
$size58->sku = 3;
$size58->size = '58cm';

$size59 = R::dispense('size');
$size59->sku = 2;
$size59->size = '59cm';

$clothing->ownSizeList[] = $size58;
$clothing->ownSizeList[] = $size59;
```

By default, since `$size58` has a lower ID, it will appear before `$size59` when accessing `$clothing->ownSizeList`. However, I would like to sort `ownSizeList` based on the `sku` property of the `size` bean. What's the recommendation?

**Comment by gabordemooij** [comment]
Use an SQL snippet on retrieval like this:
`
$sortedSizes = $clothing->with(' ORDER BY size DESC ')->ownSizeList;
`

**Comment by benmajor** [comment]
Perfect, thank you!
