### ISSUE TITLE
trashAll specific xownList then store new xownBean

### ISSUE THREAD

**Issue by Lynesth** [gabordemooij/redbean#573]
Hey there,

This isn't easy to explain so I'll post some code :

```php
$toDelete = $_user->withCondition(' status != 2 ')->xownCommandeList;
R::trashAll($toDelete);

$new = R::dispense("commande");
$new->user = $_user;
$new->status = 0;

R::store($new);
```

If I do something like this, all previously trashed beans (loaded in $toDelete) are stored again when calling R::store(). If I want to prevent that from happening (which, obviously, is the case), I have to do :

 ```php
$toDelete = $_user->withCondition(' status != 2 ')->xownCommandeList;
R::trashAll($toDelete);

/* This reloads the user bean and prevents the "issue" */
$_user = $_user->fresh();

$new = R::dispense("commande");
$new->user = $_user;
$new->status = 0;

R::store($new);
```

Is it the way to do it or am I missing something ?

Thanks,

Lyn.

**Comment by jreklund** [comment]
Haven't tested this example before. But you still got the deleted ones stored inside $_user, that you never reset/refresh. Therefor it's stored ones again. See if this one helps.

```php
R::trashAll( $_user->withCondition(' status != 2 ')->xownCommandeList );
```

**Comment by gabordemooij** [comment]
try this:


```

$toDelete = $_user->withCondition(' status != 2 ')->xownCommandeList;
$_user->xownCommandeList = [];

$new = R::dispense("commande");
$new->user = $_user;
$new->status = 0;
R::store($new);

```

**Comment by Lynesth** [comment]
@gabordemooij 

What if I then (after the "deleting") need to do stuff with all the user's other commandes ?
```php
$toDelete = $_user->withCondition(' status != 2 ')->xownCommandeList;
$_user->xownCommandeList = [];

/* I first need to store the user */
R::store($_user);

/* Before I can call */
$_user->all()->xownCommandeList;
/* otherwise it would also reload the ones we just got rid of */
```
This makes some unnecessary calls to the database doesn't it ? Much like my first proposal of trashing then refreshing the user.

So currently I need to first load all the user's xownCommandeList and then remove from the array only the ones I need to trash:
```php
$_user->xownCommandeList;

// Decide to remove all commandes that have a status != 2
foreach ($_user->xownCommandeList as $k => $c) {
    if ($c->status != 2) {
        unset($_user->xownCommandeList[$k]);
    }
}

/*
//Or we could also do it this way, but it obviously goes against the efficiency we're after:
$toDelete = R::find("commande", " user_id = ? AND status != 2 ", [ $_user->id ]);
foreach ($toDelete as $k => $c) {
    unset($_user->xownCommandeList[$k]);
}
*/

foreach ($_user->xownCommandeList as $k => $c) {
    /* Do what I need to do with the remaining ones */
}
```

I guess we could also simply reload all the commandes we need by "reversing" the withCondition, but I don't know, this doesn't seem right either way. Would it be possible to add something like the *tainted* property, for *deleted* elements ? Or maybe a trashAndRemoveFromCurrentlyLoadedLinkedBeans function ?

Let me know what you think, maybe I'm just overthinking it, I don't know really.

Lyn.

**Comment by gabordemooij** [comment]
I think the first solution, looping over the command list and unsetting all that have status != 2 is the most elegant solution. The alternatives feel a bit contrived..
