### ISSUE TITLE
How can I store binary data into a column?

### ISSUE THREAD

**Issue by krisives** [gabordemooij/redbean#583]
I tried searching for information I found an old post from 2010 where it's mentioned RedBean doesn't support binary data / BLOB types. I tried to search for "blob" on GitHub and for some reason it gave me tons of results that did not contain the word "blob" because of how URLs work in Github.

Thank you for your time!

**Comment by gabordemooij** [comment]
Hi there,

Tiny binary blobs can be base64 encoded and stored as regular text. For big blobs use the file system. Technically you could store big binary blobs in the DB, but most of the time this causes scaling issues as there is no server-database bridge to leverage the caching power of web servers with big blobs.

cheers
Gabor

**Comment by krisives** [comment]
Thanks. I only ask because it's not clear and RedBean changes over time!

Just curious will RedBean try to add an index to this column?

Normally I would use the file system but we have many servers and want to aggregate and present this data to the end user. In specific they are small JPEG screenshots. I understand that I will have to add a script that can locally cache the data and put HTTP headers to make that work.
