### ISSUE TITLE
Trim comments in production release

### ISSUE THREAD

**Issue by SusanthCom** [gabordemooij/redbean#585]
Hi,

How about trimming the all the comments in production release; 
but still keeping human readable php code ?

This should reduce the final library size near to 50% !!

Slim library attracts more user base and other advantages ...

Thanks for the wonderful work. Keep rocking

**Comment by gabordemooij** [comment]
Comments are for the developers, for you. Comments do not in any way harm performance. Any decent interpreter or compiler will ignore them and cache the resulting AST somehow. And, you can always do:

    php -w rb.php

Small size is good. But if people start counting lines without correcting for comments, that's not really pragmatic anymore.

**Comment by SusanthCom** [comment]
Thanks @gabordemooij
