### ISSUE TITLE
Is there a 5.x release available on packagist or here?

### ISSUE THREAD

**Issue by k00ni** [gabordemooij/redbean#587]
Could not find any, but was wondering because on the homepage and here, you find the information to download this version.

* https://redbeanphp.com/index.php?p=/download (version 5 is recommended)
* https://github.com/gabordemooij/redbean/releases (no 5.x release available)

composer ignores version information with 5 with the following output:

```
  Problem 1
    - The requested package gabordemooij/redbean 5.* exists as 
gabordemooij/redbean[dev-RedBeanPHP3_4_X, dev-RedBeanPHP3_5_X, 
dev-backportsqlfilters35, dev-issue525, dev-master, v3.3.5, v3.3.6, v3.4, 
v3.4.1, v3.4.2, v3.4.3, v3.4.4, v3.5, v3.5.1, v4.2.0, v4.2.1, v4.3, v4.3.1, 
v4.3.2, v4.3.3, v4.3.4] but these are rejected by your constraint.
```

**Comment by gabordemooij** [comment]
Oh no, for some reason Packagist once again does not 'see' the 5.0 release.... sigh....

**Comment by gabordemooij** [comment]
omg... why on earth do they make me install the service hook and then require me to manually click the update button... really? I dont get it.

**Comment by gabordemooij** [comment]
seems to be solved now..

**Comment by k00ni** [comment]
Thanks @gabordemooij
