### ISSUE TITLE
Logger interface

### ISSUE THREAD

**Issue by flip111** [gabordemooij/redbean#588]
Can the interface requirement for `RedBeanPHP\Logger` please be removed and instead use `Psr\Log\LoggerInterface` from https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md

That way i can just put monolog in there with `R::getDatabaseAdapter()->getDatabase()->setLogger($monolog);` and aggregate my app logs and query logs in the same log.

**Comment by flip111** [comment]
By the way i noticed that setting 3 to http://www.redbeanphp.com/api/class-RedBeanPHP.Facade.html#_debug didn't enable fancyDebug ... maybe i made a mistake here so i don't open an issue for it

**Comment by flip111** [comment]
For anyone who is looking for a redbean to monolog bridge. This small anonymous class (available since PHP 7) will do the job

```php
R::getDatabaseAdapter()->getDatabase()->setLogger(new class($app['logger']) implements RedBeanPHP\Logger{
  private $logger;
  public function __construct(Psr\Log\LoggerInterface $logger) { $this->logger = $logger->withName('sql'); }
  public function log() { $this->logger->debug(...func_get_args()); }
});
```

**Comment by flip111** [comment]
Can the log output of redbean clean up a somewhat? For example

```
SELECT `mconfig`.*  FROM `mconfig`  ORDER BY id   -- keep-cache []
```
`--keep-cache` seems to be an implementation detail of redbean leaking into the SQL query.

```
resultset: 4 rows []
```
For which query is this the resultset? It *looks* like it's the previous query, but can this be guaranteed? How about if you write async code?

**Comment by gabordemooij** [comment]
Why don't you build a plugin for RedBeanPHP? That way even more people can enjoy your solution and you get the credit? ;)

**Comment by flip111** [comment]
I think it's better to change this in the core of redbean, but that's up to you. What would be required to write a plugin?

**Comment by gabordemooij** [comment]
https://redbeanphp.com/index.php?p=/plugins_create_your_own

Looking forward to your plugin, I will put it on the plugins page for sure!
