### ISSUE TITLE
Help chapter on N+1 problem

### ISSUE THREAD

**Issue by flip111** [gabordemooij/redbean#589]
Could there please be added a help chapter on how to avoid the [N+1 problem](https://stackoverflow.com/questions/97197/what-is-n1-select-query-issue)? I was using RedBean 3 with preloading for this, but now that it has been removed i don't know what to do. I saw some mentioning of writeCache somewhere. I only enable this for production (because i don't know what it does). I can hardly imagine a cache being able to help out in making SQL joins and hydrating beans.

**Comment by flip111** [comment]
Also i'm missing a mechanism when doing manual queries with R::getAll() how to retrieve 2 types of models (with a JOIN) and put them in beans.

**Comment by flip111** [comment]
This is a piece of example code where i basically use raw SQL and raw PHP to select the beans i want. I can't move all the logic into SQL i have to do some in PHP as well. At the end i have to re-query things to load the beans for the selected ID's. This feels more like an ugly workaround for the problem, but it reduced my page load (in debug mode) from 30 seconds to 2 seconds, so still a big win.

```php
<?php
$rows = R::getAll("
  SELECT f.id AS f_id, f.title AS f_title, f.description as f_description, s.id AS s_id, s.kind as s_kind, s.fullname AS s_fullname
  FROM feature_release AS fr
  JOIN feature AS f
  ON f.id = fr.feature_id AND fr.release_id = ?
  JOIN feature_standard AS fs
  ON fs.feature_id = f.id
  JOIN standard AS s
  ON fs.standard_id = s.id
", [$this->bean->dat->resultset->release->id]);

// custom hydrating loop
$f_s = [];
foreach ($rows as $row) {
  $s =
    [ 'id' => (int) $row['s_id']
    , 'kind' => $row['s_kind']
    , 'fullname' => $row['s_fullname']
    ];
  if (isset($f_s[$row['f_id']])) {
    $f_s[$row['f_id']]['standards'][] = $s;
  } else {
    $f_s[$row['f_id']] =
      [ 'id' => $row['f_id']
      , 'title' => $row['f_title']
      , 'description' => $row['f_description']
      , 'standards' => [$s]
      ];
  }
}

// Do a lot of work with $f_s put the remaining $standards in $ss

$ss_ids = array_column($ss, 'id');
$standards = R::find('standard',' id IN (' . R::genSlots($ss_ids) . ')', $ss_ids);
```

**Comment by gabordemooij** [comment]
Have you taken a look at findMulti? This feature in RB4 sort of replaced the Preloader (it's more generic, the preloader got too complex and too specific).

https://redbeanphp.com/index.php?p=/finding#find_multi
https://redbeanphp.com/api5/classes/RedBeanPHP.Finder.html#method_findMulti

**Comment by flip111** [comment]
Ok that looks like it could work, i will give it a try.

Why do you recommend this? Do you have an example of such mapping creating function?

> While you can specify mappings like this, a better idea might be to write your own set of mapping functions returning structures like this.
