### ISSUE TITLE
why redbean error not working in try catch if there is any error like duplicate key

### ISSUE THREAD

**Issue by MarcelVe** [gabordemooij/redbean#590]
Hi, can you help me with this problem?
Example;
R::begin();
try {
   $estudante = R::dispense('estudantes');
   $estudante->estudante_nome = ucwords(strtolower(trim($this->formPost['form-nome'])));
   $estudante->estudante_cpf = $this->encode(str_replace($caracteres,'',$this->formPost['form-cpf']));
   $id = R::store($estudante);
   R::commit();
   R::close();
} catch (Exception $e) {
     // THIS CATCH NEVER HAPPENS
     R::rollback();
     R::close();
     $this->result = $e->message;
}

Thank ypu.

**Comment by r3wt** [comment]
How can we help you if you don't explain the problem. You have to provide us more information. 

Mi no hablo espanol, perro, yo tengo preguntas para ti:

1. why are you using a transaction for an insert?
2. why do you anticipate the above code should fail?

**Comment by MarcelVe** [comment]
Hi, i will try to explain better. Sorry but my english is not so good.

Ok, the transaction isn't needed.
In the code below, when a duplicate key happens, the proccess don't go to catch exception. Because that i can't manage the duplicate key, if occurs.
Why the proccess don't go to catch exception?

The field "estudante_cpf" is unique in database table.

try {
$estudante = R::dispense('estudantes');
$estudante->estudante_nome = $this->formPost['form-nome'];
$estudante->estudante_cpf = $this->formPost['form-cpf'];
$id = R::store($estudante);
R::close();
} catch (Exception $e) {
// THIS CATCH NEVER HAPPENS
// BUT HERE I NEED TO MANAGE THE DUPLICATE KEY
R::close();
$this->result = $e->message;
}

Thanks for your help.

**Comment by flip111** [comment]
@MarcelVe please use [syntaxhighlighting blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting) for your code

Also can you show us the actual exception that you get when you remove the try-catch block? Use the [php.ini development configuration](https://github.com/php/php-src/blob/master/php.ini-development) to get errors

**Comment by gabordemooij** [comment]
This might be an issue with RB4 and SQLite. Have you tried RB5? I refined the error handling for SQLite.

**Comment by MarcelVe** [comment]
Ok, here is the actual exception:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry

When occurs this, the try-catch is not called.

Thank you all.

**Comment by flip111** [comment]
@MarcelVe what is the type of the exception? you only showed the message of the exception.

**Comment by MarcelVe** [comment]
Hi, in try-catch i'm using this type "try ... catch (Exception $e)".

**Comment by MarcelVe** [comment]
Ok, than you all. I was able to solve the problem.
