### ISSUE TITLE
 $bean->import() requires '_type' to be set on child beans

### ISSUE THREAD

**Issue by ramononis** [gabordemooij/redbean#592]
```
['id' => '2',
  'title' => 'Title',
  'public' => '1', 
  'ownPhoto' => [
    ['_type' => 'photo', 'url' => 'trol']
  ]
]
```

The above array can be imported into a bean without problems.  
When I remove '_type' in the ownPhoto array though, it will fail because import() requires '_type' to be set.  
Why is this necessary? Doesn't the key 'ownPhoto' already indicate that the type of the child beans is 'photo'.

**Comment by gabordemooij** [comment]
Lists can be aliased, that's why. Sorry, you have to specify the type.

**Comment by ramononis** [comment]
I see. I'm struggling with the fact that the output of export() cannot be used as input for import() because export doesn't set _type for beans. 
Is it possible to let export set the type of beans in its output?

**Comment by gabordemooij** [comment]
Ah, now I see your point. It might sound strange but that was never really how import() and export() were designed. Although the idea sounds really cool, so you can export an entire bean graph and then store it again with import. Sounds nice. Unfortunately that's not really how it works right now. Import and export just evolved as additional tooling. RB was originally more geared toward a mix between traditional ORMs and a No-SQL-like approach. I like the idea though. Just not sure I have the time at the moment to implement this.

**Comment by gabordemooij** [comment]
I guess I could tweak the export() function to set a _type property if a certain flag is passed.

**Comment by gabordemooij** [comment]
I tried this but it does not work. RedBeanPHP has not been designed this way. There are several issues with re-importing exported beans:

- shared beans can be stored in two ways, depending on your architecture, therefore the export function export 2 versions of these beans to accomodate you (via-links and shared beans), however this means you cannot simply re-import those arrays
- re-importing beans with an ID in an empty database wont work, so whether importing is possible depends on the current state of the database
