### ISSUE TITLE
Reload a specific column in a bean?

### ISSUE THREAD

**Issue by krisives** [gabordemooij/redbean#595]
Hi we have a cron task that has a bean where the value can be changed from another process/server. We want to keep caching and avoid using `fresh()` to reload the entire bean, is there a way to tell RedBean to either not cache a specific column or reload just that column?

Thank you!

**Comment by gabordemooij** [comment]
I see the issue but this is not possible right now. Is there are reason why in this case you are not resorting to plain simple SQL?

**Comment by gabordemooij** [comment]
Just use SQL for this kind of work.
