### ISSUE TITLE
Update Or Create Bean

### ISSUE THREAD

**Issue by dvdtth** [gabordemooij/redbean#603]
Redbean has a findOrCreate function which works great to see if the bean exist, and create one if it dne.

It would be great to have something like a updateOrCreate function as well. More of why I think it's useful is so that it can be used to do the equivalent of "INSERT INTO... ON DUPLICATE UPDATE", and the only way I'm able to do this now is passing raw sql through R::exec

* btw, other ORM ex. Laravel, has such feature built in OOTB https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Builder.php#L269

**Comment by gabordemooij** [comment]
In RedBeanPHP storing a bean will also create it if it's not there. This is effectively the same. The on duplicate functionality in SQL is more powerful though, I don't see the point of recreating this functioanlity in RB.

**Comment by elis-k** [comment]
what do you mean "i dont see the point".  
The whole point is to use redbean and its syntax for performing more simpler & clearer database queries, a method that inserts or updates is neccessary.

**Comment by Lynesth** [comment]
@elis-k What would that do that `R::store` doesn't ?
```php
// This will effectively update the bean if it already exists
// in the database or create a new one if it doesn't
R::store($somebean);
```

**Comment by elis-k** [comment]
@Lynesth 
If it does perform update on duplicate index, then it's my mistake. 
Though i couldn't find anything on documentation.
