### ISSUE TITLE
Remove findLast()

### ISSUE THREAD

**Issue by Lynesth** [gabordemooij/redbean#615]
I think we should start thinking about removing `findLast()` from future major updates.

The function fills an array with results from a query (which can return a lot of rows depending on your data) to only return the last element of that array. This is the opposite of optimal.

People should learn to reverse the ORDER BY of their query and use `findOne()` instead. This is something we unfortunatly can't do for them (well, we could, but that's not really the point).

What's your point on this ?

**Comment by gabordemooij** [comment]
I agree, it's a terrible function. It was a mistake to add this function. I propose to deprecate it and attach a warning message to the documentation. I rather not remove it right now because I care a great deal about backward compatibility.

**Comment by gabordemooij** [comment]
I have added the warning and deprecated the function.

https://github.com/gabordemooij/redbean/commit/1a8a46f5eaf7abf10700a3e9823d71d3647b9a34
