### ISSUE TITLE
Invalid type when dispensing

### ISSUE THREAD

**Issue by Laegel** [gabordemooij/redbean#618]
Hi @gabordemooij , 

First, I'd like to thank you for your project! I was planning to make something similar till I discover RedBeanPHP, but to be honnest, your work is better than what I could have done. 
Next, here comes my issue: as I was migrating my models (note: DB had already been defined) to RedBeanPHP, I discovered something quite disappointing:
PHP Fatal error:  Uncaught RedBeanPHP\RedException: Invalid type: **test_table** in gabordemooij/redbean/RedBeanPHP/Util/DispenseHelper.php:37.
The fact is: I have tables with underscores in their names and I don't want to/cannot change them because those names are compound (e.g., "posts_localization").
I've seen that commenting the regex match on line 37 didn't trigger errors of this kind farther in the code, so, do you think you could be a bit more flexible and enable the use of underscores? 

Thanks for reading!

**Comment by gabordemooij** [comment]
Okay, you can now use:

\RedBeanPHP\Util\DispenseHelper::setEnforceNamingPolicy( FALSE );

https://github.com/gabordemooij/redbean/commit/f6da0908db36195b8e0f6d8e1c7d1aeda749fa25

**Comment by Laegel** [comment]
Thanks a lot!
