### ISSUE TITLE
Check many-to-many connection

### ISSUE THREAD

**Issue by s4dnss** [gabordemooij/redbean#619]
I have 2 tables with many-to-many connection. I have a foreach loop with table1 rows to check which one has connection with table2. It's working fine, but if there's no connection between tables, I get a PHP Notice with Undefined offset... And I can't get rid of that... I tried 'isset', 'is_null', 'empty', 'is_object'... Any suggestion?

```
foreach ($ids as $id) {
  if (!is_null($table1->sharedTable2List[$id])) {
    // do something
  }
}
```
Thx!

**Comment by gabordemooij** [comment]
Over here, the following test case just works fine:


```
$book = R::dispense('book');
$book->sharedPicture[] = R::dispense('picture');
R::store($book);
$book = $book->fresh();
$p = isset($book->sharedPictureList[2000]);
```

triggers no warnings or notices....

**Comment by s4dnss** [comment]
With your code I get 'false' in every cases, even if the 'Picture' with specified id is exists. Meanwhile I've found a solution:

```
if ($book->withCondition('picture'.id = ?', [$id])->countShared('picture')) {
  // do something
}
```

if there's no connection between book and specified picture, the condition above will give '0' without any php notice.

Thank you so much!!

**Comment by gabordemooij** [comment]
Glad you found a solution.
