### ISSUE TITLE
Prevent mysql column conversion to snake-case from camel-case?

### ISSUE THREAD

**Issue by yossicadaner** [gabordemooij/redbean#620]
BS"D

I would like to use camel-case mysql column names. Not snake case. Is this possible?

Hello and thank you for a great framework.

**Comment by yossicadaner** [comment]
Alternative would it possible to convert responses back to camel case

**Comment by gabordemooij** [comment]
Unfortunately no. This has to do with the fact that RB has to run out-of-the-box everywhere.
