### ISSUE TITLE
Have beans remember which database they come from

### ISSUE THREAD

**Issue by Lynesth** [gabordemooij/redbean#629]
So I'm currently working on a big project with many databases and I have to select the correct database each time I need to do something on a bean to make sure it's the correct one.

So I was thinking, why not have each bean remember which toolbox it needs to access once it's been dispensed ?

I'm currently doing it using a custom beanHelper that I set for each new database:

```php
<?php
class IntelligentBeanHelper extends RedBeanPHP\BeanHelper\SimpleFacadeBeanHelper {
    public function getToolbox() {
        return \RedBeanPHP\Facade::$toolboxes[$this->database];
    }

    public function getExtractedToolbox() {
        $toolbox = \RedBeanPHP\Facade::$toolboxes[$this->database];
        return array( $toolbox->getRedbean(), $toolbox->getDatabaseAdapter(), $toolbox->getWriter(), $toolbox );
    }

    public function __construct($database) {
        $this->database = $database;
    }
}

// Let's add some databases
R::addDatabase( 'db1', ... );
$bh = new IntelligentBeanHelper( 'db1' );
R::$toolboxes[ 'db1' ]->getRedBean()->setBeanHelper( $bh );

R::addDatabase( 'db2', ... );
$bh = new IntelligentBeanHelper( 'db2' );
R::$toolboxes[ 'db2' ]->getRedBean()->setBeanHelper( $bh );

R::addDatabase( 'db3', ... );
$bh = new IntelligentBeanHelper( 'db3' );
R::$toolboxes[ 'db3' ]->getRedBean()->setBeanHelper( $bh );


R::selectDatabase( 'db1' );
$book = R::load('book', 1);

R::selectDatabase( 'db2' );
$pizza = R::dispense('pizza');

R::selectDatabase( 'db3' );

// This works even with db3 currently selected
$book->xownPageList;

// This works too but need a very small change in the core of RedBean first
$pizza->pepperoni = true;
R::store($pizza);

// And so on....
?>
```

Is this something we'd be interesting in providing inside RedBean ?
If so, should it be the default behavior ? Only as an option ?

Let me know what you think @gabordemooij and anyone else using RedBean regularly, and if you're interested I'll submit a PR.

Lyn.

**Comment by gabordemooij** [comment]
I like this approach very much, I think we should try to turn this into a plugin or something. I don't think it's wise to implement the bits of logic required to make this work throughout the entire codebase.

**Comment by gabordemooij** [comment]
I guess you need https://github.com/gabordemooij/redbean/pull/632 for this to work?

**Comment by Lynesth** [comment]
This currently cannot work for Facade static function (the OODB isn't accessed the same way).

And yes, I need #632 for this :)

**Comment by gabordemooij** [comment]
I am taking a shot at this as well...

**Comment by Lynesth** [comment]
Nice.

I thought I should take it step by step, so I'm actually making a PR (which I don't think you'll like much :p) regarding part of this issue.

**Comment by gabordemooij** [comment]
What about this:

https://gist.github.com/gabordemooij/6feefc4964cafa766a085557d8900389

It seems to work, and requires almost no changes in RedBeanPHP at all.

**Comment by Lynesth** [comment]
@gabordemooij Can I expect anything regarding this matter ?
I understand that the way I proposed it (#634 / #641) surely wasn't how it should be done, but are you considering implementing this functionnality or not ?

I'm not being agressive or anything, just need to know so that I can really work on this on my own if that's the case :)

**Comment by gabordemooij** [comment]
I have created a plugin and waiting for your feedback...

Op di 12 jun. 2018 04:09 schreef Lynesth <notifications@github.com>:

**Comment by Lynesth** [comment]
I actually commented on this gist on the same day you posted it, I think you may have missed that :)

**Comment by gabordemooij** [comment]
Ok, I must have missed that, sorry. I will look into it asap.

Op di 12 jun. 2018 06:53 schreef Lynesth <notifications@github.com>:

**Comment by gabordemooij** [comment]
ping @Lynesth https://gist.github.com/gabordemooij/6feefc4964cafa766a085557d8900389

**Comment by gabordemooij** [comment]
I will continue to work on this as a plugin but it will not be a core 'feature' of RedBeanPHP.
