### ISSUE TITLE
Array may only contain OODBBeans

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#649]
I have been working on this for a few hours, and can't figure out the problem. I'm beginning to think it may be a bug, so thought I'd post.

Consider the following:

```
$newContractList = [ ];

foreach( $item->ownContractList as $contract )
{
    if( isset($_POST['mfg_name_'.$contract->id]) )
    {
        $mfg = \R::findOrCreate('manufacturer', [ 'name' => $_POST['mfg_name_'.$contract->id] ]);
        
        $contract->manufacturer   = $mfg;
        $contract->contractNumber = trim( $_POST['mfg_contract_'.$contract->id] );
        $contract->date           = trim( $_POST['mfg_date_'.$contract->id] );
        
        $newContractList[] = $contract;
    }
}

$item->ownContractList[] = $newContractList;

\R::store($item);
```

This produces the following fatal error:

> Array may only contain OODBBeans

Removing the `$item->ownContractList[] = $newContractList;` prevents the error from appearing, and the bean is correctly updated. However, what's really strange, the following code:

```
foreach( $newContractList as $contract )
{
    echo get_class($contract)."\n";
}
```
Produces the following output:

> RedBeanPHP\OODBBean 
> RedBeanPHP\OODBBean

So I can't see where there are any non-OODBBeans in the `$newContractList` array?

**Comment by Lynesth** [comment]
It seems to me you are adding an array of beans at the end of your array, producing something like:

```php
Array(
    /* whatever was already here */,
    Array(
        /* Your new beans */
    )
)
```

You may want to merge those arrays instead or remove the `[]` at the end of `$item->ownContractList[]`

**Comment by benmajor** [comment]
Fantastic spot, such a long morning! Thank you @Lynesth.

**Comment by Lynesth** [comment]
No worries ;)
