### ISSUE TITLE
Hook into the jsonSerialize function

### ISSUE THREAD

**Issue by brtdv** [gabordemooij/redbean#651]
When I get a bean from the database, and export it with json_encode, the `jsonSerialize` function inside the `OODBBean` gets called. 

Is there a way to 'hook in' to this function, or provide a "custom callback"?

For example: I might have a `user` bean, which has the following properties: `id`, `first_name`, `last_name`. I also have `Model_User` class, that has a `getFullName()` function. 

Right now there's no way in the `Model_User` class to override the `jsonSerialize()` function with my own exported values; which might in my `user` example be something like the following:
```
function jsonSerialize() {
	return array_merge($this->export(), [
		'full_name' => $this->getFullName();
	]);
}
```

Would you accept a pull request that allows for `Model_User` (or basically all `Model_` classes) to have a `jsonSerialize` "hook" function of some sort that can override or inject extra values in the `OODBBean->jsonSerialize()` function?

**Comment by brtdv** [comment]
A solution could be something like this: https://github.com/brtdv/redbean/commit/47bdbd038c4f6233381e07bab925a9a417efb895

I'm not sure about the function naming but basically all `Model` classes could provide a custom `__jsonSerialize` function, and, if available in the `Model`, the result of this function is used to inject into the json result.

The `Model_User` from my example could implement this the following way:
```php
class Model_User {

	...

	public function __jsonSerialize() {
		return array_merge($this->unbox()->export(), [
			'display_name' => $this->getDisplayName()
		]);
	}
}
```

**Comment by gabordemooij** [comment]
Interesting I will look into this.

**Comment by Lynesth** [comment]
Hey there,

Do you really need to hook into that function ? Can't you simply call a custom function instead of ```json_encode``` ? (I don't know what your purpose is so I'm just asking)

For example:

```php
class Model_User {

	...

	public function export() {
		return array_merge($this->bean->export(), [
			'display_name' => $this->getDisplayName()
		]);
	}
}

$user = R::load('user', 1);
$user->box()->export();
```

**Comment by brtdv** [comment]
It's true that for a single bean, you could easily call a custom function. However, this becomes more cumbersome in complex array/hash/... structures. Thats when a custom implementation of `__jsonSerialize` is really usefull... Since there's currently no way to provide this in the `Model_*` classes, it would be great if there's a way to hook into the implementation.

I have a basic implementation ready [here](https://github.com/brtdv/redbean/commit/47bdbd038c4f6233381e07bab925a9a417efb895), but this is just a quick and dirty implementation. I'm sure there's some efficiency stuff that I'm not considering in the implementation.

**Comment by gabordemooij** [comment]
Your PR looks good @brtdv can you send me the PR?

**Comment by gabordemooij** [comment]
Your Pull Request has been merged, I am now adding unit tests to confirm that the code is working properly.

**Comment by gabordemooij** [comment]
Unit tests have been added:
https://github.com/gabordemooij/redbean/commit/8b73734d16b0d7348b7996a0056348e3afe6e2f5

**Comment by gabordemooij** [comment]
Also implemented suggestion by Lynesth, thanks!

**Comment by gabordemooij** [comment]
https://github.com/gabordemooij/redbean/commit/9e9673be6eb3eb1429431cb26dd26df034b72068
