### ISSUE TITLE
Get cursor with raw SQL query

### ISSUE THREAD

**Issue by oderayi** [gabordemooij/redbean#656]
In RedBeanPHP, the only way to work with cursor is through `findCollection`, but `findCollection` does not support raw SQL query. 

Is there a way I can work with cursor while using raw SQL query (with joins) with RedBeanPHP?

Thank you!

**Comment by Lynesth** [comment]
Hey there,

You currently can use this:

```php
R::getToolbox()->getDatabaseAdapter()->getCursor( $sql, $bindings );
```

Example:

```php
$cursor = R::getToolbox()->getDatabaseAdapter()->getCursor( 'SELECT * FROM users WHERE name LIKE ?', [ 'A%' ] );
while ($row = $cursor->getNextItem()) {
    // Do your thing...
}
```

**Comment by gabordemooij** [comment]
It would be good to have a direct function for this in the facade I think.
