### ISSUE TITLE
how to set custom id value instead of auto increment

### ISSUE THREAD

**Issue by sadick254** [gabordemooij/redbean#657]
Is it possible to set a value on the id instead of auto-increment done by the databases.

```php
$book = R::dispense('book');
$book ->id = 'some value';

R::store($book);
```
When I do it like above, there is nothing getting persisted on the db.

**Comment by gabordemooij** [comment]
Hi there,

Managing your own primary keys does not work with RedBeanPHP. If you want custom ids you need to implement your own QueryWriter. Copy-pastable examples are available:

https://redbeanphp.com/index.php?p=/uuids

That page describes how to use MySQL/PostgreSQL UUIDs with RedBeanPHP.
Hope this helps!

Cheers
Gabor
