### ISSUE TITLE
Typo in Migrations Documentation

### ISSUE THREAD

**Issue by VioletPixel** [gabordemooij/redbean#658]
There's a typo on [the Migrations page](https://redbeanphp.com/index.php?p=/migrations) of the documentation.  It currently reads as follows in the **Fluid Migrations** section:

> ... You can temporarily re-activate fluid mode using:
>
>     R::freeze(TRUE);
>
> Don't forget to remove this line after the script has been executed and the required columns and tables have been generated.

This should read `R::freeze(FALSE);` instead.

**Comment by gabordemooij** [comment]
Thanks for the notice, should be fixed by now.
