### ISSUE TITLE
"fresh" function missing in API docs

### ISSUE THREAD

**Issue by alystair** [gabordemooij/redbean#659]
Appears in manual under CRUD, but only seen once in API doc under "aliases()" within example.

**Comment by gabordemooij** [comment]
https://redbeanphp.com/api5/classes/RedBeanPHP.OODBBean.html#method_fresh

**Comment by alystair** [comment]
Am I blind and this was always there or did you just add it? Thanks either way...

**Comment by gabordemooij** [comment]
docs have been updated 3 months ago
no problem
