### ISSUE TITLE
What's the proper way to grab data from a 'via' table?

### ISSUE THREAD

**Issue by alystair** [gabordemooij/redbean#662]
According to the docs if one wants to add information to a many-to-many/sharedList, the via method is the way to go... however what's the correct way to pull the matching data from the table when grabbing the related information when using via?

Let's say we have this affiliation bean:
```php
$affiliate = R::dispense('affiliate');
$affiliate->user = $user;
$affiliate->brand = $brand;
if (v::alpha()->validate($_POST['title'])) $affiliate->title = $_POST['title'];
R::store($affiliate);
```

Now one can easily pull the related data this way... `$user->via('affiliate')->sharedBrandList` but what about the associated `$affiliate->title`?

**Comment by Lynesth** [comment]
Hey there,

I guess you should simply use `$user->ownAffiliateList` to retrieve those and then loop over and get the Brand detail and the Title.

You could also use `R::find('affiliate', ' user_id = ? ', [ $user->id ])` should you prefer.

**Comment by alystair** [comment]
Good to know, still getting accustomed to the way these works. I've been using the second method and it works well.
