### ISSUE TITLE
I have an issue in running query "Identifier does not conform to RedBeanPHP security policies"

### ISSUE THREAD

**Issue by RHamidR** [gabordemooij/redbean#670]
What is wrong with this query, Its works in MySQL clients but RedBean returns this message
**Identifier does not conform to RedBeanPHP security policies**
```
              SELECT l.port + 1 AS start
              FROM mytable AS l
              LEFT OUTER JOIN mytable AS r
                ON  r.server_id= 1 AND
                    l.port + 1 = r.port AND
                    r.port BETWEEN 20000 AND 65535
              WHERE l.server_id= 1 AND r.port IS NULL AND
                    l.port BETWEEN 20000 AND 65535
```

**Comment by Lynesth** [comment]
Hey there,

The issue doesn't specifically come from that query. It just means that either the name of a table or a column contains characters that are not one of those : 

- letters from `a` to `z`
- letters from `A` to `z`
- numbers from `0` to `9`
- an underscore (`_`)

So if the name of your table/column contains anything else (a dash `-` for example), this exception will be thrown.

Lyn.

**Comment by RHamidR** [comment]
Thanks Lynesth for your attention
The table name is just contains letters from `a` to `z`, nothing more.
and whole of query is the mentioned above.
I don't think its occurred for  `server_id` field name, Because when i remove the last line its going to work, and with that line its not working

```
.port BETWEEN 20000 AND 65535
```

**Comment by Lynesth** [comment]
Hmm, that'll be hard to debug...

Could you find the line that says
```php
throw new RedException( 'Identifier does not conform to RedBeanPHP security policies.' );
```
in your redbean file and replace it with
```php
throw new RedException( 'Identifier "' . $struct . '"does not conform to RedBeanPHP security policies.' );
```
and let me know what the exception now is ?

Lyn.

**Comment by RHamidR** [comment]
Identifier "SELECT * 
FROM mytable
WHERE `server_id`=? AND `port`=?"does not conform to RedBeanPHP security policies.

**Comment by Lynesth** [comment]
Thank you.

Could you please provide the code you're trying to execute ?

If the whole script is too big, then the line that matches the SQL in the exception, if possible with context (some lines above and below) would be nice.

**Comment by RHamidR** [comment]
This is the whole of code that has interact with the block
And via your mention to other parts of code i found out the problem is about `checkPortAvailability` function. But i think that query is OK too
```
    private $table_name = 'projectstarters';
    private $server_port_range_start = "20000";
    private $server_port_range_end = "65535";

    public function getAvailablePort($server_id, $getCount = false)
    {
        R::debug();
        $query = "
              SELECT l.port + 1 AS start
              FROM {$this->table_name} AS l
              LEFT OUTER JOIN {$this->table_name} AS r
                ON  r.server_id=? AND
                    l.port + 1 = r.port AND
                    r.port BETWEEN {$this->server_port_range_start} AND {$this->server_port_range_end}
              WHERE l.server_id=? AND r.port IS NULL AND
                    l.port BETWEEN {$this->server_port_range_start} AND {$this->server_port_range_end}
            ";
        if ($getCount) {
            $result = R::getCol("${query} LIMIT ${getCount}", [$server_id, $server_id]);
        } else {
            $result = R::getCell("${query} LIMIT 1", [$server_id,  $server_id]);
        }

        if (empty($result) && $this->checkPortAvailability($server_id, $this->server_port_range_start))
            return $getCount ? range($this->server_port_range_start, $this->server_port_range_start + $getCount ) //Summerized for here
        return $result;
    }


    public function checkPortAvailability($server_id, $port)
    {
        R::debug();
        if ($port<$this->server_port_range_start || $port>$this->server_port_range_end)
            return false;
        $starter = R::findOne("
              SELECT *
              FROM {$this->table_name}
              WHERE `server_id`=? AND `port`=?
            ", [$server_id, $port]);
        return empty($starter);
    }
```

**Comment by Lynesth** [comment]
Okay the issue in `checkPortAvailability` is that you should use `R::getRow` instead of `R::findOne` (which is used to retrieve beans).

**Comment by RHamidR** [comment]
OMG I cant believe that i waste my day for this foolish mistake.
Thanks a lot for your help dear Lynesth

**Comment by Lynesth** [comment]
Happy to help :)

If it's all good for you on this matter, you can close the issue.

Lyn.
