### ISSUE TITLE
Extend testConnection()

### ISSUE THREAD

**Issue by Lynesth** [gabordemooij/redbean#672]
The way the testConnection function currently works is not optimal.
It doesn't check anything really, except if we initiated a connection to the database at some point before.

I think this needs to be improved to test that we are connected to the database and that the database is responding (maybe with an option to automatically reconnect if it failed).

If it were me, I guess i'd simply do something like
```php
try {
    // Simple query using as little ressources as possible
    @R::getPDO()->query( 'SELECT 1' );
} catch (PDOException $e) {
    // It failed, there's an issue
}
```

@gabordemooij 
You said in #667: "We could extend the testConnection function to test a specific SQL scenario maybe?"
What did you have in mind ?

**Comment by gabordemooij** [comment]
I was wondering if we should allow the user to specify the query to test?

**Comment by marios88** [comment]
Allowing the user to specify the query, allows for more options 
Functionality i can see being useful, based on the pull of @Lynesth

```
R::testConnection(FALSE,SELECT version FROM version, DB_VERSION);

	public static function testConnection( $autoReconnect = FALSE, $sql = 'SELECT 1',$expected = '1' )
	{
		if ( !isset( self::$adapter ) ) return FALSE;
		$database = self::$adapter->getDatabase();
		try {
			$result = $database->getPDO()->prepare( $sql )->execute()->fetchColumn();
                        if($result != $expected){
                            throw new \Exception( 'SQL returned unexpected data' );
                        }
		} catch ( \Exception $e ) {
			if ( !$autoReconnect ) return FALSE;
			$database->close();
			$database->connect();
		}
		return TRUE;
	}

````

on the other side if you dont plan to allow for conditional testing of the result query, i think there is no need for the user to be able to change the query, since it just makes it more complex and error prone

**Comment by Lynesth** [comment]
@marios88 I agree with @gabordemooij that your exemple is a bit out of the scope of the function.
I'm not even sure allowing to specify the request is a valid concern except in case someone creates a driver for a database that doesn't accept a request as simple as `SELECT 1` (like Oracle or HSQLDB).

**Comment by marios88** [comment]
@Lynesth You are right, i didnt consider this
> a database that doesn't accept a request as simple as SELECT 1
