### ISSUE TITLE
According to the documentation R::hunt returns an array but it relies on trashAll which returns void

### ISSUE THREAD

**Issue by HF0** [gabordemooij/redbean#675]

**Comment by Lynesth** [comment]
Indeed, that's a mistake.

I guess we could either return:
- Number of beans deleted
- Array of deleted beans
- Void (just fix the docs)

@gabordemooij what do you think ?

**Comment by HF0** [comment]
Option number 1 or 2 would be ideal

**Comment by gabordemooij** [comment]
ok
