### ISSUE TITLE
findMulti doesn't work with tables wrapped in ` quotes

### ISSUE THREAD

**Issue by VictorJuliani** [gabordemooij/redbean#683]
Hello!

Currently, I cannot make findMulti calls if my query has \` quotes surrounding table names. For example:
R::findMulti('books', "SELECT \`books\`.* FROM \`books\`") returns me an object with "books" as an empty array. However, if I change the query to simply "SELECT books.* FROM \`books\`", the execution works normally.

**Comment by gabordemooij** [comment]
Thanks for reporting. I will look into this.

**Comment by Lynesth** [comment]
Made a PR to fix this.
Tested it on my end, it worked as intended. Let me know if that fixes it for you.
