### ISSUE TITLE
close and reconnect throwing error

### ISSUE THREAD

**Issue by pnvasanth** [gabordemooij/redbean#685]
When I am trying to close the connection and reconnect to the database its throwing the error.
Here is my code.

**CODE**
```
\R::setup("mysql:host=localhost;dbname=oodb", "root", "password", true);
var_dump(\R::testConnection());
\R::close();
\R::setup("mysql:host=localhost;dbname=oodb1", "root", "password", true);
var_dump(\R::testConnection());
```
**OUTPUT**

> bool(true)
> PHP Fatal error:  Uncaught RedBeanPHP\RedException: A database has already been specified for this key. in /redbeanphp/rb.php:10391
> Stack trace:
> #0 /redbeanphp/rb.php(10312): RedBeanPHP\Facade::addDatabase('default', 'mysql:host=loca...', 'root', 'password', true)
> #1 /bin/test.php(8): RedBeanPHP\Facade::setup('mysql:host=loca...', 'root', 'password', true)
> #2 {main}
>   thrown in /redbeanphp/rb.php on line 10391
> 

I think we need to remove the default key in close function https://github.com/gabordemooij/redbean/blob/master/RedBeanPHP/Facade.php#L1952
Like

```
if (isset(self::$toolboxes['default'])) {
          unset(self::$toolboxes['default']);
}

```

Could you please help me to understand? 
Thank you.

**Comment by gabordemooij** [comment]
Have you tried to reconnect aftter closing?

`R::getDatabaseAdapter()->getDatabase()->connect();`

**Comment by pnvasanth** [comment]
Thank you,  Yeah,  its working fine with same database.  
```
\R::setup("mysql:host=localhost;dbname=oodb", "root", "password", true);
var_dump(\R::testConnection());
\R::close();
\R::getDatabaseAdapter()->getDatabase()->connect();
var_dump(\R::testConnection());
```
But getting the error when I try to connect with different database.

**Comment by Lynesth** [comment]
If you want to add another database, you should use the functions `addDatabase` and `selectDatabase`
```php
\R::addDatabase( 'uniqueKey', $dsn, $username, $password, $frozen, $partialBeans );
\R::selectDatabase( 'uniqueKey' );
```

**Comment by pnvasanth** [comment]
@Lynesth Thank you
