### ISSUE TITLE
Bindings for tables

### ISSUE THREAD

**Issue by gabordemooij** [gabordemooij/redbean#687]
It would be nice to use tables as dynamic variables like bindings.
However there needs to be a security layer that handles this.

**Comment by Lynesth** [comment]
Why would you want to add that inside RedBean ?

**Comment by gabordemooij** [comment]
Because I got this e-mail:

Hello, I am having a small problem when using RedBeanPHP SQLite.。


The following code can't run without any return value
R::getAll("select * from ?",['table_name']);



This also does not work properly
R::getAll("select * from :table",[':table'=>'table_name']);


This is no problem
R::getAll("select * from table");

**Comment by gabordemooij** [comment]
I answered that PDO simply does not support this. I am not convinced it's even desirable.

We don't need to make the binding system more complex, but maybe we can implement a subtle hint or something. Just something to think about for the long term.

**Comment by gabordemooij** [comment]
Actually, there is of course already a mechanism to escape tables:

`$writer->esc( $table )`

it is a public method. Internally RedBeanPHP uses this method to make sure bean types (which are used to generate table names) are safe.
