### ISSUE TITLE
Cannot unset string offsets "_type" Exception when importing data

### ISSUE THREAD

**Issue by nebulousGirl** [gabordemooij/redbean#689]
I am updating libraries in a legacy application. I have run into this issue with `import`:
**Exception: Cannot unset string offsets**

The problem is that the data that I am importing contains arrays that are serialized before saving, but that are imported as is. The new version of Redbeanphp seems to assume that if a array is imported it is a bean. 

Failing imported data:
```php
$_POST['interests'] = array(
    8 => 'Sports'
);
```

Relevant lines from import method: 
```php

if ( isset( $value['_type'] ) ) {
	$bean = $this->beanHelper->getToolbox()->getRedBean()->dispense( $value['_type'] );
	unset( $value['_type'] );
	$bean->import($value);
	$this->$key = $bean;
} else {
	$listBeans = array();
	foreach( $value as $listKey => $listItem ) {
		$bean = $this->beanHelper->getToolbox()->getRedBean()->dispense( $listItem['_type'] );
		unset( $listItem['_type'] ); //<= fails here as _type is not set in the array
		$bean->import($listItem);
		$list = &$this->$key;
		$list[ $listKey ] = $bean;
	}
}
```
Is there another way to do it, or can I submit a fix?

**Comment by gabordemooij** [comment]
Interesting, what version of RedBeanPHP does your application use?

**Comment by gabordemooij** [comment]
@nebulousGirl  ? Still there?

**Comment by nebulousGirl** [comment]
Sorry, I was working on other projects. I am updating from 3.5 to the latest 5.2.

**Comment by gabordemooij** [comment]
I can also research the possibility to make the $bean->import() method more versatile if you like, but then I need some time because I do not have so much time.

**Comment by nebulousGirl** [comment]
If you have to provide time to provide a more robust solution before I come back to this project, I will take it, but the extension solution would also work for me. I could also simply create a function that import the data into the bean.

**Comment by nebulousGirl** [comment]
I ended up doing something else. I've overriden the BeanHelper to add a base model class to all my beans and in the model class I created a legacyImport method that does what RedbeanPHP 3 did when  importing.

```
            $toolbox = R::setup('mysql:host=' . $hostname . ';dbname=' . $database, $username, $password);

            $toolbox->getRedBean()->setBeanHelper(new MySimpleFacadeBeanHelper);
            R::configureFacadeWithToolbox($toolbox);

class MySimpleFacadeBeanHelper extends SimpleFacadeBeanHelper {
    
	public function getModelForBean( OODBBean $bean )
	{
		$model     = $bean->getMeta( 'type' );
		$prefix    = defined( 'REDBEAN_MODEL_PREFIX' ) ? REDBEAN_MODEL_PREFIX : '\\Model_';
		if ( strpos( $model, '_' ) !== FALSE ) {
			$modelParts = explode( '_', $model );
			$modelName = '';
			foreach( $modelParts as $part ) {
				$modelName .= ucfirst( $part );
			}
			$modelName = $prefix . $modelName;
			if ( !class_exists( $modelName ) ) {
				$modelName = $prefix . ucfirst( $model );
				if ( !class_exists( $modelName ) ) {
					$modelName = 'Redbean_Model';
				}
			}
		} else {
			$modelName = $prefix . ucfirst( $model );
			if ( !class_exists( $modelName ) ) {
                $modelName = 'Redbean_Model';
			}
		}
		$obj = self::factory( $modelName );
		$obj->loadBean( $bean );
		return $obj;
	}
}

**Comment by gabordemooij** [comment]
Thanks for updating this thread and posting a solution. If you like we can share this solution as a a separate class for others to use on the website. On the other hand, not really sure, but what if I checked on the first line of the else-code whether the first element in the array contains a _type key? Or would that still pose an issue?

**Comment by nebulousGirl** [comment]
I think that would work, but since I seem to be the only one that reported
the problem, it might not be worth complexifying the codebase.

The hotfix class is a good idea.

Le dim. 4 oct. 2020 04:52, Gabor de Mooij <notifications@github.com> a
écrit :

**Comment by gabordemooij** [comment]
Great, I would love to host your class on the website, can you send me a tgz or zip package with your code and your credits in the comments?
