### ISSUE TITLE
Using composer gives errors

### ISSUE THREAD

**Issue by rivets** [gabordemooij/redbean#690]
I know composer is not recommended but RedBean is part of a larger system and needs to be installed  without any intervention so composer it is.

There have been strange errors/warnings for a while now, but today when I do a composer update I am getting hard errors about unpunished changes. This is not particularly useful for users of my system.  Any chance of cleaning this up?

**Comment by gabordemooij** [comment]
Can you be a little more specific? What errors do you get? What are 'unpunished' changes? Do you mean unpublished?

**Comment by marios88** [comment]
@rivets are you using dev:master in your composer.json?

**Comment by gabordemooij** [comment]
Over here, dev-master works fine, including autoloading. Maybe @rivets can paste the error here?

**Comment by rivets** [comment]
Sorry about delay in replying!! The error I get is this:

   Update failed (Source directory ...../vendor/gabordemooij/redbean has unpushed changes on the current branch: 
M	RedBeanPHP/Facade.php
M	RedBeanPHP/Logger/RDefault/Debug.php)

I have never touched the code in the tree - it was created using composer - so I don't see how there can be unpushed changes.

L.

**Comment by Lynesth** [comment]
Seems like this can happen sometimes with composer (just searching for `has unpushed changes on the current branch` gives some results) not sure why in this case.

I guess you can remove and reinstall it. If you keep having issues after that, then there's a real problem to hunt.

**Comment by k00ni** [comment]
I recommend using a fixed version (like "^5.2") in composer instead of *dev-master*. Not only would this speed up your composer (cache used), but also makes it more reliable, which version of RedBeanPHP actually runs. I installed it yesterday and it worked out of the box. Hope it helps.

**Comment by rivets** [comment]
I was just following the instructions:-) I'll try a fixed version number.

**Comment by rivets** [comment]
Still get an error:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating gabordemooij/redbean (dev-master c0df346 => v5.2):     Update failed (Source directory /home/www/framework/vendor/gabordemooij/redbean has unpushed changes on the current branch: 
M	RedBeanPHP/Facade.php
M	RedBeanPHP/Logger/RDefault/Debug.php)
    Would you like to try reinstalling the package instead [yes]?

**Comment by k00ni** [comment]
> I was just following the instructions:-)

No problem :)

> Updating gabordemooij/redbean (dev-master c0df346 => v5.2): Update failed (Source directory /home/www/framework/vendor/gabordemooij/redbean has unpushed changes on the current branch:
M	RedBeanPHP/Facade.php

Please manually remove the "vendor" folder and run

```bash
composer clearcache && composer update
```

which clears the cache and reloads all dependencies.

Afterwards please paste the result here.

**Comment by rivets** [comment]
Sorry about delay in replying - didn't see this. That cleared the problem. Thanks
