### ISSUE TITLE
When R::setup() with no parameters doesn’t work

### ISSUE THREAD

**Issue by kokoshneta** [gabordemooij/redbean#694]
The documentation recommends using `R::setup()` with no parameters for testing and fooling around, to create a test SQLite database in /temp on the server. It says, “On most systems, this just works”.

I can’t find any information on where to go if it **doesn’t** just work, though, which it doesn’t for me. Trying to initiate this test database just results in the `RPDO->connect()` method throwing an exception; turning on debugging, for example, gives me this:

```
Fatal error:  Uncaught PDOException: Could not connect to database (?). in {path}\RedBeanPHP\Driver\RPDO.php:431
Stack trace:
#0 {path}\RedBeanPHP\Driver\RPDO.php(570): RedBeanPHP\Driver\RPDO->connect()
#1 {path}\RedBeanPHP\Facade.php(461): RedBeanPHP\Driver\RPDO->setDebugMode(true, Object(RedBeanPHP\Logger\RDefault\Debug))
#2 {path}\RedBeanPHP\Facade.php(479): RedBeanPHP\Facade::debug(true, 0)
#3 called_file.php(12): RedBeanPHP\Facade::fancyDebug(true)
#4 {main}
  thrown in {path}\RedBeanPHP\Driver\RPDO.php on line 431
```

Might it not be a good idea to be a bit more verbose in the documentation and offer some suggestions on what could be the problem if the standard fooling-around way doesn’t work? As a brand new user who’s trying to debug, I have no idea where to even look …

(I’m on a Plesk-administered Windows Server 2012 R2 server on PHP 7.1.25 FastCGI. Both the pdo_sqlite and sqlite3 extensions are enabled in php.ini and the .dll files exist in the appropriate directory, but I have not previously created or used any SQLite databases on the server.)

**Comment by kokoshneta** [comment]
A bit of digging around revealed what the issue was: PHP does not have write access to the temp folder (`C:\Windows\Temp`) so the SQLite `.db` file could not be created.

Changing `R::setup()` to `R::setup('sqlite:' . getcwd() . '\red.db)` and creating the database file in the current directory instead of putting it in the temp directory solved the issue.

I’m guessing this isn’t an uncommon thing to occur, so it is probably worth mentioning in the documentation.

**Comment by gabordemooij** [comment]
Added a note: https://redbeanphp.com/index.php?p=/connection

**Comment by gabordemooij** [comment]
thx!

**Comment by osmonbekchynaliev** [comment]
Hello, I have a problem connecting mariaDb 11.1!
unable to connect to database
