### ISSUE TITLE
Many To Many - Odd Behaviour

### ISSUE THREAD

**Issue by justtoprogram** [gabordemooij/redbean#695]
The tables are:

- kioskmodels
- components

Where kioskmodels can have multiple components in the 1 model. Currently, I don't allow RedbeansPHP to add/remove db tables fluidly. I like to have manual control over that.

So I have a table called: kioskmodels_components with 2 columns;
1. kioskmodels_id
2. components_id

The problem, when I'm adding a new record into kioskmodels, using the dispense function as below:

    if(!$this->isEdit()) $kiosk_model = R::dispense('kioskmodels');

	$kiosk_model->import($this->getValidation()->data['kioskmodels']);

	if(!empty($this->getValidation()->data['components'])) {
		$kiosk_model->sharedComponentsList = $this->getValidation()->data['components'];
	}

	R::begin();

	try {
		R::store($kiosk_model);
		R::commit();
	} catch(\Exception $e) {
		R::rollback();
		throw $e;
	}

What happens is when I'm adding a new record, I dispense a new kioskmodel bean. If it is editing an existing record, the R::load is used earlier on.

However, when inserting a new kioskmodels and associating it with components, it wants to use a table called "components_kioskmodels". When this happened, I went along with it and changed the db table to match it.

However when I tested the edit setting, it wanted to use "kioskmodels_components" as I originally had it (Which I'd prefer).

Further, inside the "$this->getValidation()->data['components']" is an array of Beans using the R::loadAll('components', $value); and value comes from the user.

**Comment by justtoprogram** [comment]
Hi Lyn,

Thanks for the response. That's interesting it's in Alphabetical order, I'll keep that in mind.

As I said, the issue I'm having is when adding a new Record using R::dispense('kioskmodels') and sharing them as above, it wants to use the table called components_kioskmodels, which is fine.

However, when I edit an existing record using R::load('kioskmodels', $id), it wants to use kioskmodels_components.

If it helps, I can replicate the issue and show the record results here.

**Comment by Lynesth** [comment]
> If it helps, I can replicate the issue and show the record results here.
I'd like that yes. I tried on my side and everything works fine.

```php
$kiosk = R::dispense('kiosk');
$component = R::dispense('component');

$kiosk->sharedComponentList[] = $component;

R::store($kiosk);
R::store($component);

$kiosk2  = R::load('kiosk', 1);
$component2  = R::load('component', 1);

// Those contains the correct bean
$kiosk2->sharedComponentList;
$component2->sharedKioskList;

// This returns only 3 tables, "kiosk" "component" and "component_kiosk"
R::inspect();
```

**Comment by justtoprogram** [comment]
Hi Guys,

I will get back to you very shortly. I'm sorry, I've been flat out with other work.

I'll try again and let you know how I go. Maybe I made a mistake.

Cheers,
Tim

**Comment by Lynesth** [comment]
Hi there @justtoprogram 

Have you been able to check if you would reproduce your issue ?

Regards,

Lyn.

**Comment by justtoprogram** [comment]
Hi Lyn,

I haven't tried yet. I've been flat out on other things.

If you give me a few days I'll give it ago and let you know.

Cheers,
Tim

**Comment by Lynesth** [comment]
@justtoprogram No problem, I'll be waiting for your answer then :)

**Comment by Lynesth** [comment]
@justtoprogram Hey there. Just checking if you managed to work this out or if you still need help :)

**Comment by justtoprogram** [comment]
Hi,

I think I have, as funnily enough, I haven't been back to that part where I
had the issue for a while. However I've implemented the same thing in a
different area of the system without issue for both dispense and load.

I'm not sure when I'll be able to get back to the other area because
unfortunately, I'm a sole developer for the project and the project is just
getting bigger and bigger day by day with requests and scope changing, I'm
not in much of a position to get back and check this stuff out :(

When I get back to it I'll let you know.

Thank you for following up.

Kind regards,
Tim
