### ISSUE TITLE
MySQL SSL connect

### ISSUE THREAD

**Issue by bartspiering** [gabordemooij/redbean#696]
Hi!

Is there a way to connect to MySQL via SSL?

Thanks for your help!

**Comment by gabordemooij** [comment]
yes just configure the pdo object and pass it to setup()

**Comment by gabordemooij** [comment]
https://stackoverflow.com/questions/29634341/php-pdomysql-ssl-connection

**Comment by Jemt** [comment]
For anyone else wondering how to get this working, please see:
https://github.com/gabordemooij/redbean/issues/834
