### ISSUE TITLE
Some issues with tagged items

### ISSUE THREAD

**Issue by rivets** [gabordemooij/redbean#698]
I've been using tags a lot in a new system I'm building and there's a couple of things that I think could do with help from RedBean:

1) Counting tagged items - currently the only way (without recourse to SQL...) to get a count of items with a set of tags is to called taggedAll (or tagged) and do a count() of the resulting array. Sometimes I don't actually want all the beans  and then there is the issue in point 2 below. So R::countTaggedAll(bean, tags) would be nice.

2) Potentially you could have a very large number of tagged beans which could then result in memory issues. It would be nice to have a collection mechanism for tags like there is for beans.

Yes, I could write a SQL for all of these, but that's your job :-)

L.

**Comment by Lynesth** [comment]
Those are nice ideas indeed that shouldn't be hard to implement.

I'll try to find some time to look into it but feel free to create pull requests too :)

**Comment by rivets** [comment]
If I had the time to get grips with the guts of RedBean I would! But sadly not at the moment.

**Comment by rivets** [comment]
But let me also add a

3. Allow ordering of the returned beans from tagged and taggedAll

**Comment by gabordemooij** [comment]
Just implemented R::countTagged() and R::countTaggedAll().

**Comment by gabordemooij** [comment]
https://github.com/gabordemooij/redbean/commit/79b65d3e6ea929809263c80c4e7597c3b1764a03
