### ISSUE TITLE
RedBeanPHP manual on github for editing

### ISSUE THREAD

**Issue by gabordemooij** [gabordemooij/redbean#707]

**Comment by gabordemooij** [comment]
Sorry that it took longer than expected.

The manual will be available soon in a special branch.
Just checking the final version to be shared now...

**Comment by alystair** [comment]
Referencing my comment on #361 once this is ready to go :)

**Comment by gabordemooij** [comment]
Hi all,

As promised the manual has been uploaded to github.
https://github.com/gabordemooij/redbean/blob/manual/redbean_manual.html
Send me pull request if you have contributions.
Please keep your PRs as small as possible.

How it works:

- every category-tag is a new menu section
- every H1 is a new page

Enjoy!

**Comment by alystair** [comment]
Feels weird to have to fork entire code base to edit the manual, what was the thought behind deciding to add it here instead of a separate project?

**Comment by alystair** [comment]
Curious to know the thought process in making it a branch instead as a separate project on github.

**Comment by gabordemooij** [comment]
Just like github pages I guess?
