### ISSUE TITLE
findMulti is a bit slow

### ISSUE THREAD

**Issue by marios88** [gabordemooij/redbean#712]
Trying to use findMulti to preload the parent bean, dataset is around 10k postcodes and 3k stores.  
Sql query time is ~0.0006s uncached  
execution time is ~3s

The culprit (this will run 3000*10000) https://github.com/gabordemooij/redbean/blob/3e151b25b5867a202ef7535d2a294d236b076170/RedBeanPHP/Finder.php#L466-L470

sample code
```
R::findMulti('postcode,store',sqn('postcode>store'),[],[
            [   'a'=>'store',
                'b'=>'postcode',
                'matcher' => function( $a, $b ) {
                    return ( $a->postcode_id == $b->id );
                },
                'do' => function( $a, $b ) {
                    $a->postcode = $b;
                },
            ]
        ]);
```

To get to the question, is there a faster way to implement preloading?

**Comment by Lynesth** [comment]
Hey there,

Not sure what exactly is the use case, but I guess it would be faster to do it out of the function ?
Something like:

```php
$beans = R::findMulti('postcode,store',sqn('postcode>store'));

foreach ($beans['store'] as $store) {
    $store->postcode = $beans['postcode'][$store->postcode_id];
}
```

This is totally untested + really tired so not sure about scope and reference or whatever, but I guess it should work

**Comment by marios88** [comment]
Thanks lynesth,
Well, this definitely does the trick, for some weird reason i insisted on using the finder and didnt think of the the KISS way
