### ISSUE TITLE
Getting null data on R::store in PHP 7.2

### ISSUE THREAD

**Issue by madTeddy** [gabordemooij/redbean#716]
In **PHP 5.6** this code working fine:
```php
function create($tab ,$keys, $values)
{
    $value = R::dispense($tab);
    for ($i = 0; $i < count($keys); $i++) $value -> $keys[$i] = $values[$i];
    R::store($value);
}
```
But in **PHP 7.2** i'm just getting column with **NULL's**. Is there no support for this version of PHP?

**Comment by Lynesth** [comment]
Hi there,

This is not related to RedBeanPHP but to changes in PHP7 regarding the handling of indirect properties (which you can read about [here](https://www.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect)). It should actually have raised some NOTICE in your logs regarding `Array to string conversion`.

Anyway, you can fix this by modifying your function like this to make it work (notice the curly braces around `$keys[$i]`):
```php
function create($tab, $keys, $values) {
    $value = R::dispense($tab);
    for ($i = 0; $i < count($keys); $i++) {
        $value->{$keys[$i]} = $values[$i];
    }
    R::store($value);
}
```

**Comment by madTeddy** [comment]
> Hi there,
> 
> This is not related to RedBeanPHP but to changes in PHP7 regarding the handling of indirect properties (which you can read about [here](https://www.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect)). It should actually have raised some NOTICE in your logs regarding `Array to string conversion`.
> 
> Anyway, you can fix this by modifying your function like this to make it work (notice the curly braces around `$keys[$i]`):
> 
> ```
> function create($tab, $keys, $values) {
>     $value = R::dispense($tab);
>     for ($i = 0; $i < count($keys); $i++) {
>         $value->{$keys[$i]} = $values[$i];
>     }
>     R::store($value);
> }
> ```

Oh, thanks 👍
