### ISSUE TITLE
Poll: would you like SQN to be part of RedBeanPHP?

### ISSUE THREAD

**Issue by gabordemooij** [gabordemooij/redbean#717]
http://gabordemooij.com/sqn/

**Comment by Lynesth** [comment]
I don't use it to be honest.

Since it is something pretty different than RedBean, I don't think it really belongs in it. And people may already be using another query builder. It's only one function so it's pretty easy to include already.

My vote would be no then :)

**Comment by marios88** [comment]
Really a timesaver when used with `R::findMulti`
but since its not core to redbean i am leaning on no.

*It would be really nice to have it on composer (git submodules are a real pain)

**Comment by gabordemooij** [comment]
I'll give this one another look.
It's a tiny piece of code, maintaining it as a separate project is too much of hassle for me.

**Comment by Lynesth** [comment]
I understand where you're coming from but I'll give you my two cents on this matter.

It really is a different project and it already has its own repo. Plus it seems robust enough that you didn't commit anything for the last 6 months. So why would you want to merge it in RedBean ?

And as you said yourself:
> we don't use a fancy query builder, just good old SQL. We like to keep things simple.

**Comment by jreklund** [comment]
I would leave it out. I prefer writing my own queries. rather than learning a new syntax.

**Comment by gabordemooij** [comment]
I seem to be contradicting myself....
