### ISSUE TITLE
Q: Correct approach to 'lock' a bean from findOne?

### ISSUE THREAD

**Issue by alystair** [gabordemooij/redbean#722]
Two questions (these will also help me write some more documentation):
I noticed the documentation shows a `loadForUpdate` function that locks the bean in question - however what is the correct approach to lock a bean when found using `findOne`?

Current situation: Users enter instant contest and wins a prize, however I noticed in some race conditions the same prize could be 'won' by multiple users if they both triggered the winnings near simultaneously.

```
if ($winner) {
   $prize = R::findOne('prize','project = ? AND used IS NULL',['Test Project']);
   $prize->used = date_create();

   ... give prize to user (and other anti-abuse stuff here) ...

   R::store($prize);
}
```

In this situation, would all I have to do is something akin to `$prize = loadForUpdate($prize);` or am I misunderstanding what locking would do (eg. it becomes read only, and still appears via findOne)

**Comment by gabordemooij** [comment]
loadForUpdate will execute a SELECT FOR UPDATE query. This means the record will still be found but it cannot be updated before your transaction completes.

For more details:
https://stackoverflow.com/questions/8849518/mysql-select-for-update-behaviour

**Comment by alystair** [comment]
So the correct approach would be to add `$prize = loadForUpdate($prize)` after findOne to lock it? Maybe adding a try/catch...

**Comment by gabordemooij** [comment]
Maybe we could combine find-and-loadForUpdate somehow in the facade with a convenience function....

**Comment by alystair** [comment]
In the meantime the method I described is the correct approach?

**Comment by gabordemooij** [comment]
No, to lock and load a bean use:
$bean = R::loadForUpdate( 'bean', $id );
(it's a different query)

**Comment by Lynesth** [comment]
@alystair 
You currently should be able to do it like this (untested):
```php
R::getWriter()->setSQLSelectSnippet('FOR UPDATE');
$prize = R::findOne('prize','project = ? AND used IS NULL',['Test Project']);
```

**Comment by gabordemooij** [comment]
This is indeed already possible and quite good.

**Comment by Lynesth** [comment]
@gabordemooij I guess we could add a `R::findForUpdate` function since we've got the `R::loadForUpdate` one don't you think ?

**Comment by gabordemooij** [comment]
Yes, we could do that.

**Comment by alystair** [comment]
Thanks for keeping an open mind for this common use case. Hopefully I'll have time to contribute to the manual if/once implemented.

**Comment by gabordemooij** [comment]
- Added R::findForUpdate
- Fixed an issue with cache for -forUpdate() methods
- Added $writer->clearCache() to manually flush cache if needed (was needed for fix)
- Added unit tests in Base/Concurrency test

https://github.com/gabordemooij/redbean/commit/39af9af786f60bf1325fa175d70ade09a9300390
