### ISSUE TITLE
adhere to return type specification for R::getRow

### ISSUE THREAD

**Issue by nucc1** [gabordemooij/redbean#728]
`public static function getRow` is documented as a function that returns an array. However, in a situation where the resultset is empty, this returns a boolean and causes an unexpected failure in code like this because it is expecting an array: 

```
$res = R::getRow($sql,[
            ":param1" => $p1,
            ':param2' => $p2
        ]);


        if (count($res) > 0 ) { //value exists
```
Since the empty array evaluates to false in comparisons, it is more consistent to return an empty array `[]` instead of `false` when the result set is empty.

```
php > $a = [];
php > if ($a) { echo "true"; } else { echo "false"; }
false
php >
```

**Comment by gabordemooij** [comment]
Thank you for reporting this. I will work on this issue.
