### ISSUE TITLE
Specify properties to ignore with export()

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#739]
The `export()` function of a bean is extremely useful, especially when using RedBean to build APIs. 

However, sometimes we need to omit specific fields from the exported bean. I know that we can do this as follows:

```
$json = $myBean->export();

unset($json['user_id']);
unset($json['password']);
...
```

But this is cumbersome when working with large data. It would be much more useful to allow us to specify fields to be ignored directly when we call `export()`. For example, the following would be the equivalent of the above:

`$json = $myBean->export([ 'user_id', 'password' ]);`

Of course, this isn't a bug, more of a topic of discussion for the community and lead devs.

**Comment by gabordemooij** [comment]
Thank you, we're going to look into this.

**Comment by Lynesth** [comment]
Hey there @benmajor 

There's indeed no way to do this with RedBean currently and I'm not sure there will be.
At least I don't want to work on that unless @gabordemooij finally agrees to break BC for an upcoming v6 ;)
That function already accepts many parameters, so adding some more or using features sets again doesn't feel right to me.

All I can advise for now is to do something like this:
```php
$json = array_diff_key($myBean->export(), array_flip([ 'user_id', 'password' ]));
```

**Comment by benmajor** [comment]
Thanks @gabordemooij. Yes, I know that I can use the `array_diff_key` method, it's just a bit cumbersome and would be handy to have it OOB in RB. 

Do you have a list of parameters that `export()` accepts, as I can't find them in the docs, and it may answer my next question:

`export()` seems to flatten the bean down to the individual record, rather than the bean's own structure. In the example I posted above, `$myBean` has another bean assigned to the `user` property. When calling `export`, I just get `user_id`, not a flattened structure of `user`. It would be extremely handy if `export()` could not flatten the bean.

**Comment by marios88** [comment]
@benmajor 

> export() seems to flatten the bean down to the individual record

Take a look at `R::exportAll`

**Comment by benmajor** [comment]
@marios88  `R::exportAll` has some weird behavior. For example:

R::exportAll( $collection );

Produces the following JSON structure:

```
{
    "id": 2,
    "name": "Test Category",
    "description": "sdfsdfsdfsdfsdfsdfsdfsdf",
    "created": "2019-07-30 08:30:37",
    "modified": "2019-07-30 08:30:37",
    "organization": null,
    "user_id": 1,
    "url": "test-category",
    "ownCategory": [
        {
            "id": 1,
            "name": "Test Category",
            "description": "sdfsdf.sdf.sdfsdfs.dfsdf.sdfsdf",
            "url": "test-category",
            "parent": null,
            "created": "2019-07-30 08:31:27",
            "modified": "2019-07-30 08:31:27",
            "organization": null,
            "collection_id": 2,
            "user_id": 1
        }
    ]
}
```

Notice how the `user` property (which contains a `user` bean) has been flattended, while `ownCategory` is exported correctly (although the same issue with `user` not being expanded).

**Comment by Lynesth** [comment]
@benmajor 
Sure thing, [there you go](https://redbeanphp.com/api/classes/RedBeanPHP.OODBBean.html#method_export)

**Please notice the following:**
`$filters` only filters related beans, not properties (so you cannot use it for what you want)
Also, `$filters` is a whitelist, so the example saying that it will not retrieve 'author' beans is wrong. It is quite the opposite.

**Comment by Lynesth** [comment]
My previous comment is the reason I don't want to work on this function :)

**Comment by marios88** [comment]
Lynesth covered it, use `R::exportAll( $collection, true );`

On a similar situation ( https://github.com/gabordemooij/redbean/issues/712 ) i ended up using `R::findMulti` cause `R::exportAll` is too slow, but its really handy for prototyping

**Comment by Lynesth** [comment]
I had to review and correct my comment about `export()` multiple times because I messed up but I think it is now describing the correct behavior.

Regarding exportAll, it works almost the same way:
- It will first retrieve own/shared lists from the database for all the beans you want to export and for all their own beans too (not for the shared ones) recursively.
- It will then call `export()` (yes the one I previously explained) on each "1st level" bean with the following arguments: `$meta = FALSE, $parents = TRUE, $onlyMe = FALSE, $filters = $filters`

**Comment by benmajor** [comment]
Okay, I think looking at the functionality performed by `export()` and `exportAll()`, adding the ability that I suggested in the initial post here doesn't make too much sense. I think the circumstances for being able to remove specific properties. I'll go ahead and close this, as using `array_diff_key` is a workable solution that's a bit cleaner than consecutive `unset()` calls.
