### ISSUE TITLE
Better understanding / documentation of Trees

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#740]
Perhaps I'm being a little slow here (it's been a busy few weeks), but I'm trying to better understand Trees within RedBean. The manual describes them as essentially self-referential relationships, but the single example in the online docs is convoluted in my opinion.

Consider the following structure, which comprises Category beans:

```
Parent Category 1
  - Child Category 1
  - Child Category 2
    - Grandchild Category 1
      - Grand-grandchild Category 1
      - Grand-grandchild Category 2
    - Grandchild Category 2
  - Child Category 3
Parent Category 2
```

Where the depth of nested Category beans is `n`. 

Typically, without the use of an ORM we would have to define the `parent_id` of each Category, and write an interator to handle any handling of the data. However, it seems that RedBean's Tree structure should be able to handle this, but I cannot figure out how to get it working so that I'm able to us` traverse` on the parent Category bean as follows:

```
$parent->traverse('ownCategory', function($child) {  });
```

Perhaps the docs are unclear, or maybe I'm misunderstanding, but any input would be welcome.

**Comment by Lynesth** [comment]
Let's say all the categories in your example are beans of type `category` that are already assigned to variables but they are not linked yet. Let's do it:
```php
$parentCategory->ownCategory = [ $childCategory1, $childCategory2, $childCategory3 ];
$childCategory2->ownCategory = [ $grandChildCategory1, $grandChildCategory2 ];
$grandChildCategory1->ownCategory = [ $grandGrandChildCategory1, $grandGrandChildCategory2 ];
```
For the example let's say they have a property called `name`. Here is how you can use the `traverse` function:
```php
$parentCategory->traverse('ownCategory', function($child) {
    print $child->name;
});
```
This will output the following:
```
Child Category 1
Child Category 2
Grandchild Category 1
Grand-grandchild Category 1
Grand-grandchild Category 2
Grandchild Category 2
Child Category 3
```
You can set a maxDepth:
```php
$parentCategory->traverse('ownCategory', function($child) {
    print $child->name;
}, 1); // <---- It is here
```
This would output:
```
Child Category 1
Child Category 2
Child Category 3
```
Let's say they also have a `active` property that is a boolean and you only want to traverse the active ones. You can do it like this:
```php
$parentCategory->withCondition(' active = ? ', [ 1 ])->traverse('ownCategory', function($child) {
    print $child->name;
});
```
-------------
Was that clear enough ? Maybe I did not understand your question, let me know.

**Comment by benmajor** [comment]
Yes, that's perfect! Thanks @Lynesth.

**Comment by benmajor** [comment]
Am I right to assume this is the correct way to add a child to an existing bean?

```
# Are we adding a parent?
if( ! is_null($parent) )
{
    $parent->ownCategory[] = [ $category ];
    R::store($parent);
}
```

**Comment by benmajor** [comment]
The reason I ask for clarification, is because when I run this:

```
# Everything's okay here, so now try to create the Collection:
$bean = [
    '_type' => 'category',
    
    'name'         => $name,
    'description'  => ucfirst($description),
    'url'          => \URLify::filter($name),
    'created'      => R::isoDateTime(),
    'modified'     => R::isoDateTime(),
    'user'         => $this->user,
    'organization' => null
];

# Are we specifying a collection?
if( ! is_null($collection) )
{
    $bean['collection'] = $collection;
}

$category = R::dispense($bean);

$id = R::store($category);

# Are we adding a parent?
if( ! is_null($parent) )
{
    $parent->ownCategory[] = [ $category ];
    R::store($parent);
}
```

I get the following exception:

> Type: RedBeanPHP\RedException
> Message: Array may only contain OODBBeans
> File: C:\...\RedBeanPHP\Repository\Fluid.php
> Line: 186

**Comment by marios88** [comment]
$parent->ownCategory[] = $category;

**Comment by Lynesth** [comment]
Yes as @marios88 pointed out, you were adding an array to your array instead of just a bean.
So `$parent->ownCategory[] = $category;` is the way to go.

Note that if you just want to add elements to an ownList but don't have anything else to do with it (ie. remove something), you could use the `noLoad` to prevent fetching everything from the database:
`$parent->noLoad()->ownCategory[] = $category;`

**Comment by gabordemooij** [comment]
@benmajor  @Lynesth @marios88 Just for the sake of curiosity anyone tried R::children()/R::parents() yet? Those functions use CTE functionality if available for the database and might have better performance.

**Comment by Lynesth** [comment]
@gabordemooij Never used any of the tree functions. Sorry :)

**Comment by marios88** [comment]
@gabordemooij never tried them, i run a test to see the functionality but got an error on `10.3.15-MariaDB`
```
$p = \R::load('users',1);
var_dump(\R::children($p,''));
```
```
WITH RECURSIVE tree AS
(
SELECT *
FROM users WHERE users.id = ?
UNION ALL
SELECT users.* FROM users
INNER JOIN tree child ON  child.id = users.users_id
)
SELECT * FROM tree ;
```
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.users_id' in 'on clause'
```

**Comment by benmajor** [comment]
@gabordemooij I have never run RedBean with a DB engine that supports CTE, so I haven't been able to try them out yet unfortunately.

**Comment by gabordemooij** [comment]
@marios88 can you run the same command without the empty second parameter (that is meant for additional sql).

**Comment by marios88** [comment]
@gabordemooij 
Sorry my bad, i read the function comments
https://github.com/gabordemooij/redbean/blob/bcfde2f088a949967353796e8bb5a983764308df/RedBeanPHP/Facade.php#L3001
and I wrongly assumed by the naming that it will return **all** children/parents. 

it needs `$p->ownUsersList` for this to work ( thats something my database doesnt have, hence the error! )
