### ISSUE TITLE
findone issue with varchar string

### ISSUE THREAD

**Issue by renieravin** [gabordemooij/redbean#741]
When I run any of these queries:

```
R::findOne( 'user',' guid = ? ', [ '8' ] );
R::findOne( 'user',' guid = ? ', [ 8 ] );
```

It returns the user with guid 8f860f0a-dd41-4a35-94d4-5f0032846118. Is this expected behaviour?

Running `R::findOne( 'user',' guid = ? ', [ '8f' ] );` returns null as expected.

It looks like this happens only when a varchar column starts with an integer.

**Comment by benmajor** [comment]
I've just tried this and can confirm it's happening for me, too.

**Comment by benmajor** [comment]
For what it's worth, the same happens with `R::find()`:

```php
R::find('user', 'guid = ?', [ 8 ]);    # Returns a single element in the array
R::find('user', 'guid = ?', [ '8f' ]); # Returns an empty array
```

**Comment by benmajor** [comment]
Actually, running the query itself directly against the DB in MySQL produces the same result:

```
SELECT * FROM `user` WHERE `guid` = 8;
```

**Comment by Lynesth** [comment]
@benmajor pretty much explained the behavior you are facing.

You can read issue https://github.com/gabordemooij/redbean/issues/700 for more information.
And as I said in that issue:
> In RedBean, if the parameter can be treated as an int, the pdo function bindParam will be called with the PARAM_INT option, which will remove quotes around integers.
> 
> You can bypass this by setting R::getDatabaseAdapter()->getDatabase()->setUseStringOnlyBinding(true); before that query (and setting it back to false after that).
> 
> This will force all bound parameters to be surrounded by single quotes (which will still work for integers).
> I do not recommend keeping this on, for implicit casting and performance issues.

**Comment by renieravin** [comment]
I'm sorry, I saw #700 earlier but didn't realize it was connected to this. Thank you @benmajor and @Lynesth for the super quick replies and resolution.
