### ISSUE TITLE
Add depth parameter to traverse() callback

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#742]
Further to my query about Trees (https://github.com/gabordemooij/redbean/issues/740), it would be extremely handy to be able to retrieve the current working depth inside the callback function.

For example (oversimplified):

```php
$this->bean->traverse('ownCategory', function($child, $level) {
  echo str_repeat("\t", $level).$level.$child->name."\n";
});
```

Is this something that could be added?

**Comment by Lynesth** [comment]
@benmajor Can you try #743 ?

**Comment by benmajor** [comment]
@Lynesth yep, works a treat! Great work adding this, I really think it could be a useful addition to 5.4.

**Comment by gabordemooij** [comment]
Merged. Will be availabe in version 5.4.
