### ISSUE TITLE
When using R :: find to obtain an array of data, empty keys are generated.

### ISSUE THREAD

**Issue by DeltaVetal26** [gabordemooij/redbean#744]
Hi,

I am trying to get an array of items from a database:
```php
$session_list = R::find('session', ' panel_id LIKE ? ', array($panel_id) );
$session_count = count($session_list);
echo $session_count;
```

$session_count returns 3, which indicates that 3 elements were found with this value in the table, which is true.

Next, I want to use this number to work with the while loop, where I will iterate over the keys from the $session_list array.

The problem is that the key numbers will not be 1,2,3. And it can be 1, 10, 23. It depends on the location of the element in the table. Idea:

```php
$a = 0;
 while($a < $session_counter) {
    $data = $session_list[$session_counter];
    $session_counter++;
 }
```

It does not work, since the keys with the received data do not coincide with 1, 2, 3, and if I turn to the key # 3, for example, it will give an empty answer, since the data lies somewhere further. How can this be fixed?

My goal is to:
1) Unload the array from the database
2) Calculate the number of elements in the array.
3) Get data by sorting keys.

Example: number of elements in an array: 6
The data will be: array [1], array [2], .... array [6]

Best regards,
Alex

**Comment by Lynesth** [comment]
Hi @DeltaVetal26 
When retrieving multiple beans at the same time like you did, the array is indexed with the ids of those beans, that's why it will not be continuous.

Now I'm not sure I really understood your issue but I'll give it a try.

If you want to loop over the array you can use a foreach:
```php
// Using the same variables you already declared
foreach ($session_list as $id => $data) {
    // Do your thing
}
```

If you really want to work with the number of elements in the array, use a for loop:
```php
// Using the same variables you already declared
for ($session_counter = 0; $session_counter < $session_count; $session_counter++) {
    // Do your thing
}
```

**Comment by marios88** [comment]
As @Lynesth pointed out `foreach` is the way to go.

Depending on what the rest of the code does you could also rekey the array
```
$a = 0;
$session_list = array_values($session_list);
 while($a < $session_counter) {
    $data = $session_list[$session_counter];
    $session_counter++;
 }
```

**Comment by DeltaVetal26** [comment]
Hi @Lynesth , @marios88 

**foreach() {}** solved my problem, now it works.

The option of overriding the array will also be useful to me in my project.

Thank you for the help!
