### ISSUE TITLE
Should countOwn produce an SQL exception when trying to count a table that doesn't exist yet?

### ISSUE THREAD

**Issue by krisives** [gabordemooij/redbean#745]
When using `countOwn()` on a bean for a table that has not yet been created, usually when a webapp is freshly installed, should it produce an SQL exception? Most parts of RedBean ignore such "scaffolding" errors, but `countOwn` seems not to.

**Comment by krisives** [comment]
Example in SQLIte doing:

     $account->countOwn('post')

Yields:

     SQLSTATE[HY000]: General error: 1 no such table: post

**Comment by krisives** [comment]
Thank you Gabor, you're a legend.

**Comment by gabordemooij** [comment]
Thanks ;-)
Note that in order to use this patch you need either:

`OODBBean::useFluidCount(TRUE)`

or use the latest feature set:

`R::useFeatureSet( 'novice/latest' );`

cheers,
Gabor
