### ISSUE TITLE
Cannot override export() method on bean

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#746]
When using RedBean with Composer and working with models, we have to extend `\RedBeanPHP\SimpleModel` as follows:

```
<?php

use \RedBeanPHP\R;

class Model_County extends \RedBeanPHP\SimpleModel
{
    public function hello()
    {
        return 'hello';
    }
    
    public final function export()
    {
        return 'does not work';
    }
}

```
Notice that in the above code, I am attempting to override the default `export()` method of a Bean. This doesn't work, and simply returns the Bean as an array. 

For example:

```
<?php

$bean->export();
```

Expected result:

'does not work'

Actual result:

```
array (size=4)
  'id' => string '1' (length=1)
  'name' => string 'Autauga' (length=7)
  'code' => string '001' (length=3)
  'state_id' => string '1' (length=1)
```

Is this a bug, or a design flaw in RedBean?

**Comment by benmajor** [comment]
After some investigation, it appears that this is because `export()` is a method on `OODBBean`, not `SimpleModel`. As a result, I don't think there's a workaround for this?

**Comment by gabordemooij** [comment]
The export() method is indeed part of the bean and not of the Fused model. You could box the bean of course: $bean->box(). Why would you like to override the export() method? We could allow to dispense 'different' kind of beans.

**Comment by benmajor** [comment]
Thanks Gabor.

I use RedBean a lot to build APIs in combination with Slim3. I am returning JSON data to the API based on beans. However, sometimes I would like to rename properties of beans, or manipulate the data before outputting. It would be better to handle this on the model, rather than in the controller of course. I am could just create a new method (something like `toJSON`), but it would be handy to override `export()` in some instances. 

For example, this is the result I get when using `$bean->export()` on a specific county:

```
{
    "id": 1,
    "name": "Autauga",
    "code": 1,
    "state_id": 1
}
```

Notice that `state_id` is a foreign key to `state`. What I'd like to achieve by using `export()` is something like the following:

```
{
    "id": 1,
    "name": "Autauga",
    "code": 1,
    "state": {
        "id": 1,
        "name": "State name"
    }
}
```

I cannot use `R::exportAll()` because that just generates an array as follows:

[
    {
        "id": 1,
        "name": "Autauga",
        "code": 1,
        "state_id": 1
    }
]

So essentially what I would like to do is override `export()` to manipulate the output to include the child bean of `state`. As I said, I can always create a new method on the County model called `toJSON()` or similar but in my opinion it would be better to add `export()` to the fused methods. Here's how we might use an override `export()` method:

```
public final function export()
{
    $json = $this->bean->export();
    unset($json['state_id']);

    $json['state'] =$this->bean->state->export();

    return $json;
}
```

**Comment by gabordemooij** [comment]
Okay, well one option you have is to extend the Bean class: OODBBean.
You can then tell RedBeanPHP to dispense your extended bean instead of the default bean:
define('REDBEAN_OODBBEAN_CLASS', '\MyBean');

**Comment by benmajor** [comment]
Okay, thanks. Are there any plans to add `export()` to the list of fused methods? I think it'd be a great addition to library.

**Comment by Lynesth** [comment]
Hi @benmajor 
The `export` function is used in many places internally by RedBean so it cannot be overriden.
Nevertheless, you can define a `__jsonSerialize` method on the model and then use `json_encode()` on the bean if you want, this should work.

**Comment by benmajor** [comment]
Okay, thanks for the advice, @Lynesth. It's not a massive deal to be honest, I can always just define another method.
