### ISSUE TITLE
An error when run the test case called testAutoClearHistory

### ISSUE THREAD

**Issue by AlexanderYIXIAO** [gabordemooij/redbean#752]
There is an error when I run the tests by executing ./run_all_tests.sh. And I follow the process of the code. I found that the test case before testAutoClearHistory is testPartialBeansAtSetup. This test case changed R::$currentDB but not changed it back. So I did a little modification to make the whole tests working. But I do not know how to push my branch to your repository. Do I need some permissions?

Below is the error information.

    Testpack: RedUNIT\Base\Misc

    ===== DRIVER : (mysql) =====

            RedUNIT\Base\Misc->testReferencedGetInBeans [RedUNIT\Base\Misc->testReferencedGetInBeans]
            [6546][6547][6548]

            RedUNIT\Base\Misc->testPartialBeansAtSetup [RedUNIT\Base\Misc->testPartialBeansAtSetup]
            [6549]

            RedUNIT\Base\Misc->testAutoClearHistory [RedUNIT\Base\Misc->testAutoClearHistory]

            Sub testpack: Auto clear history

    Fatal error: Uncaught PDOException: Could not connect to database (?). in /myprojectpath/vendor/gabordemooij/redbean/testing/cli/testcontainer/rb.php on line 1011

    PDOException: Could not connect to database (?). in /myprojectpath/vendor/gabordemooij/redbean/testing/cli/testcontainer/rb.php on line 1011

    Call Stack:
        0.0003     410312   1. {main}() /myprojectpath/vendor/gabordemooij/redbean/testing/cli/runtests.php:0
       84.4031   11896992   2. RedUNIT\Base\Misc->run() /myprojectpath/vendor/gabordemooij/redbean/testing/cli/runtests.php:275
       84.4097   11916048   3. RedUNIT\Base\Misc->testAutoClearHistory() /myprojectpath/vendor/gabordemooij/redbean/testing/RedUNIT.php:82
       84.4110   11917424   4. RedBeanPHP\Facade::store() /myprojectpath/vendor/gabordemooij/redbean/testing/RedUNIT/Base/Misc.php:97
       84.4110   11917424   5. RedBeanPHP\OODB->store() /myprojectpath/vendor/gabordemooij/redbean/testing/cli/testcontainer/rb.php:12443
       84.4110   11917424   6. RedBeanPHP\Repository\Fluid->store() /myprojectpath/vendor/gabordemooij/redbean/testing/cli/testcontainer/rb.php:9887
       84.4112   11917424   7. RedBeanPHP\Repository\Fluid->storeBean() /myprojectpath/vendor/gabordemooij/redbean/testing/cli/testcontainer/rb.php:8738
       84.4113   11917424   8. RedBeanPHP\Repository\Fluid->createTableIfNotExists() /myprojectpath/vendor/gabordemooij/redbean/testing/cli/testcontainer/rb.php:9146
       84.4114   11917424   9. RedBeanPHP\Repository\Fluid->tableExists() /myprojectpath/vendor/gabordemooij/redbean/testing/cli/testcontainer/rb.php:9014
       84.4114   11917424  10. RedBeanPHP\QueryWriter\SQLiteT->tableExists() /myprojectpath/vendor/gabordemooij/redbean/testing/cli/testcontainer/rb.php:8912
       84.4114   11917424  11. RedBeanPHP\QueryWriter\SQLiteT->getTables() /myprojectpath/vendor/gabordemooij/redbean/testing/cli/testcontainer/rb.php:5857
       84.4114   11917424  12. RedBeanPHP\Adapter\DBAdapter->getCol() /myprojectpath/vendor/gabordemooij/redbean/testing/cli/testcontainer/rb.php:7232
       84.4115   11917424  13. RedBeanPHP\Driver\RPDO->GetCol() /myprojectpath/vendor/gabordemooij/redbean/testing/cli/testcontainer/rb.php:4183
       84.4115   11917424  14. RedBeanPHP\Driver\RPDO->GetAll() /myprojectpath/vendor/gabordemooij/redbean/testing/cli/testcontainer/rb.php:1056
       84.4115   11917424  15. RedBeanPHP\Driver\RPDO->runQuery() /myprojectpath/vendor/gabordemooij/redbean/testing/cli/testcontainer/rb.php:1035
       84.4115   11917424  16. RedBeanPHP\Driver\RPDO->connect() /myprojectpath/vendor/gabordemooij/redbean/testing/cli/testcontainer/rb.php:735

Below is my code.

	public static $setupPartialBeansTestDone = 0;
	/**
	 * Check partial beans at setup()
	 */
	 public function testPartialBeansAtSetup()
	 {
		 if (self::$setupPartialBeansTestDone) return; /* only needs to be tested once */
		 $currentDB = R::$currentDB;
		 $key  = 'partialBeanBase' . time();
		 $dsn  = 'sqlite:/tmp/test.txt';
		 $user = '';
		 $pass = '';
		 $frozen = FALSE;
		 $partialBeans = TRUE;
		 R::addDatabase( $key, $dsn, $user, $pass, $frozen, $partialBeans);
		 $redbean = R::getRedBean();
		 $wasItSet = $redbean->getCurrentRepository()->usePartialBeans( FALSE );
		 R::selectDatabase( $key );
		 $redbean = R::getRedBean();
		 $wasItSet = $redbean->getCurrentRepository()->usePartialBeans( FALSE );
		 asrt( $wasItSet, TRUE );
		 self::$setupPartialBeansTestDone = 1;
		 R::selectDatabase( $currentDB );
	 }

**Comment by gabordemooij** [comment]
Hi there,

Thanks for reporting this. Strange that Travis CI does not has an issue with this (https://travis-ci.org/gabordemooij/redbean/jobs/602409996 nor me locally), but anyway, feel free to create a pull request (fork the repository first, push your change, then submit PR). We'll look into it!

cheers
Gabor

**Comment by AlexanderYIXIAO** [comment]
> Hi there,
> 
> Thanks for reporting this. Strange that Travis CI does not has an issue with this (https://travis-ci.org/gabordemooij/redbean/jobs/602409996 nor me locally), but anyway, feel free to create a pull request (fork the repository first, push your change, then submit PR). We'll look into it!
> 
> cheers
> Gabor

PR is here. https://github.com/gabordemooij/redbean/pull/753
