### ISSUE TITLE
Inconsistent handling of booleans

### ISSUE THREAD

**Issue by Jemt** [gabordemooij/redbean#756]
Hi,

Creating a new bean and assigning a boolean value to a field results in this value being converted to either "1" or "0", despite having set stringifyFetches(false)

```
$bean = R::dispense("person");
$bean["coffeelover"] = true;
var_dump($bean["coffeelover"]); // Emits "1" - a string
```

While the name does imply that the behaviour only affect fetched data, it's confusing.

When I load the entry, the boolean value is represented by either 0 or 1.

```
$bean = R::loadOne("person"); // There is only one record
var_dump($bean["coffeelover"]); // Emits 1 - an int
```

But I would much rather have data types preserved (true or false).

Is the current implementation "by design"?

By the way; I love this ORM - it has made me much more productive - thank you! :-)

**Comment by gabordemooij** [comment]
Hi there,

Good to hear you like the ORM ;-)
RedBeanPHP makes use of the dynamic nature of types in PHP, this is by design.

cheers,
Gabor

**Comment by Jemt** [comment]
Alright - thanks for replying back :-)

**Comment by alystair** [comment]
I actually got caught by this by trying to do some optimization like `if ($user->emailVerified === true)`, which of course didn't work. Oops :D
