### ISSUE TITLE
ConvertToBean does not play well with getRow

### ISSUE THREAD

**Issue by flip111** [gabordemooij/redbean#758]
When no results are found for `getRow` it returns `[]` in my opinion it should return `null` because i think `[]` is a single row without any properties. Anyway .. this is not the main problem ... so to continue ...

Then when you give that to `convertToBean` it wraps your single row into an array of multiple rows, so you get `[[]]`.

Then this loop has something to iterate on https://github.com/gabordemooij/redbean/blob/d1491a6ba5d8b5d7c2171e575101e53ecb17976a/RedBeanPHP/Repository.php#L591

And then it crashes here https://github.com/gabordemooij/redbean/blob/d1491a6ba5d8b5d7c2171e575101e53ecb17976a/RedBeanPHP/Repository.php#L602

**Comment by gabordemooij** [comment]
Thank you for reporting this. We are going to look into this issue.

**Comment by gabordemooij** [comment]
getRow() always returns an array, this is useful so you can always use a foreach-loop. (https://github.com/gabordemooij/redbean/issues/728)

But you are correct that convertToBean() should be more graceful.
However I am a bit on the fence whether we should return null here or a newly dispensed bean maybe?

**Comment by flip111** [comment]
Ok if https://github.com/gabordemooij/redbean/issues/728 is needed to be it. I just find it a very strange use case ... because it counts the amount of columns (or cells because it's a single row). When is this even relevant code? Normally you know how many columns are in your database table.

As for what to return on an empty query, you could argue that the programmer always wants to create a new bean after an empty query and therefor it's useful to return a fresh one for convenience. On the other hand i don't think this `always` will apply and letting the programmer create a new bean him/herself allows for more control. Also in the case when the bean is not needed it saves the creation of an unnecessary object

**Comment by gabordemooij** [comment]
Okay, fix has been applied, also a test.

**Comment by flip111** [comment]
Thank you :)
