### ISSUE TITLE
Weird behaviour with bean with 3 letter name

### ISSUE THREAD

**Issue by rivets** [gabordemooij/redbean#760]
A student created a bean called "fav" with a model. In the model of another bean she returned the value of $this->bean->ownFav

This definitely returned an array of beans that were of type "fav", but the Model field was not filled in and the model functions could not be called from inside a Twig. When we returned the result of an equivalent find to the ownFav the model was found and when we renamed the bean to be "favour" it also worked. I don't know if there is some strange interaction with Twig involved here or what but there is definitely something odd going on.

**Comment by Lynesth** [comment]
This is interesting.
Could you provide some code to be able to replicate the issue ?

**Comment by rivets** [comment]
Bit tricky as it's all embedded in a website development framework of mine that my students use.

Basically the student had a bean called fav with two fields user_id and note_id which were foreign keyed back to the related tables. 

The user bean had in its model a function called favourites that was simply

public function favourites() [ return $this->bean->ownFav; }

The fav has a model with one method:

public function note() { return $this->bean->note; }

In the twig file we had twig code like:

{% for fav in user.favourites %}
    <p>{{fav.note.title}}</p>
{% endfor %}

when you dump the fav bean the model field is NULL.  But if you replace the favourites function with

public function favourites() [ return \R::find('fav', 'user_id=?', [$this->bean->getID()]); }

it works and the model is not NULL. Changing the name of the bean to be favour rather than fav and using the favourites function:

public function favourites() [ return $this->bean->ownFavour; }

It also works. Very strange. I will try and replicate it fully later but am currently madly busy.

**Comment by gabordemooij** [comment]
With the information available so far, I cannot seem to reproduce this issue? Might be a hidden feature in Twig maybe?

![afbeelding](https://user-images.githubusercontent.com/89826/71101787-97ef5e00-21b7-11ea-89f7-0e79e03cf965.png)

**Comment by marios88** [comment]
I dont know why but i had the same problem, probably the way Twig works

Using `__get()` works for me
```
{% for item in user.__get('ownPageList') %}
  {{item.title}}
{% endfor %}
```

**Comment by Lynesth** [comment]
Okay so here is what it seems is happening.

Lists are not loaded by default, so if that's the first time you are trying to access it, RedBean will try to load them. It makes use of the magic `__get` function.

For it to work with Twig, we would need to declare a magic `__isset` function on the bean as well. Source: https://twig.symfony.com/doc/3.x/recipes.html#using-dynamic-object-properties

^ @gabordemooij @marios88 @rivets
