### ISSUE TITLE
Main site - Unavailable videos

### ISSUE THREAD

**Issue by magikstm** [gabordemooij/redbean#763]
The following videos on the main site aren't available anymore:
https://www.youtube.com/watch?v=aNISC_-Dhlk
https://www.youtube.com/watch?v=rIWfb6nihGA
https://www.youtube.com/watch?v=7NRAsvl3qDA&t=221s
https://www.youtube.com/watch?v=WPbplKryjOo

Page: https://redbeanphp.com/index.php?p=/videos

I think they should be removed.

**Comment by gabordemooij** [comment]
Thanks for reporting this.
The videos should have been removed by now.
