### ISSUE TITLE
Most efficient way to search an ownList

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#764]
I have a need to search an ownList property of bean (it's basically for user logins, to ascertain if the system has already seen the device before). At the moment, to achieve this I am using `findOne()` as follows:

```php
$login = R::findOne(
  'login', 
  'user_id = ? AND ip_address = ? AND user_agent = ?', 
  [ $user->id, $_SERVER['REMOTE_ADDR'], $_SERVER['HTTP_USER_AGENT'] ]
);
```

However, this seems to be expensive, especially considering that we already have access to all of the `login` beans of `$user` available. Is there a way for us to search the `ownLoginList` of `$user` (i.e. looking for specific values to `ip_address` and `user_agent`) without having to loop over the list?

**Comment by Lynesth** [comment]
If you didn't load the list beforehand then using `findOne` (or even simplier, a `getRow`) would be the best solution.

If you already loaded the list beforehand, then there's nothing that will be faster looping over the list just once in search of what you need.

Now another solution, not sure of its much faster than a simple loop especially if searching only once, would be to have a model for `login` beans and to have a class variable array in which you'd store the ip/ua already used when the beans are loaded.

Something like this (kinda pseudocode):

```php
class Model_Login extends RedBean_SimpleModel {
    public static logins = [];

    # Redbean hook
    public function open() {
        $identifier = $this->bean->ip_address . "-" . $this->bean->user_agent;
        self::$logins[$identifier] = true;
    }
}

# Then later on, you can simply check that the key isset:

$identifier = $_SERVER['REMOTE_ADDR'] . "-" . $_SERVER['HTTP_USER_AGENT'];
if (isset(Model_Login::$logins[$identifiers])) {
    # This is a known device !
} else {
    # Alert, it isn't !
}
```

**Comment by benmajor** [comment]
Okay, thanks Lynesth. I will just loop through the list as I think it's going to be the most efficient for what I need. I just wasn't sure if there was a more suited way in Redbean to filter a list.

I'll go ahead and close this now.
