### ISSUE TITLE
Output data from the database to a table

### ISSUE THREAD

**Issue by ApTemkA73** [gabordemooij/redbean#766]
Table "links" with content
![Screenshot_32](https://user-images.githubusercontent.com/37661593/72238088-32e02a00-35f6-11ea-902d-c91d64dcd610.png)
You need to output the data "link_in" and "link_out" to the table where user_id = 3
Doing:
`$id = 3;
							$searсh_link = R::exec('select link_in, link_out from links where id_user = ?', [
								$id
								]);
								echo '<pre>' . print_r($searсh_link, true) . '</pre>';`
Receive:
![Screenshot_33](https://user-images.githubusercontent.com/37661593/72238274-bb5eca80-35f6-11ea-89a2-047a8f464b19.png)
`<pre>2</pre>`
If you make a query in MySQL the result displays the necessary data:
![Screenshot_34](https://user-images.githubusercontent.com/37661593/72238479-43dd6b00-35f7-11ea-8f78-9b8b5718ba1a.png)

**Comment by Lynesth** [comment]
Hello,

`R::exec` is used to simply execute a query but doesn't return SELECT data (in this case it returns the number of affected rows).

The function you are looking for is `R::getAll`.

Lyn.

**Comment by ApTemkA73** [comment]
Thank you!
Can I use redbean to get a bin from an array?
![Screenshot_35](https://user-images.githubusercontent.com/37661593/72244387-9a52a580-3607-11ea-9304-9f1040ec5b1f.png)

**Comment by Lynesth** [comment]
Yes, you can. Using `R::convertToBeans` like this:
```php
// If the type of bean you want is 'link' then you do
$beans = R::convertToBeans( 'link', $array);
```


But if you wanted beans from the start, you know you can just use `R::find` right ?

```php
// You table needs to be named 'link' for this to work
$beans = R::find( 'link', ' id_user = ? ', [ $id ] );
```
Anyway, it seems you are working with some legacy database and naming scheme. If you are still able to do it you should really consider having RedBean create your tables instead.

**Comment by ApTemkA73** [comment]
Thanks!
I need a bean just to display in a table, 2 columns
