### ISSUE TITLE
Allow multiple parameters for R::bindFunc

### ISSUE THREAD

**Issue by gabordemooij** [gabordemooij/redbean#768]
Allow multiple parameters for R::bindFunc, or just allow a plain SQL snippet like SHA1( ? ) instead of just SHA1. We might just scan for a '?' to determine if the function needs to be processed or not.

**Comment by gabordemooij** [comment]
R::bindFunc('write', 'ute.position', 'ST_GeomFromText(?, 4326)', 1 );

4th parameter = mode
0 (default) means: I just give a function name
1 means: I give an SQL snippet to insert

optionally constants can be used:

R::bindFunc('write', 'ute.position', 'ST_GeomFromText(?, 4326)', AQueryWriter::C_BIND_SNIPPET );
R::bindFunc('write', 'ute.position', 'SHA1', AQueryWriter::C_BIND_FUNCTION );

**Comment by massimosignoritti** [comment]
I think that for now is the best flexible solution

**Comment by flip111** [comment]
I don't understand what this is about.
