### ISSUE TITLE
R::begin()

### ISSUE THREAD

**Issue by marios88** [gabordemooij/redbean#773]
Using `R::begin()` with the wrong options fails silently and the code continues execution

Since using R::begin() clearly marks the need to start a transaction, in my opinion it should throw an exception instead of returning false

This is probably a breaking change, in case you dont agree with it, the manual should be changed to reflect it

```
if(R::begin()){
    try{
        R::store( $page );
        R::commit();
    }
    catch( Exception $e ) {
        R::rollback();
    }
}else{
    Throw new \RuntimeException('Could not start transaction');
}
```

**Comment by gabordemooij** [comment]
Breaking changes are not a problem since RedBeanPHP has Feature flags

**Comment by gabordemooij** [comment]
Have been researching this, but I don't think it's a good idea to change the behavior of R::begin() for the simple reason that you cannot transition from FLUID -> FROZEN anymore using the same code.
