### ISSUE TITLE
Use glueLimitOne() in getRow() and getCell() ?

### ISSUE THREAD

**Issue by marcus-seegreen** [gabordemooij/redbean#774]
Is there a reason glueLimitOne() is only used in findOne() and findOrCreate() ?

Could it not also be used in getRow() and getCell() ?

Similarly, is there a reason `-- keep-cache` isn't used for getRow(), getCell(), getAll(), getRow(), getCol(), getAssoc() and getAssocRow() ?

Is it because you could technically put multiple queries in these methods eg. `R::getAll( "UPDATE foo SET bar = 1; SELECT * FROM foo WHERE bar = 2 "`

Thanks!

**Comment by gabordemooij** [comment]
--keep-cache is used for bean functions only, that being said we could append it automatically to other queries as well. That might be  a low risk change. Still, if someone abuses R::get...() for updates it might break something.

**Comment by Lynesth** [comment]
Thing is that all `R::get...()` functions do the same simple thing: running a query.
The only thing that changes is what part of the result they return.
Which means you could do a `R::getCell('DELETE FROM table')` and it will work perfectly as well (and you'll get the number of deleted rows).

Also note that they totally bypass the QueryWriter, and the caching system in place.

So, if we did modify those functions to actually do what their name implies, and if we modified them enough to use the cache, then yes, we could forcibly add a "LIMIT 1" to getRow and getCell and a --keep-cache to the "SELECT" ones.

Anyway I found a couple of problems while checking all this, opening an new issue.

Also th
