### ISSUE TITLE
Functions that bypass QueryWriter can break the cache

### ISSUE THREAD

**Issue by Lynesth** [gabordemooij/redbean#775]
@gabordemooij an example first:
```php
R::setup( 'sqlite:/tmp/sqlitetest.db' );
R::nuke();
R::freeze( FALSE );
R::usePartialBeans( TRUE );

$author = R::dispense('author');
$author->name = "John";
R::store($author);

$author = R::load('author', 1);                    // This gets cached
$author = $author->fresh();                        // This gets cached
$author = R::findOne('author', ' id = ? ', [ 1 ]); // This gets cached
var_dump($author->name);                           // John

R::exec('UPDATE author SET name = "Bob" WHERE id = 1');
// It's broken because there's no cache check between those two calls
R::getCell('SELECT MAX(id) FROM author -- keep-cache');

$author = R::load('author', 1);
var_dump($author->name);                           // John

$author = $author->fresh();
var_dump($author->name);                           // John

$author = R::findOne('author', ' id = ? ', [ 1 ]);
var_dump($author->name);                           // John
```

Using `flushCache()` obviously fixes it.
The example might be a bit stupid but it gets to the point. Someone might be using a specific query more than once with `getCell` (or any other) and thinking the cache works for those as well, try to make use of it.

I could propose a PR for this but the matter is to first decide what we intend to do with those functions, as mentionned in #774

**Comment by flip111** [comment]
which cache ?

**Comment by gabordemooij** [comment]
Maybe we should discourage people to use the cache tag for their own caching purposes. Or we have to move the caching layer to the lower database adapter. Anyway I added a test to confirm this behavior.

**Comment by Lynesth** [comment]
@gabordemooij One way to deal with this issue right now would be to forcibly remove `-- keep-cache` from the end of queries made using `R::get...()` since it doesn't use the cache at all atm.

**Comment by gabordemooij** [comment]
Nah, I don't see the point. It's dangerous to play with those cache tags but just a warning should suffice. Cannot do everything to protect devs from themselves.

**Comment by Lynesth** [comment]
Says the guy who added stuff like `noNuke` :p
But ok, I'm fine with it.

**Comment by gabordemooij** [comment]
LOL. Yes, you're right there.
