### ISSUE TITLE
Issues with AutoResolve

### ISSUE THREAD

**Issue by Lynesth** [gabordemooij/redbean#780]
Hey @gabordemooij 
I never played with the AutoResolve feature before (nor the alias/fetchAs btw), so unless I missed something, there's a few issues with it.

First of all, I couldn't get it to work in Frozen mode. Here is an example:
```php
R::setup( 'sqlite:/tmp/sqlitetest.db' );
R::nuke();
R::freeze( FALSE );
R::usePartialBeans( TRUE );


$p = R::dispense('project');
$p->name    = 'Is the earth flat?';
$p->teacher = R::dispense('person');
$p->student = R::dispense('person');
$p->teacher->name = "Bob";
$p->student->name = "Sarah";
R::store($p);

R::freeze( TRUE );
R::setAutoResolve( TRUE );

$p = R::load('project', 1);

var_dump($p->name);
var_dump($p->teacher->name);
var_dump($p->student->name);
```
It throws an exception because the system first tries to load a `teacher` bean (line 1169 below), but since that teacher table doesn't exist it fails and stops there instead of continuing.
https://github.com/gabordemooij/redbean/blob/58d366ac135cf14c7b952cda075a7723dfb425a7/RedBeanPHP/OODBBean.php#L1168-L1171
It works in Fluid mode because that error is simply discarded and the script moves on.

------

Then, going through the code and learning how it works, I noticed it is pretty heavy at the moment:
- 1 SQL query to try and retrieve the parent bean first
- 1 SQL query to get the FK of the child bean
- 1 SQL query to actually retrieve the parent bean

While this is "ok" in Fluid mode, I think that it should be optimized when used in Frozen mode to cache the results of `getKeyMapForType`. That way we could check the real type of the bean beforehand and only make one query to retrieve it:
- 1 SQL query to get the FK of the child bean (**only once, cached**)
- Check from cache if the parent bean is of a specific type
- 1 SQL query to actually retrieve the parent bean

------

I would also recommend users not to use it and be verbose with fetchAs or aliases instead as it would be less prone to errors and faster anyway.

Let me know if I missed something there.

**Comment by gabordemooij** [comment]
Thanks for reporting this, I will look into this.

**Comment by gabordemooij** [comment]
Thanks again for this, very good find! I created a PR to fix the bug. The performance issue is not yet fixed though.

**Comment by gabordemooij** [comment]
Auto resolving is just a bad idea.
