### ISSUE TITLE
Website does not work

### ISSUE THREAD

**Issue by martinjeromelouis** [gabordemooij/redbean#784]
Hi,

I have been trying to gain access to the website (https://www.redbeanphp.com/) for several days and always get the following error ERR_CONNECTION_RESET. Is there any other place I can dowload the documentation?

Thanks,

Jerome

**Comment by Lynesth** [comment]
Hmmm,

No error here when accessing the website.
I guess you can try using google's translation to access it:
https://translate.google.com/translate?hl=fr&sl=en&tl=fr&u=https%3A%2F%2Fwww.redbeanphp.com%2Findex.php&anno=2
Not sure it'll work though.

**Comment by martinjeromelouis** [comment]
Hi Lynesth

thanks for your answer.

I don't have a language issue. If you say you can connect it must be an issue with my connection. But I can connect to websites in France and elsewhere without any issue. I am not behind a proxy. I can for instance connect to github as you can see. But I cannot connect to https://www.redbeanphp.com. And maybe I am not the only one in this situation. I wonder if this is not linked to the https protocol.... I will keep investigating and let you know if I find anything.

**Comment by gabordemooij** [comment]
Can you select your country and try to connect using this tool: https://www.locabrowser.com/ ?

**Comment by martinjeromelouis** [comment]
I get a white page

**Comment by gabordemooij** [comment]
https://www.uptrends.com/tools/uptime

**Comment by gabordemooij** [comment]
You are connecting from France?

**Comment by martinjeromelouis** [comment]
Yes, Paris. On uptrends, they say everything is ok.

**Comment by gabordemooij** [comment]
Can you try using your phone?

**Comment by martinjeromelouis** [comment]
Same error. I also tried with Firefox. They seem to say it's linked to the fact I am receiving unsafe information from your website.

**Comment by gabordemooij** [comment]
I checked everything over here but I cannot find the issue. No attacks. Uptrends geo fine. Certificate is valid. Anyway, in the meantime I will send you offline docs. They can be generated using the website, so just give me a moment...

**Comment by martinjeromelouis** [comment]
Ok thanks. I will try with my girlfriend's phone tonight and from a network in a library tomorrow and will let you know.

**Comment by gabordemooij** [comment]
Where can I send the e-mail to?
BTW: you can find the source of manual also here, it's just one big html file:
https://github.com/gabordemooij/redbean/blob/manual/redbean_manual.html

**Comment by Lynesth** [comment]
Can you try using curl with max verbosity ?

**Comment by martinjeromelouis** [comment]
Sorry, I prefer not to have my email hanging around on websites...

But I could save the redbean_manual.html on my PC and will use it. Thanks a
lot for your kind help.

Regards

Le mer. 5 févr. 2020 à 14:13, Gabor de Mooij <notifications@github.com> a
écrit :

**Comment by gabordemooij** [comment]
Fair enough.

**Comment by martinjeromelouis** [comment]
I tried :
$ch = \curl_init('https://redbeanphp.com/index.php');
\curl_setopt($ch, \CURLOPT_VERBOSE, true);
\curl_setopt($ch, \CURLOPT_STDERR, './error.txt');

$toto = \curl_exec($ch);

Got false as a result but no error.txt file was created.

**Comment by Lynesth** [comment]
@martinjeromelouis If you only have PHP to use curl, you can follow this to get the verbose output apparently: https://stackoverflow.com/a/14436877/3857024

If you can I recommend you otherwise execute it from a linux or windows terminal though.

**Comment by martinjeromelouis** [comment]
I did it with php. That's what I get : 
[error.txt](https://github.com/gabordemooij/redbean/files/4159891/error.txt)

Not sure it will help...

**Comment by Lynesth** [comment]
Ok so it tries to connect using ipv6 and apparently manages to do it. And then you get an SSL error, which seems to be linked to the fact that you are accessing it in ipv6 (according to a fast google search).

Here is an example of what I get using curl. You can see the ipv6 fails, so it falls back to ipv4 and then successfully connects.
```
curl -vvvvv https://www.redbeanphp.com/
*   Trying 77.72.150.84...
* TCP_NODELAY set
*   Trying 2a01:7c8:aaae:29a::1...
* TCP_NODELAY set
* Immediate connect fail for 2a01:7c8:aaae:29a::1: Le réseau n'est pas accessible
* Connected to www.redbeanphp.com (77.72.150.84) port 443 (#0)
* ...
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
```

I guess @gabordemooij will know better what's going on with ipv6 on his server.

**Comment by gabordemooij** [comment]
I can confirm ipv6 is not working properly at the moment. I have to look into this.

**Comment by gabordemooij** [comment]
For some reason the machine is not responding to IPv6 connections. I temporarily delisted the AAAA records to enforce IPv4 connections.

**Comment by martinjeromelouis** [comment]
Ok. I confirm it works for me now. Thanks for your help !

Le mer. 5 févr. 2020 à 18:25, Gabor de Mooij <notifications@github.com> a
écrit :
