### ISSUE TITLE
Issues with R::close();

### ISSUE THREAD

**Issue by benzon** [gabordemooij/redbean#786]
So im playing around with Redbeanphp

Got a mysql.php file where i run the connection method.

```
use \RedBeanPHP\R;

try {
    R::setup('mysql:host=' . getenv('MYSQL_HOST') . ';dbname=' . getenv('MYSQL_DATABASE'), getenv('MYSQL_USERNAME'), getenv('MYSQL_PASSWORD'));
} catch (Exception $e) {
    echo "Error while connection to the database: " . $e->getMessage();
}
```

Then i do a echo R::testConnection(); in the index.php then a R::close(); and then i try to do a nother testConnection and it still returns true.

**Comment by gabordemooij** [comment]
Thank you for reporting this, I will look into this asap.

**Comment by Lynesth** [comment]
`testConnection()` actually tries to connect first if we're not already and then returns wether we are connected or not.
You should be able to perform the test you want by using `R::getDatabaseAdapter()->getDatabase()->isConnected()`.

**Comment by benzon** [comment]
R::getDatabaseAdapter()->getDatabase()->isConnected()

Returns absolutly nothing to be honest :) just did a simple test ad EOF.

```
echo "test";
echo R::getDatabaseAdapter()->getDatabase()->isConnected();
R::close();
echo R::getDatabaseAdapter()->getDatabase()->isConnected();
```

No reply.

**Comment by Lynesth** [comment]
@benzon The connection isn't established by just calling `R::setup()` (unless you provide an object as dsn). You need to at least perform one action on the database or manually call `R::getDatabaseAdapter()->getDatabase()->connect()`.

Also, note that `isConnected()` returns a boolean so it'll echo "1" if true and nothing if false.

You can check it with the following snippet:

```php
R::setup( ... );

$database = R::getDatabaseAdapter()->getDatabase();
$database->connect(); // Or any action that needs to connect to the database

var_dump($database->isConnected()); // bool(true)
R::close();
var_dump($database->isConnected()); // bool(false)
```
