### ISSUE TITLE
Issue with auto field type

### ISSUE THREAD

**Issue by benzon** [gabordemooij/redbean#787]
So im working with a login system that uses steamid's and the way it handles steam id's is not done right.

It converts it to a INT, and insert a wrong value to db, compared to the value it's asked to add.

Ex. 76561197960295817 gets converted in to 4294967295, aint the a way around this with out having to create a string type first before then going to this other type ?

**Comment by gabordemooij** [comment]
With MySQL:

    $x = R::dispense('bean');
    $x->steamid = 76561197960295817;
    echo $x;
    R::store($x);
    $x = $x->fresh();
    echo $x;
    print_r(R::inspect('bean'));


I get: 

     {"id":0,"steamid":76561197960295817}

     {"id":"2","steamid":"7.656119796029582e16"}Array

     (
    [id] => int(11) unsigned
    [steamid] => double
     )

Gets converted to double, which is expected. If you want to avoid floating point number you need to store them as a string, for instance by prefixing them with a letter.

**Comment by Lynesth** [comment]
There a couple of way you can deal with this issue.

1. You can also force RedBean to treat anything that's over a certain integer (4294967295 in your case) as a string by using `R::getDatabaseAdapter()->getDatabase()->setMaxIntBind(4294967295)`.
_Note that this number is set to `PHP_INT_MAX` by default, except when using PHP 5.3 and SQLite or CUBRID where it's set to `2147483647`._

2. You can call `R::getDatabaseAdapter()->getDatabase()->setUseStringOnlyBinding(true)` to force all integers to be treated as string in regard to database insertion.

3. You can modify the column in your database manually to a VARCHAR once it's created (or the first steamid you provide could be a string with letters to create such a column automatically and you can delete the record afterwards).
You will be able to insert your integers in it afterwards without having the type being modified (unless you're working in Fluid mode and drop the table for some reason).

**Comment by gabordemooij** [comment]
It strange that I cannot get the number 4294967295 though... Looking at the MySQL code it says that anything higher will be cast to a double. RedBeanPHP cannot determine of course how you want to handle precision, it assumes you are just storing the number for floating point calculation which is not the case. The simplest solution I can think of is simply prefix the number like 'S76561197960295817' or something. But what database are you using because I want to figure out how you end up with 4294967295...

**Comment by Lynesth** [comment]
`4294967295` is **2<sup>32</sup> - 1** so... maybe a database on a 32bits system (https://stackoverflow.com/questions/10255724/incorrect-integer-2147483647-is-inserted-into-mysql) ?

**Comment by benzon** [comment]
It's with out doubt  on 64 bit :)

Serverversion: 10.1.44-MariaDB-0ubuntu0.18.04.1 - Ubuntu 18.04

**Comment by benzon** [comment]
tested on a different server now - it gave me 7.656119796029582e16

**Comment by benzon** [comment]
But i guess it dos something that im not used to using manual mysql with the id that is since i normally just save it as an int(11), and that have worked fine.

But it's a shame there is not a method i can use to foce the field type to be something specific, but i guess ill just do the change manually after, just to make sure.
