### ISSUE TITLE
Don't understand purpose of partial beans mode

### ISSUE THREAD

**Issue by alystair** [gabordemooij/redbean#788]
Online documentation should contain reason behind mode's existence, is it performance - or some other reason? Is it safe to enable across DB?

**Comment by Lynesth** [comment]
Hey, yes it should be totally safe.

When updating a bean, RedBean will execute an UPDATE on all of its fields.
When using partial beans mode, RedBean will only UPDATE fields that have been changed.

It is a performance upgrade:

```php
$person = R::dispense('person');
$person->name = 'Bob';
$person->age = '20';
R::store($person); // id: 1

$person->age = 21;
R::store($person);

// Without PARTIAL BEANS mode it will execute
// UPDATE person SET name = 'Bob', age = '21' WHERE id = 1;

// With PARTIAL BEANS mode on, it will execute
// UPDATE person SET age = '21' WHERE id = 1;
```
Now imagine if we had a lots of columns and a lot of beans to update.

-----

It is also a way to prevent issues with auto-updated timestamp columns (#579).
Let's say our `person` table as a `update_date` column which has `ON UPDATE CURRENT_TIMESTAMP`.

```php
$person = R::load('person', 1);
/**
 * id: 1
 * name: Bob
 * age: 21
 * update_date: 2020-02-116 13:15:00
 */

$person->age = 22;
R::store($person);

// Without PARTIAL BEANS mode it will execute
// UPDATE person SET name = 'Bob', age = '22', update_date = '2020-02-116 13:15:00' WHERE id = 1;
// Which will prevent MySQL from auto updating the column

// With PARTIAL BEANS mode on, it will execute
// UPDATE person SET age = '22' WHERE id = 1;
// This will work as intended
```

-----

For the sake of completion, it was first introduced to fix an issue with Postgre boolean type (#547).

**Comment by alystair** [comment]
Thanks, definitely seems like something that should be added to the official documentation and considered to be made default in an upcoming major version?

**Comment by gabordemooij** [comment]
Not setting partial mode to default. There may be consequences for people relying on default behavior. Please send a PR for documentation if you have any improvements.
