### ISSUE TITLE
Lazy loading of one-to-many relationship

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#789]
I have tried to check using the API docs, but I couldn't seem to find the answer to my query. The online manual states:

> When you access an own-list, RedBeanPHP will query the related beans and populate the array, this is called lazy loading. So, to load the list:
> 
> ```php
> $shop = R::load( 'shop', $id );
> $first = reset( $shop->ownProductList ); //gets first product
> $last = end( $shop->ownProductList ); //gets last product
> foreach( $shop->ownProductList as $product ) {...} //iterate
> ```

When we access the `ownProductList` property is the list cached within RedBean? In other words, given the snippet in the documentation, are there three calls to the database to obtain the `ownProductList` array, or is it cached after the initial call? For example, is the following more performant than the snippet in the documentation, or is it irrelevant? 

```php
$shop = R::load('shop', 1);
$products = $shop->ownProductList;

$first = reset($products); // get the first product
$last = end($products); // get the last product
foreach( $products as $product ) {  } // iterate over the products
```

Thanks, and apologies for filing an issue regarding this, I wasn't really sure how else to pose the question.

**Comment by gabordemooij** [comment]
The list is cached of course. Lazy loading means that the lists are not loaded if you do not access them at all.

**Comment by gabordemooij** [comment]
Sorry for the late reply btw very busy over here

**Comment by benmajor** [comment]
Thanks for the clarification, Gabor!
