### ISSUE TITLE
Possible bug in new join syntax feature

### ISSUE THREAD

**Issue by gabordemooij** [gabordemooij/redbean#795]
Move parseJoin to QueryWrite #781

**Comment by gabordemooij** [comment]
$group = R::dispense('group');
		$group->name = 'a';
		$group->sharedAuthorList =  array($bert, $albert);
		R::store($group);
		$group = R::dispense('group');
		$group->name = 'b';
		$group->sharedAuthorList =  array($bert);
		R::store($group);
		R::debug(1);
		
		
		
		$groups = R::find( 'group', ' @shared.author.name = ? ', array( 'Bert' )); // This works
		asrt(count($groups),2);

**Comment by gabordemooij** [comment]
SELECT `group`.*  FROM `group`   
					LEFT JOIN `group_person`
					LEFT JOIN `person` AS `author` ON `author`.id = `group_person`.person_id AND `group`.id = `group_person`.group_id
				 WHERE  author.name = 'Bert'<br>
array (
)<br>
An error occurred: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE  author.name = 'Bert'' at line 4<br>
PHP Fatal error:  Uncaught [42000] - SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE  author.name = 'Bert'' at line 4

**Comment by gabordemooij** [comment]
for some reason the ON-clause is missing in 1st join?

**Comment by Lynesth** [comment]
Okay so it doesn't work in mysql/mariadb, but this, for example, works in sqlite:
```php
include 'rb-sqlite.php';

R::setup( 'sqlite:/tmp/sqlitetest.db' );
R::freeze( FALSE );
R::nuke();
R::usePartialBeans( TRUE );

R::aliases([ 'author' => 'person' ]);

$bert = R::dispense('person');
$bert->name = 'Bert';
$albert = R::dispense('person');
$albert->name = 'Albert';
R::storeAll([$bert, $albert]);

$group = R::dispense('group');
$group->name = 'a';
$group->sharedAuthorList =  array($bert, $albert);
R::store($group);
$group = R::dispense('group');
$group->name = 'b';
$group->sharedAuthorList =  array($bert);
R::store($group);

R::fancyDebug( TRUE );
$groups = R::find( 'group', ' @shared.author.name = ? ', array( 'Bert' ));

/*
SELECT `group`.*  FROM `group`
    LEFT JOIN `group_person`
    INNER JOIN `person` AS `author` ON (
        `author`.id = `group_person`.person_id
        AND `group`.id = `group_person`.group_id
    )
    WHERE  author.name = 'Bert'   -- keep-cache
resultset: 2 rows
*/
```
Making the PR now.

**Comment by gabordemooij** [comment]
Funny, I didnt know about this 'short'-syntax feature in SQLite ;-)

**Comment by gabordemooij** [comment]
Looking forward to your PR, awesome!
