### ISSUE TITLE
Allow alias in find

### ISSUE THREAD

**Issue by gabordemooij** [gabordemooij/redbean#798]
Currently, our users cannot use aliased lists in find:

     $authors = R::find('author',' @own.page.title = ? ', array('about'));

Because it will search for page.author_id instead of page.person_id

We could integrate the aliasing system (with a feature flag to presever BC) with find() to make this possible.

**Comment by Lynesth** [comment]
I don't understand the connection between this and the @joined feature.

I thought that `load`, `find`, etc didn't work with aliases anyway.
Like, you can't do `R::load('author', 1)` or `R::find('author', ' id = 1 ')` if the `author` table doesn't exist even if you declared global aliases).

Maybe I did not understand your question ?

**Comment by gabordemooij** [comment]
That's true. However you added support for aliases in the @joined feature which you made available to R::find() so now find() has partial support for aliases (https://github.com/gabordemooij/redbean/pull/781). - But I agree I don't want to make things too complex. If we can reduce complexity we should do so.

**Comment by Lynesth** [comment]
I see your point.

I honestly don't see how much complex it is to actually just check the aliases table first when doing load/find/etc and switching to the correct type if needed. I think we could probably add that.

**Comment by gabordemooij** [comment]
Okay, I was a bit in doubt.
I must say, thanks to your contributions I feel inspired to integrate these features better into the core. Some features of RedBeanPHP have not been integrated that well, this seems to be changing now, which is a good point I think.

For my current project, I could really use the newly available R::children() + @joined for instance, that really works great.

**Comment by gabordemooij** [comment]
@Lynesth would you like to implement this and have me test it?

**Comment by Lynesth** [comment]
@gabordemooij We're talking about doing this, right ? 
```php
R::aliases(array( 'author' => 'person' ));
R::load('author', 1); // Loads a person bean
R::findOne('author', ' whatever '); // Finds a person bean
// And so on...
```

**Comment by gabordemooij** [comment]
Yes, but this should also be possible

     $authors = R::find('author',' @own.page.title = ? ', array('about'));

That's the original case, to make the @-parts work everywhere. But I don't think that requires extra code at all. But maybe I am wrong?

**Comment by Lynesth** [comment]
Yes. At the moment using an alias as the type for `load`, `find`, etc is not supported. If we add that then everything else would work. I don't see anything specific to do for the @ syntax.

I haven't looked at it yet but it seems to be as simply as to add this at the top of each of the functions we want to support that feature:
```php
// Example with load()
public static function load( $type, $id, $snippet = NULL ) {
    $aliases = OODBBean::getAliases();
    if ( isset( $aliases[$type] ) ) {
        $type = $aliases[$type];
    }
    // rest of the function...
}
```

But I'm not sure I'm entirely in favour of doing this.
Let's say that `author` is an alias for `person`. It makes sense when you do `$book->author` to resolve the alias.
But when doing `R::findAll('author');` for example, it's actually going to retrieve all the `person`, not only those who are "authors" of some book. So it might seem a bit counter intuitive in way.

**Comment by gabordemooij** [comment]
I agree, but with R::find('person') you won't be able to use @own.page right?

**Comment by gabordemooij** [comment]
Maybe we can discuss this on discord?
