### ISSUE TITLE
Issues with chained joins

### ISSUE THREAD

**Issue by Lynesth** [gabordemooij/redbean#800]
Ok so as a followup to what I said in #781 :

I noticed you want to allow joining the same table multiple times, because they can be joined with different tables when chained.

While that's a good idea, you also need to add aliases for those tables otherwise it won't work as there will be ambiguous things going on.

For example, this piece of code:
```php
R::findOne('device', ' @joined.bluetooth.joined.manufacturer.name = ? OR @joined.wifi.joined.manufacturer.name = ? ', [ 'M1', 'M2' ]);
```
Gives the following query
```sql
SELECT `device`.*
FROM   `device`
       LEFT JOIN `bluetooth`
              ON `bluetooth`.id = `device`.bluetooth_id
       LEFT JOIN `manufacturer`
              ON `manufacturer`.id = `bluetooth`.manufacturer_id
       LEFT JOIN `wifi`
              ON `wifi`.id = `device`.wifi_id
       LEFT JOIN `manufacturer`
              ON `manufacturer`.id = `wifi`.manufacturer_id
WHERE  manufacturer.name = 'M1'
        OR manufacturer.name = 'M2'
LIMIT  1 -- keep-cache
```
Which fails because
```
An error occurred: SQLSTATE[HY000]: General error: 1 ambiguous column name: manufacturer.name
```

**Comment by gabordemooij** [comment]
Very good find.
But how can we solve this? We could try to detect whether a table is joined multiple times and add a suffix to the alias maybe?

**Comment by Lynesth** [comment]
Sure I can do that. Let's keep the whole conversation here from now on this matter.

**Comment by gabordemooij** [comment]
Sure, good idea.

**Comment by gabordemooij** [comment]
If you take care of the code, I will write the tests ;-)
