### ISSUE TITLE
Cant you create beans with _ in them?

### ISSUE THREAD

**Issue by benzon** [gabordemooij/redbean#802]
Hi tryed to fit a bean in to my permission system

users_roles thought i could use usersRoles, and that gives an error.

`AH01071: Got error 'PHP message: PHP Fatal error: Uncaught RedBeanPHP\\RedException: Invalid type: usersRoles in /var/www/vhosts/dev.benzon.pw/httpdocs/vendor/gabordemooij/redbean/RedBeanPHP/Util/DispenseHelper.php:77\nStack trace:\n#0 /var/www/vhosts/dev.benzon.pw/httpdocs/vendor/gabordemooij/redbean/RedBeanPHP/Util/DispenseHelper.php(151): RedBeanPHP\\Util\\DispenseHelper::checkType()\n#1 /var/www/vhosts/dev.benzon.pw/httpdocs/vendor/gabordemooij/redbean/RedBeanPHP/Facade.php(853): RedBeanPHP\\Util\\DispenseHelper::dispense()\n#2 /var/www/vhosts/dev.benzon.pw/httpdocs/includes/steamauth.php(58): RedBeanPHP\\Facade::dispense()\n#3 /var/www/vhosts/dev.benzon.pw/httpdocs/routes/login.php(4): require('/var/www/vhosts...')\n#4 /var/www/vhosts/dev.benzon.pw/httpdocs/public/index.php(41): {closure}()\n#5 {main}\n thrown in /var/www/vhosts/dev.benzon.pw/httpdocs/vendor/gabordemooij/redbean/RedBeanPHP/Util/DispenseHelper.php on line 77'`

**Comment by benzon** [comment]
tryed users_roles to and it did not work either.

**Comment by Lynesth** [comment]
Hey,

It should be lowercase only, so userrole (or usersroles) should be what you want.
Also you cannot use an underscore as those are use for association tables (role_user would be the table that link beans from the user table to the role table in a many-to-many relationship, maybe that's what you want ?).
