### ISSUE TITLE
method hasDatabase() is not documented on site

### ISSUE THREAD

**Issue by masakik** [gabordemooij/redbean#804]
Hi, I found just on api documentation (nowhere else) the use of hasDatabase method, usefull for multiple connection setting. Maybe it could be documented at redbeanphp.com site as a way of checking if a database is already set to a key. My example:
```php
if (!R::hasDatabase('db2')) {
    R::addDatabase('db2', 'sqlite:/path/db2.db');
}
R::selectDatabase('db2');
```

**Comment by gabordemooij** [comment]
API is more elaborated than site manual.
