### ISSUE TITLE
How to systemize eager loading of a model's child beans?

### ISSUE THREAD

**Issue by fabswt** [gabordemooij/redbean#806]
I end up repeating the same pattern all over my code:

```php
$user = R::findOne(
'user',
'email = :email',
array(':email' => 'bob.smith@example.org')
);
R::preload($user, array('language'));
```

The repetitive `R::preload()` being the issue. It's not pretty since I keep repeating myself and, if I forget to preload, I'll run into trouble.

Simplified, the database structure is:

    user.id
    user.name
    user.email
    user.language_id

    language.id
    language.code
    language.name

If I were to access `$user->language->name` (or any other foreign key property) inside PHP itself, it would work fine, RedBean would load what it needs for me.

But I'm passing `$user` to the templating engine to access its attributes (here with Slim Framework):

```php
return $this->get('view')->render(
	$response,
	'tests/redbean-preload.twig',
	array(
	    'user' => $user,
	)
);
```

This lets me use `{{ user.language.code }}`, `{{ user.language.name }}`, etc. inside the Twig template, but won't work without `R::preload()`. (I know Gabor is not a fan of Twig, my question is close to this one about [Twig support](https://github.com/gabordemooij/redbean/issues/371)).

(Without `R::preload()`, I'll get 'An exception has been thrown during the rendering of a template ("FUSE: method does not exist in model: language").' – which is a bit of a misnomer since `language` is a foreign key bean, not a method.)

I came up with the following:

```php
namespace Model;
use \R;
class User extends \RedBeanPHP\SimpleModel
{
    public function open() {
        // Access the language bean to force loading it.
        $this->language->name;
    }

    // …
}
```

or

```php
class User extends \RedBeanPHP\SimpleModel
    public function language() {
        return $this->language;
    }

    // …
}
```

which will, as far as I can tell, behave the exact same: on `R::findOne()`, they each generate two queries, one to find the User bean, the next one to load the language bean (same as with `R::preload()`.)

But it feels unclean. It would make more sense if RedBean loaded both the bean and its foreign key(s) at once. Is this doable?

**Comment by Lynesth** [comment]
Hey !

It seems Slim tries to `__call` "language" instead of `__get` it for some reason.
Could you please show the Twig code as well ?

Also, which version of RedBean are you using ?

**Comment by Lynesth** [comment]
Ok so here's how Twig actually tries to access a property when you write `user.language`:
```php
// Array key.
$user['language'];
// Object property.
$user->language;
// Also works for magic get (provided you implement magic isset).
$user->__isset('language') && $user->__get('language');
// Object method.
$user->language();
// Object get method convention.
$user->getLanguage();
// Object is method convention.
$user->isLanguage();
// Method doesn't exist/dynamic method.
$user->__call('language');
```

Thing that happens is that `__isset` fails, because only `language_id` exists at that point. So it tries to access it as a method, which fails as well and throw the exception you've noticed.

It could easily be fixed by checking if either `property` or `property_id` exists in the `__isset` method and it doesn't seem it'd break anything internally. But it may break someone's code doing simple checks on a property.

As of right now, here are a few ideas to fix your problem:
- Retrieve it beforehand, like you were doing (not using the `language()` function though, that's not a good idea) ;
- Use `user.__get('language')` in Twig instead of `user.language` when accessing foreign key beans (should only needed for the first time).
- Monkey patch RedBean yourself, changing `return isset( $this->properties[$property] );` for `return isset( $this->properties[$property] ) || isset( $this->properties["{$property}_id"] );`. This is totally untested and could have side effects.

**Comment by fabswt** [comment]
Thanks for the insight!

Using the latest RedBean (5.4.2).

- For testing, using a simple route like this:

```php
$app->get('/tests/redbean/preload/', function ($request, $response, $args) {
    $user = R::findOne(
        'user',
        'email = :email',
        array(':email' => 'bob.smith@example.org')
    );
    // R::preload($user, array('language'));

    return $this->get('view')->render(
        $response,
        'tests/redbean-preload.twig',
        array(
            'user' => $user,
        )
    );
});
```

- In Twig, used this alone in a redbean-preload.twig template:

```twig
{{ user.language.code }}
{{ user.language.name }}
{{ user.language.script }}
{{ user.language.direction }}
```
---

`user.__get('language')` does work. It produces the same number of queries as the other options I'd described. Might come in handy.

I realize I'm really describing two issues:

1. How to eager load without repeating oneself.
2. How to eager load in a single query rather than a bunch.

I got very curious when I read this in the changelog (emphasis mine):

> Why has the Preloader been removed?
>
> When I wrote the preloader, the original purpose was to prevent for-each loops to fire queries when retrieving the parent of a bean. Later I added the writer cache which could take care of this but was turned off by default. In RedBeanPHP the writer cache is turned on by default solving the original problem. Meanwhile people requested all kinds of new features for the Preloader like support for loading own-lists, shared-lists and even aliases and SQL snippets. It even got its own syntax. I decided to remove the preloader because **I believe simple SQL is better suited to query large amounts of records all at once for overviews and reports.**
This functionality is still available as a plugin. 

I thought the emphasized bit would refer to some form of eager loading.

**Comment by Lynesth** [comment]
If you want to load the user and its language at the same time, you can use **findMulti**:
https://redbeanphp.com/index.php?p=/finding#find_multi

```php
$users = R::findMulti(
    'user,language',
    'SELECT user.*, language.* FROM user LEFT JOIN language ON user.language_id = language.id WHERE user.email = ?',
    [ 'fabien.snauwaert@gmail.com' ],
    [
        [
            'a'       => 'user',
            'b'       => 'language',
            'matcher' =>  function( $a, $b ) {
                return ( $a->language_id == $b->id );
            },
            'do'      => function( $a, $b ) {
                $a->language = $b;
            }
        ]
    ]
);
```
You can also replace the last parameter with a simple `Finder::map('language', 'user');` if you're not using aliases (see just below on the page I linked):

```php
use RedBeanPHP\Finder;
$users = R::findMulti(
    'user,language',
    'SELECT user.*, language.* FROM user LEFT JOIN language ON user.language_id = language.id WHERE user.email = ?',
    [ 'fabien.snauwaert@gmail.com' ],
    [
        Finder::map('language', 'user');
    ]
);
```

Please note that using **findMulti** isn't necessarily faster than loading things with multiple queries and I invite you to benchmark for your own needs.

**Comment by gabordemooij** [comment]
I also just added:
Finder::onmap() mapper and
R::also()

     $all = R::findMulti('country',
     R::genSlots( $users, 'SELECT country.* FROM country WHERE id IN ( %s )' ),
     array_column( $users, 'country_id' ),
     [	Finder::onMap('country', $users) ]
     );

Even shorter:

     $users = R::find('user');
     $users = R::also( users, 'country' );
