### ISSUE TITLE
PDO class not found

### ISSUE THREAD

**Issue by mostav** [gabordemooij/redbean#810]
Hi there,

Appreciate your help with my issue below:
I came across the error 
`Uncaught Error: Class 'PDO' not found in /var/www/html/vendor/RB.php:1041`
at the setup of my web PHP app on a new Linux environment which is Alpine v3.11.

**Versions**
RedBean v5.4.2
PHP v7.4
Alpine v3.11
Apache 2.4

For your information, calling `new PDO('...');` in a php script directly works like a charm.
Any hint? Thank you.

**Comment by Lynesth** [comment]
What if you make a simple php script in which you first include `/var/www/html/vendor/RB.php` and then call `R::setup()` ?

**Comment by mostav** [comment]
Actually it's fixed by installing PHP packages from apk manager and not using docker extensions. Thank you.
