### ISSUE TITLE
Performance drop with RedBean 4+

### ISSUE THREAD

**Issue by fabswt** [gabordemooij/redbean#811]
Hi,
I upgraded to RedBean 4, but after realizing it caused a big performance loss I ended up downgrading. Some details:

![redbean 4 issue annotated](https://user-images.githubusercontent.com/3042488/78682219-0171b480-78ee-11ea-9e07-b74fba693b52.png)

In other words, after upgrading to RedBean 4 (ditto with RedBean 5):

- Lots of timeouts
- The response time overall went really up (in ms):

Version    | Max   | 99th percentile | 95th percentile | 50th percentile
-----------|-------|-----------------|-----------------|----------------
RedBean 3  |  1471 |   415           |  207            |  75
Redbean 4+ | 30719 | 18431           | 1343            | 127

Did anyone experience anything similar?

**Comment by gabordemooij** [comment]
Looks weird. Almost as if you are working in fluid mode. But without detailed information it is hard to determine the root cause of this performance drop. I have not noticed significant performance differences between versions, but to be honest, I haven't really checked, because I have had no performance problems in general.

**Comment by sah-comp** [comment]
I am willing to check, because I am at the eve of upgrading. @fabswt, can you provide a test-suite?

**Comment by Lynesth** [comment]
@fabswt It will be hard to know exactly what causes it without knowing what your code does.
As @gabordemooij pointed out, are you sure you are not using Fluid mode ?
Also, could you provide a piece of code that performs much worse in RedBean 5 ?

**Comment by fabswt** [comment]
Thanks for the hindsight. Working at it.

**Comment by Lynesth** [comment]
Hey there @fabswt !

Did you get the time to work on this by chance ?

**Comment by fabswt** [comment]
No, sorry. I got swamped. Feel free to close it. I'll reopen with details it if needed.

**Comment by Lynesth** [comment]
Hey there,

Could you please show us the piece of code that calls the `findOne` as well as the exact query that's ran in Postgres ?

**Comment by fabswt** [comment]
Working on a MCVE... Managed to reproduce the issue locally... will keep you posted ASAP.

**Comment by fabswt** [comment]
Turns out the issue wasn't due to RedBean directly.

I have a `findOne` like so:

```php
/**
 * Any Extra Practice available?
 */
$extrareview = R::findOne(
    'review',
    '
    type = :type
    AND clicker_id = :clickerid
    AND done is NULL
    AND due <= :now ORDER BY due ASC
    ',
    array(
        ':type' => 'EXTRA',
        ':clickerid' => $clicker->id,
        ':now' => Helper::isoDateTimeTZ()
    )
);
```

With the RedBean upgrade came a change in terms of the query being generated:

```sql
-- 3.5
SELECT * FROM "review" WHERE type = :type AND clicker_id = :clickerid AND done is NULL AND due <= :now ORDER BY due ASC -- keep-cache

-- 4 and 5
SELECT "review".* FROM "review" WHERE type = :type AND clicker_id = :clickerid AND done is NULL AND due <= :now ORDER BY due ASC LIMIT 1 -- keep-cache
```

The query plan with the `LIMIT 1` was bad, with Postgres scanning through millions of rows. Adding a multi-column index and removing an old index from the table in question fixed it.

Happily upgraded to RedBean 5 and all is good now :)

Sorry about the false alert!
