### ISSUE TITLE
Issues with null on linked bean

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#817]
I have searched through the closed issues on Github, but wasn't able to find any references to the following.

Consider the below snippet:

```php
$user = R::dispense('user');
$user->name = 'John Doe';
$user->company = R::dispense('company');
R::store($user);
```

This will correctly generate a schema as follows:

```
+------------+------------+
|    name    | company_id |
+------------+------------+
| John Doe   |     1      |
+------------+------------+
```

However, if we then run the following:

```php
$user2 = R::dispense('user');
$user2->name = 'Jane Doe';
$user2->company = null;
R::store($user2);
```

We end up with a schema which looks as follows:

```
+------------+------------+---------+
|    name    | company_id | company |
+------------+------------+---------+
| John Doe   |     1      |   NULL  |
+------------+------------+---------+
| Jane Doe   |    NULL    |   NULL  |
+------------+------------+---------+
```

Surely the correct behaviour in this instance is to check if the property (i.e. `company`) already exists as a linked relationship in the table, and simply assign the `*_id` field a value of `NULL`, instead of creating an unnecessary field?

**Comment by gabordemooij** [comment]
No, it's not. This works as expected. Otherwise you would not be able to set a column to null right?

**Comment by benmajor** [comment]
Why not? What I'm saying is that it would be better for the ORM to check if there's already a relationship defined on the `company` property, something like the following psuedo-code:

if exists $fieldname_id: set to null
else create column $fieldname

If the `company` column has been added before a link-bean record has been added, that's understandable. But if there exists a relationship on the property, it should be set to NULL.

This would still allow the setting of another field to be null, but avoids the creation of unnecessary columns in the database. For example, running the following snippet:

```php
$user2 = R::dispense('user');
$user2->name = 'Jane Doe';
$user2->company = null;
$user2->avatar = null;
```

Would produce the following (correct) schema, assuming `$user1` had been stored first:

```
+------------+------------+----------+
|    name    | company_id |  avatar  |
+------------+------------+----------+
| John Doe   |     1      |    NULL  |
+------------+------------+----------+
| Jane Doe   |    NULL    |    NULL  |
+------------+------------+----------+
```

**Comment by Lynesth** [comment]
When you use `R::dispense`, RedBean doesn't retrieve the columns of the dispensed type. It just creates an empty bean.

If you don't want to set a company for that 2nd bean, just don't set it.

If you load an existing bean (or first set a company to your new bean) and then set its company to `null` then it will know that it needs to link that to `company_id` because the bean knows that column now.

I understand that it can be a bit counter intuitive.

**Comment by benmajor** [comment]
Yes, I had discovered the work around when playing around with this test case actually. Sadly, I'm now having to delete columns from a 2.5 GB table I just finished importing because of this exact issue!

I understand that we can just not set the `company` parameter, but sometimes, we may not know if the value is null. The snippet I posted was a simple version of the code I have just used, which actually used the following in the import:

```
$user2->company = R::findOne('company', 'name = ?', [ $csvRow[0] ]);
```

Since this is a database import, we don't actually know if the `findOne` call will return a Bean, or null.

**Comment by Lynesth** [comment]
Yeah I understand. You'll need one more check to see if that retrieved a bean before assigning it then.
Also, just delete the column, not the entire table :)

**Comment by benmajor** [comment]
Yes, I realise that now! In future, we can always add this check, but it might be worth adding something in the docs about this behaviour, as I'm sure it'll catch a few devs out. From a data integrity point of view, it would be better if the ORM acknowledged known relationships when dispensing a bean of known type, surely?  I appreciate this would be a performance hit, but might be better for integrity in the long run, and prevent the schema from messing up in this way.
