### ISSUE TITLE
Support for multithreaded usage

### ISSUE THREAD

**Issue by insperedia** [gabordemooij/redbean#818]
I am using an excellent Parallel extension for multithreaded execution and it works perfectly. Unfortunately, RedBeanPHP uses the static class facade with the global state which makes it impossible to use it in a multithreaded application in an easy way.

**Comment by gabordemooij** [comment]
Absolutely not, you don't have to use the Facade. You can use the objects behind the facade with minimal effort.

https://redbeanphp.com/index.php?p=/non_static

**Comment by insperedia** [comment]
Nice! Thanks for the reference and for the great ORM.
