### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#819]
I have a table that contains just over 9 million records, and the indexes have been defined well to work with our database model.

Please consider the following:

```php
# PDO method:
$db = new \PDO('mysql:dbname=db;host=localhost', 'root', 'root');
$q = $db->prepare('SELECT id FROM record WHERE asn = :asn');
$q->execute([ ':asn' => $asn ]);
$res = $q->fetchObject();
$r = R::load('record', $res->id);

# RedBean method:
$res = R::getRow('SELECT id FROM record WHERE asn = ? LIMIT 1', [ $asn ]);
$r = R::load('record', $res['id']);

# RedBean findOne method:
$r = R::findOne('record', 'asn = ?', [ $asn ]);
```

The benchmarks for this under PHP 7.4 are as follows:

PDO method: 4.32 ms
RedBean `getRow` and `load`: 574.02 ms
RedBean `findOne`: 3518.75 ms

Can you please explain why the PDO method is shaving a massive amount of time off both the RedBean solutions? What is the correct approach to achieving comparable speeds using a RedBean-only solution?

**Comment by gabordemooij** [comment]
My first guess would be that the parameter type does not match and therefore the database index isn't used. What is asn? You can enforce parameter types using array notation: [ $asn, PDO::PARAM_INT ] for instance.

**Comment by benmajor** [comment]
Great response, @gabordemooij! The column type of `asn` is the default created by RedBean (i.e. `VARCHAR(191)`), forcing the parameter to be `PDO::PARAM_STR` has resolve this.
