### ISSUE TITLE
Problem with Begin and Exec

### ISSUE THREAD

**Issue by bluedrayco** [gabordemooij/redbean#820]
I have the following piece of code using redbean 3.5:

```
    R::begin();
    foreach ($sqlOrder as $order) {
        foreach ($statements[$order] as $index => $sql) {
            try {
                R::exec($sql);
                $statements[$order][$index] = array('sql' => $sql, 'result' => true, 'message' => 'ok');
            } catch (\Exception $ex) {
                $statements[$order][$index] = array('sql' => $sql, 'result' => false, 'message' => $ex->getMessage());
            }
        }
    }
    R::rollback();
```

My code only needs to extract the posible errors executing the sql statements and after rollback the changes but... the changes always are applied, the freeze option in the database is true, i don't know if i'm wrong or i cannot use begin with exec and the documentation does not explain this situation.

**Comment by Lynesth** [comment]
Hey,

Could you please tell us which DBMS you are using and an example of the queries you are performing ?

Your example should be working but some database automatically perform commits after certain operations, like DDL statements.

**Comment by bluedrayco** [comment]
The database is MySQL and some queries ar the following:

`
DROP TABLE IF EXISTS `tipousuario`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tipousuario` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `tipo` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activo` tinyint(1) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;



--
-- Table structure for table `grupo`
--

DROP TABLE IF EXISTS `grupo`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `grupo` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `grupo` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `anio` int(11) unsigned DEFAULT NULL,
  `activo` tinyint(1) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;



--
-- Table structure for table `usuario`
--

DROP TABLE IF EXISTS `usuario`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `usuario` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `nombre` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `apellido_paterno` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `apellido_materno` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `identificador` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fecha_nacimiento` datetime DEFAULT NULL,
  `fecha_alta` datetime DEFAULT NULL,
  `fecha_modificacion` datetime DEFAULT NULL,
  `activo` tinyint(1) unsigned DEFAULT NULL,
  `grupo_id` int(11) unsigned DEFAULT NULL,
  `tipousuario_id` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_foreignkey_usuario_grupo` (`grupo_id`),
  KEY `index_foreignkey_usuario_tipousuario` (`tipousuario_id`),
  CONSTRAINT `c_fk_usuario_grupo_id` FOREIGN KEY (`grupo_id`) REFERENCES `grupo` (`id`) ON DELETE SET NULL ON UPDATE SET NULL,
  CONSTRAINT `c_fk_usuario_tipousuario_id` FOREIGN KEY (`tipousuario_id`) REFERENCES `tipousuario` (`id`) ON DELETE SET NULL ON UPDATE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;


--
-- Table structure for table `checkpoint`
--

DROP TABLE IF EXISTS `checkpoint`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `checkpoint` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `fecha_registro` datetime DEFAULT NULL,
  `activo` tinyint(1) unsigned DEFAULT NULL,
  `usuario_id` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_foreignkey_checkpoint_usuario` (`usuario_id`),
  CONSTRAINT `c_fk_checkpoint_usuario_id` FOREIGN KEY (`usuario_id`) REFERENCES `usuario` (`id`) ON DELETE SET NULL ON UPDATE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;


--
-- Table structure for table `hook`
--

DROP TABLE IF EXISTS `hook`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `hook` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `hora_activacion` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lunes` tinyint(1) unsigned DEFAULT NULL,
  `martes` tinyint(1) unsigned DEFAULT NULL,
  `miercoles` tinyint(1) unsigned DEFAULT NULL,
  `jueves` tinyint(1) unsigned DEFAULT NULL,
  `viernes` tinyint(1) unsigned DEFAULT NULL,
  `sabado` tinyint(1) unsigned DEFAULT NULL,
  `domingo` tinyint(1) unsigned DEFAULT NULL,
  `instruccion` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activo` tinyint(1) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

`

And some inserts to these tables, thanks.

**Comment by Lynesth** [comment]
Yeah then that's what I thought.
Unfortunatly, DDL statements are automatically commited by MySQL: https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html

Nothing we or you can do about except switching to a different DBMS which support transactional DDL, like PostgreSQL.
