### ISSUE TITLE
question/suggestion on non static usage

### ISSUE THREAD

**Issue by workingtom** [gabordemooij/redbean#822]
Dear sir,

Maybe i am missing something but i don't see an obvious solution to calling i.e. R::store() on a particular toolbox (and all the other R::xyz() facade functions), which is typical when using redbean in a non-static environment? I did of course read the page [here](https://redbeanphp.com/index.php?p=/non_static).
I am trying to use multiple databases and would like to call the R::xyz() functions in the Facade directly on a particular toolbox. In the case of R::store([...]) i would expect something like this:

```
// facade function
public static function store( $bean, $unfreezeIfNeeded = FALSE ) {
  self::storeBackend(bean, $unfreezeIfNeeded, self::$redbean)
}

// this function can be called by both the facade and 
// with $toolbox->getRedBean() for non-static usage
public static function storeBackend( $bean, $unfreezeIfNeeded , $redbean ) 
{
[body of function]
}
```
(obviously the storeBackend() function should normally not be in the facade itself but in a backend-worker- class of some kind)

Any suggestions how to cleanly resolve this ?

**Comment by Lynesth** [comment]
Hey there. We are actually thinking of a possibility to make it happen.
Meanwhile I advise you to check #816 comments in which you'll find more info on the subject as well as a simple class that could emulate what you are looking for.

**Comment by workingtom** [comment]
Thanks that helps a lot. Actually i made myself a lazyloader that did something along the lines what is suggested in the topic you linked to. But it feels a little bit quirky. 
I did look into calling  R::selectDatabase() before each call to R:xyz(), which is not overly expensive, since not much is done when the proper database is already active.

However it did strike me somewhat odd that the facade has "real" code. I'm sure its a proper use of the facade software pattern, but my natural 'instinct' would be to create a completely empty facade (aside from the calls to other functions) and let the facade only doing calls to a worker class with the active database. Then the static and non-static usage would be completely symmetrical and the facade would be a "real" facade which lets other classes do the heavy lifting. If a facade has 'real' code its become less of a facade. When the facade is the only place with a particular piece of code, it obviously cant be used indirectly. 

Anyway thanks for your quick reply, then at least i know i was not missing the obvious.
