### ISSUE TITLE
maybe a bug in dsn

### ISSUE THREAD

**Issue by workingtom** [gabordemooij/redbean#823]
I think in Facade.php (line:263) the dsn might be wrong.

```
if ( is_null( $dsn ) ) {
	$dsn = 'sqlite:/' . sys_get_temp_dir() . '/red.db';
}
```
On my commercial unix host this gives:
`sqlite://tmp/red.db` which i think should be `sqlite:/tmp/red.db`
I tested for 2 sec and although it does work on my host (both single and double slash at start)... on my local windows environment the extra / at beginning gives issues.

I have a feeling i might be wrong since this code is pretty much the most used code in the library(and i am pretty tired), but maybe because it seems to work it stayed unnoticed for very long?

**Comment by Lynesth** [comment]
I don't have a windows to test it infortunatly, but it could very likely be a bug.

I'm not even sure why we're keeping that line in.
If it's for quick prototyping using an sqlite database, I don't think it'd bother anyone to write a few more characters by passing the dsn manually.

Unless there's a specific reason it's still there @gabordemooij I'm in favour of removing it and simply throwing an exception if no dsn is specified.

**Comment by gabordemooij** [comment]
It's handy for tests, demos and prototyping. I see no reason why we should remove it. I don't use Windows so I don't know what's wrong with it on Windows, probably slashes or so? I would accept a PR that fixes this for Windows.

**Comment by workingtom** [comment]
(Personally i would not break backwards compatibility, looking at how often the no args R::setup() is used in the documentation. It will make many examples around the internet fail instantly. )

If i am not mistaken, without exceptions, all sqlite dsn's are with only a single /. Doing a search on the R lib itself gives 5-ish examples like `sqlite:/tmp/db1.txt` . I dont think its a windows issue at all.
The dsn should be  (i also took a quick look the php pages) `"dsn:$path"` , not `"dsn:/$path"`.
When doing this, it goes correctly on windows and linux . But apperenly in linux you can use a "//tmp/red.db" (which is happening now) path and it still works... or so it seemed on my host.

Im not a linux guru but i would be rather surprices if sys_get_temp_dir() on linux would give a path not starting with a '/'

the examples from the php pages are like this:

> sqlite:/opt/databases/mydb.sq3
> sqlite::memory:
> sqlite2:/opt/databases/mydb.sq2
> sqlite2::memory:

Either way i am (of course) more then willing to help in any way i can

**Comment by gabordemooij** [comment]
https://github.com/gabordemooij/redbean/commit/bc65b616cc098dac467b11fa93f259483016033a
