### ISSUE TITLE
How to allow camel case in column name.

### ISSUE THREAD

**Issue by Hackynk** [gabordemooij/redbean#825]
I have using RedBeanPHP version 5.5. Also I have read the FAQ related to this issue. In the end, you have mentioned

**Note that RedBeanPHP 3.4+ supports so-called beautiful column names, this will turn camelCased column names in underscored_column_names. You can turn this feature off as well.**

So, How can I disable this feature?

I have using this operation.
$user = R::despense("User");
$user->Name = "User Name"; 
R::store($user);
But it's creating _name column inside database. I don't want to convert it into sneakcase.

**Comment by Lynesth** [comment]
Hello,

You are quoting the FAQ for RedBeanPHP 3.X, it is not possible to disable this feature in 5.5.

**Comment by Hackynk** [comment]
Thanks for the information. But as per note this feature will available in **3.4+** versions.

I found code for disabling this beautifier.
**RedBean_OODBBean::setFlagBeautifulColumnNames(false);**
but it causing the issue **Fatal error: Uncaught Error: Class 'RedBean_OODBBean' not found in** 

Also, I checked in rb.php file, there is no class named RedBean_OODBBea.
Please help me to sort it out.

Thank you in advance!

**Comment by Hackynk** [comment]
I have solved this issue by changing the camelsSnake (on line 5360) function.

I changed **return $camel;**

Ii will be helpful to people who want Camelcase in any condition.

@Lynesth Thanks again for version information.
closing this thread.
