### ISSUE TITLE
a thought about findOrCreate()

### ISSUE THREAD

**Issue by CaffeineLab** [gabordemooij/redbean#827]
I was having a hard time with this function because I needed to know whether or not the record was being created and I didn't want to sort out a way to flag it and then test for a flag so I made a quick change in the function and wanted to see if it was acceptable or if there was another preferred way of solving this.  Essentially returning an array with the bean and the result.  Thoughts?

list($bean, $created) = R::findOrCreate(......)

```
	public function findOrCreate( $type, $like = array() )
	{
			$beans = $this->findLike( $type, $like );
			if ( count( $beans ) ) {
				$bean = reset( $beans );
				return [$bean, false];
			}

			$bean = $this->redbean->dispense( $type );
			$bean->import( $like );
			$this->redbean->store( $bean );
			return [$bean, true];
	}
```

**Comment by gabordemooij** [comment]
Thanks, I understand the idea. I will look into it. Changing the return value breaks backward compatibility though, so maybe we could just add a '&' return parameter?

**Comment by CaffeineLab** [comment]
Hah!  I'll leave that up to you :)  

Thanks for entertaining the idea.  I wish I could say it was mine, but there is a similar feature in the Python PeeWee ORM that I use.
