### ISSUE TITLE
Issue with strict mode

### ISSUE THREAD

**Issue by TheFrankman** [gabordemooij/redbean#828]
Hello There, 

I know that you don't support strict mode. Unfortunately, the database is now on a Galera cluster where we don't want to have to globally disable strict mode across all databases for a single application that uses RedBean.

Is it possible with R::setup or R::exec to set strict mode only for that connection ? I might be talking non-sense but this sort of thing is possible in Eloquent doing something like this : `DB::statement("set session sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'");`

**Comment by gabordemooij** [comment]
R::exec() should work, you should be able to execute that statement. Some statements cannot be performed using exec(), including SQLite pragmas but this should work.
