### ISSUE TITLE
possible isEmpty bug

### ISSUE THREAD

**Issue by AndiLeni** [gabordemooij/redbean#829]
Hello,

`isEmpty()` gives me the following error `Call to a member function isEmpty() on null` when my bean is null.
I thought, isEmpty() also checks for null.

My code looks like:
```
$entry = R::findOne('data', 'ip = ?', [$userIp]);
if ($entry->isEmpty()){
```

Using the php's native function `empty()` works fine.

Kind regards
Andreas

**Comment by Lynesth** [comment]
Hello,

`isEmpty` checks if a **bean** has no other properties than the id field OR if all the other properties are 'empty()' (this might include NULL and FALSE values).

However, `findOne` returns NULL if it cannot find the bean you are looking for, not a **bean**. So the behavior is normal and you should instead use the native `empty` or `is_null` in that case.

Regards,

Lyn.

**Comment by AndiLeni** [comment]
Oh, I see.
Then I misunderstood the docu at that point.
Sorry for the confusion.
