### ISSUE TITLE
Create bean without loading it

### ISSUE THREAD

**Issue by JeromeDeLeon** [gabordemooij/redbean#830]
Happy to use this library but I have question when doing a foreign key operation.

I have this setup like Category and SubCategory tables. I just passed a json body.

POST /subCategory
```json
{
  "name": "Hello",
  "categoryId": 1
}
```

Now inside of it, I had to load the whole category where I could have just pass it as an Id and it will automatically link as foreign key like it could have a `loadWithoutData` or having an optional third argument of boolean to tell if if needs to fetch or not.

Is it possible or is there an existing solution for this without having to load the the data of category with an Id of 1?

**Comment by Lynesth** [comment]
Hey there,

Not sure if I got it right but here goes.
If you want to set the Category to your SubCategory without having to load the Category, you can directly set `category_id` instead of `category`:

```php
$sub = R::dispense('subcategory');
$sub->name = "Hello";
$sub->category_id = 1;
R::store($sub);
```

Let me know if that wasn't what you meant.

**Comment by JeromeDeLeon** [comment]
That was fast! Thanks!
