### ISSUE TITLE
maximum function nesting level with OneToOne relation

### ISSUE THREAD

**Issue by romainlavabre** [gabordemooij/redbean#832]
Hello,

In my e-commerce application, I have a OneToOne relationship:

A product bearing its graphic rule
This graphic rule carries this product

This design is ideal for my application.

The error is a nested maximum function, my usage is bad or I can offer a patch?

Thanks in advance and thanks again for redbean

EDIT: 
> For creation of the graphic rule (product already exists in database)

`$product->setGraphicRule($graphicRule);`

`$graphicRule->setProduct($product);`

`// Abstraction to convert to bean`

`R::store($graphicRule)`

> Product 

`private ?GraphicRuleProduct $graphicRuleProduct;`

> GraphicRuleProduct

`private Product $product`

**Comment by Lynesth** [comment]
Hey there.

You'll have to be more precise as to what error you are getting.
If you could provide the piece of code that gives the error as well, that would be nice.

Also, were tables created automatically using RedBeanPHP ? If they were not, could you also show the schema of those 2 tables please ?

Thank you.

**Comment by romainlavabre** [comment]
My initial post has been updated, the schema was created by redbean

**Comment by Lynesth** [comment]
I see. You indeed cannot do that using RedBeanPHP.
As stated in the manual: _"RedBeanPHP one-to-one relations are an anti-pattern, the fields should belong to the same bean."_

As I suppose that's not what you want to do, you then have 2 solutions:

#### 1. Only one of them hold the foreign key linking to the other and you need to use `find` to load it from the other one.

Example:
```php
$product = R::dispense('product');
$product->prop = 'value';

$graphicRule = R::dispense('graphicrule');
$graphicRule->prop = 'value';

$product->graphicrule = $graphicRule;

R::store($product);

##############

// Loading graphicRule from a product:
$product = R::load('product', $id);
$graphicrule = $product->graphicrule;

// Loading product from a graphicRule:
$graphicRule = R::load('graphicrule', $id);
$product = R::find('product', ' graphicrule_id = ? ', $graphicRule->id);
```

--------

#### 2. You make sure they both have the same id which makes things easy to find them.

Example:
```php
$product = R::dispense('product');
$product->prop = 'value';
R::store($product);

$graphicRule = R::dispense('graphicrule');
$graphicRule->prop = 'value';
$graphicRule->id = $product->id;
R::store($graphicRule);

##############

// Loading graphicRule from a product:
$product = R::load('product', $id);
$graphicrule = R::load('graphicrule', $product->id);

// Loading product from a graphicRule:
$graphicRule = R::load('graphicrule', $id);
$product = R::load('product', ' graphicrule->id);

// Loading both at the same time:
list($product, $graphicRule) = R::loadMulti('product,graphicrule', $id);
```

**Comment by romainlavabre** [comment]
Thank you for these solutions (and responsiveness), i missed this line in your documentation. 

Good continuation.
