### ISSUE TITLE
Website typo (Meta Mask)

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#833]
I believe there's a typo in the snippet on the main RedBean website related to Meta Mask. For example:

> Meta Mask (4.3.2)
> As of version 4.3.2 you can specify a meta mask when converting rows to beans:
> 
> ```php
> $rows = R::getRow( 'SELECT book.*, count( page.id ) AS meta_pages... ' );
> $book = R::convertToBean( 'book', $data, 'meta_' );
> $queryData = $book->getMeta('data.bundle');
> echo $queryData['meta_pages'];
> ```

I'm guessing that in the snippet, `$data` should be `$rows`?

**Comment by gabordemooij** [comment]
Thanks for reporting, has been fixed!
