### ISSUE TITLE
MySQL SSL connect

### ISSUE THREAD

**Issue by razvanioan** [gabordemooij/redbean#834]
I've seen that a new Facade method has been introduced (`useMysqlSSL()`) but I cannot figure out how to properly use it.

The problem is that it tries to setAttributes on the PDO object, which first has to connect to the DB in order to exists, but connecting w/o SSL options fails.

Normally we should configure this upon PDO initialisation, with options parameter which is missing from RedBean.

It seems that I also cannot use `Driver->setPDO($customPDO);`, there are more other issues ...

So, where can we find a proper way to connect to MySQL using SSL ?

**Comment by Lynesth** [comment]
Hey,

You should probably be able to use it like this:

```php
R::addDatabase( 'mydb', $host, $user, $password, $frozen );
R::useMysqlSSL( 'key.pem', 'cert.pem', 'cacert.pem', 'mydb' );
R::selectDatabase( 'mydb' );
```
I am not able to test it at the moment, so let me know.

Lyn.

**Comment by razvanioan** [comment]
Nope, it is not working, and for the same reason I guess.

Even if using `R::setup()` or `R::addDataBase()` it's not connecting to it, `R::useMysqlSSL()` forces the connection when it retrieves the PDO handler, check [line 766 from Driver\RPDO class](https://github.com/gabordemooij/redbean/blob/master/RedBeanPHP/Driver/RPDO.php#L766)

The only proper way to achieve this is by using PDO connection options parameter, check [here](https://www.saotn.org/how-to-use-ssl-in-php-data-objects-pdo-mysql/)

Otherwise it's a never-ending story: PDO needs SSL conf in order to connect the DB and we're trying to connect in order to configure that SSL (which raises error, as it's not configured)

**Comment by gabordemooij** [comment]
Does this help? @razvanioan 
https://github.com/gabordemooij/redbean/commit/e20fc8d33d241b751205b3db02c7e9191b8db51e

**Comment by razvanioan** [comment]
@gabordemooij 

Almost there, but you still have an error.

I think that in Facade::createToolbox() you're having a boolean extra parameter TRUE for the RPDO Driver which doesn't have it's place inside the constructor !

```php
$db = new RPDO( $dsn, $username, $password, TRUE, $options );
...
public function __construct( $dsn, $user = NULL, $pass = NULL, $options = array() )
```

**Comment by gabordemooij** [comment]
Hm, strange, I cant remember why that is there, removed it

**Comment by razvanioan** [comment]
Ok, now it's working !

**Comment by Jemt** [comment]
There is no longer a useMysqlSSL(...) function for this. Instead pass PDO options to the setup(..) function, e.g.:
```
$options = array(
	\PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8",
	\PDO::MYSQL_ATTR_SSL_CA => dirname(__FILE__) . "/../../ca-certificate.crt",
	\PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false
);

R::setup("mysql:host=hostname;port=25060;dbname=mydatabase, $username, $password, false, false, $options);
```
