### ISSUE TITLE
setPDO doesn't work

### ISSUE THREAD

**Issue by razvanioan** [gabordemooij/redbean#835]
While searching for an easy workaround for the https://github.com/gabordemooij/redbean/issues/834 issue I was trying to use the `RPDO->setPDO()` method.

It didn't work, because the connect() method would have been replaced the pdo.

Thus if I've modified the setPDO method to tell that it is connected it was working fine !

```php
public function setPDO(\PDO $pdo)
{
    $this->pdo = $pdo;

    $this->isConnected = true;
    $this->setEncoding();
}
```

**Comment by marios88** [comment]
To reuse a pdo object i use the following code

```
...
            //reuse main connection
            $db = new \RedBeanPHP\Driver\RPDO( $conn_id );
            R::addToolBoxWithKey('default',$this->create_toolbox($db, FALSE));
            R::selectDatabase('default');
            $this->set_aliases();
            R::setAutoResolve(TRUE);
            R::usePartialBeans( TRUE );
...
    protected function create_toolbox(\RedBeanPHP\Driver\RPDO $db,bool $frozen): \RedBeanPHP\ToolBox {
        
        //Logging?
        if(ENVIRONMENT === 'development'){
            $db = $this->set_debug_mode($db);
        }
        
        $adapter = new \RedBeanPHP\Adapter\DBAdapter( $db );
        $writer = new \RedBeanPHP\QueryWriter\MySQL( $adapter );
        $oodb = new \RedBeanPHP\OODB( $writer, $frozen );
        return new \RedBeanPHP\ToolBox( $oodb, $adapter, $writer );
    }
```

**Comment by razvanioan** [comment]
@marios88 Because I couldn't connect to MySQL server which required SSL configuration (see https://github.com/gabordemooij/redbean/issues/834 for details) as it could only be configured via options parameter which was completely missing from RedBean until yesterday, I was trying to do something like this, taking advantage of setting custom PDO to RedBean:

```php
$options = [
  \PDO::MYSQL_ATTR_SSL_CA => $CAcertPath,
];

$pdo = new \PDO($dsn, $user, $pass, $options);

R::setup();
R::getDataBaseAdapter()->getDataBase()->setPDO($pdo);
```

This was not working as expected, and by investigating, the `Facade::connect()` method was replacing the internal `$pdo`, so just by modifying the `RPDO::setPDO()` method just to make the `$isConnected` parameter true, was working fine (the pdo was not replaced anymore)

So what I want to tell is that if you set manually the pdo, the framework has to know that's already connected.

Or at least put a bool parameter $connected to the setPDO() method, and the developer can choose what's right, but 99% of the time when this method is needed, it has to be true ;)

**Comment by marios88** [comment]
here is a more complete example

```php
\R::setup();
$pdo = get_pdo_object_from_somewhere();
$db = new \RedBeanPHP\Driver\RPDO( $pdo );

$adapter = new \RedBeanPHP\Adapter\DBAdapter( $db );
$writer = new \RedBeanPHP\QueryWriter\MySQL( $adapter );
$oodb = new \RedBeanPHP\OODB( $writer, $frozen );
$toolbox = \RedBeanPHP\ToolBox( $oodb, $adapter, $writer );

\R::addToolBoxWithKey('default',$toolbox);
\R::selectDatabase('default');
\R::setAutoResolve(TRUE);
\R::usePartialBeans( TRUE );
```

This comes with the added bonus that you can extend all the core classes

**Comment by gabordemooij** [comment]
@razvanioan 
https://github.com/gabordemooij/redbean/commit/df772a0d89a83552575d07e740253699933e0440

**Comment by razvanioan** [comment]
@marios88 Thx

That seems a lot of code just to build something which normally the simple setPDO() would have achieved
The issue I've opened was about the `setPDO()` method, not an alternative which is nice to have anyway here as an example

@gabordemooij Thx

This should be more than enough
I haven't tested though, but it looks ok ;)

**Comment by gabordemooij** [comment]
Further improvement
https://github.com/gabordemooij/redbean/commit/f663e9597893e8d21a801c104d2e8e76061e3561

If you define initcode for SQL or PHP this will also be taken into account (if you like).

**Comment by razvanioan** [comment]
@gabordemooij 

That's nice, but I suppose you'd have to allow stringifyFetches parameter in the same options array

**Comment by gabordemooij** [comment]
I agree
https://github.com/gabordemooij/redbean/commit/41131338b249fee28746e1636515fb79b38f5e89
