### ISSUE TITLE
Unable to use __call() with Model

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#838]
For convenience, I'd sometimes like to use getters and setters to manipulate Beans. This allows us to extract out data management within a system to Repositories and maintain testable code. 

For some reason, using the `__call` magic method on a Bean Model doesn't seem to work. For example, my Models all extend a base class (`Entity`), which looks like this:

```php
<?php

namespace Example\API\Entity;

use Example\API\Exception\EntityException;

class Entity extends \RedBeanPHP\SimpleModel
{
  # Handle get* and set*:
  function __call($method, $params)
  {
    $start = substr($method, 0, 3);

    if( $start == 'get' || $start == 'set' )
    {
      $property = lcfirst(substr($method, 3));

      # It's a getter:
      if( $start == 'get' )
      {
        return $this->bean->$property;
      }

      # No need for else, can only be reached if setter:
      if( count($params) != 1 )
      {
        throw new EntityExcpetion('Setter method for '.$property.' expects 1 parameter.');
      }

      $this->bean->$property = $params[0];

      return $this;
    }
  }	
}
```

When we extend the base class, the `__call` method is never executed, for example:

```php
$user = R::load('user', 1);

echo $user->getForename(); # never called
echo $user->forename;      # correctly returns 'Ben'
```

Similarly, calling a method that does not exist on a Bean Model does not leak an error or exception:

```php
echo $user->nonExistentMethod(); # returns null
```

This is obviously a design feature in RedBean, but is there any way for us to still leverage `__call()` on a Model?

**Comment by Lynesth** [comment]
The way RedBean does its magic is by checking if the model has the specific function declared or not, using:
```php
if ( !method_exists($this->__info['model'], $method) ) {
```
In your case, `$method` is equal to `getForename`, so you can guess why it doesn't work.

We could probably modify it that way:
```php
if ( !method_exists($this->__info['model'], $method) && !method_exists($this->info['model'], '__call')) {
```
Just need to make sure it doesn't break anything, but it probably shouldn't.

Meanwhile you can either:
- Patch yourself that specific line in RedBean to behave as you want it to
- `box()` your bean when calling your "magic" functions `$user->box()->getForename();`

**Comment by benmajor** [comment]
Thanks for fast reply, @Lynesth! I think that it would be much better to check against `is_callable`, as it would be nice to utilise the `__call` method as indicated.

I've just tried your latest commit, and it seems to work exactly fine. I don't think that there should be any implications to adding it to the core, and I look forward to seeing in the next release if you think it's worthwhile!

Thanks again :)
