### ISSUE TITLE
Unnecessary widening when storing 1 in a MySQL TINYINT(1) column

### ISSUE THREAD

**Issue by davidsickmiller** [gabordemooij/redbean#839]
Hi,

I've noticed that if I have a database table like this:
```
CREATE TABLE `sometable` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `somecol` tinyint(1) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

And I run some code like this:
```
$bean = R::dispense('sometable');
$bean->somecol = 1;
R::store($bean);
```

RedBean, in Fluid mode, will change the schema of somecol to `int(11) unsigned`.

That seems unnecessary.

It works as desired if I set the value to `true`.  Looking at MySQL::scanType(), I think it would also work if I set the value to `'1'`:
```
if ( $value === FALSE || $value === TRUE || $value === '0' || $value === '1' ) {
	return MySQL::C_DATATYPE_BOOL;
}
```

It seems like we should also use BOOL for `=== 0` and `=== 1` since they would fit fine inside TINYINT(1).

Thoughts?

**Comment by gabordemooij** [comment]
Agreed, I'll write a unit test to confirm this

**Comment by gabordemooij** [comment]
https://github.com/gabordemooij/redbean/commit/9240f1d8c0d80802139042921c0d1d5e4a3c89d8
