### ISSUE TITLE
Documentation: Duplicate

### ISSUE THREAD

**Issue by sah-comp** [gabordemooij/redbean#843]
Just one minor thing I came across:

On [RedbeanPHP.com](https://redbeanphp.com/index.php?p=/duplicate) the code example for duplicate should say:

```
$duplicate->name = 'copy!';
```

instead of 

```
$book->name = 'copy!';
```

**Comment by gabordemooij** [comment]
Thanks for reporting. This bug has been fixed.

https://redbeanphp.com/index.php?p=/duplicate
