### ISSUE TITLE
Question about autocomplete

### ISSUE THREAD

**Issue by marios88** [gabordemooij/redbean#844]
Currently using PHPstorm and have not found a way to make properties auto-complete

Does anyone have a working solution for autocompletion of bean properties?

**Comment by gabordemooij** [comment]
I guess the IDE tries to infer the properties from source code, which does not exist in the case of RedBeanPHP. We could trick IDEs porbably by having a script that creates 'shadow' files from the database schema, just to fool the IDE, but that seems a bit far-fetched.

**Comment by marios88** [comment]
Yea that doesn't sound like something that could work automatically.

How about using setters and getters?
