### ISSUE TITLE
Documentation : Look Functions

### ISSUE THREAD

**Issue by esmupamungkas** [gabordemooij/redbean#845]
A minor issue about the documentation [here on data tools section](https://www.redbeanphp.com/index.php?p=/data_tools).

Code example is still using :
`R::getLook()->look()`
While it's considered deprecated (also shown being strikethrough by intelephense) and we can use R::Look() directly.

**Comment by gabordemooij** [comment]
Thanks for reporting this, the issue has been fixed.
