### ISSUE TITLE
fetchAs() not working inside model

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#846]
When working with Models inside of RedBean, I don't seem to be able to get the `fetchAs()` method to function correctly. 

For example, I have an `Image` bean that is assigned to the `avatar_id` property of a `User` bean. Usually, we could access this using the following:

```php
$user = R::load('user', 1);
$user->fetchAs('image')->avatar;
```

However, when we try the above inside a model, this simply returns an empty Bean. For example:

```php
public function getAvatar()
{
  if( is_null($this->bean->avatar) )
  {
    $em = new EntityManager();
    return $em->getRepository('image')->load(1);
  }
  
  return $this->bean->fetchAs('image')->avatar;
}
```

The above method returns an empty Bean of type `avatar`, however, instead of passing through the model, the following will correctly return the `Image` bean:

```php
$user2 = R::load('user', 1);
$user2->fetchAs('image')->avatar;
```

**Comment by benmajor** [comment]
As a post script to the above, both `$this->bean` and `$user2` are the same entity.

**Comment by gabordemooij** [comment]
Strange, over here, this works fine:

```
R::store(R::dispense([
	'_type'=>'user',
	'avatar' => [
		'_type' => 'image',
		'url'   => 'me.jpg'
	]
]));

class Model_User extends \RedBeanPHP\SimpleModel {
	public function getAvatar() {
	  return $this->bean->fetchAs('image')->avatar;
	}
}

$user = R::findOne('user');
var_dump($user->fetchAs('image')->avatar->url);
var_dump($user->getAvatar()->url);
```

Output:

```
string(6) "me.jpg"
string(6) "me.jpg"
```

**Comment by benmajor** [comment]
Okay, after some digging around, the troublesome line appears to be:

```php
if( is_null($this->bean->avatar) )
```

If we comment out the `if()` clause, it correctly returns the value:

```php
public function getAvatar()
{
  /*
  if( is_null($this->bean->avatar) )
  {
    $em = new EntityManager();
    return $em->getRepository('image')->load(1);
  }
  */

  return $this->bean->fetchAs('image')->avatar;
}
```

This correctly returns the avatar `image` Bean. Similarly, updating the clause as follows also works:

```php
public function getAvatar()
{
  if( is_null($this->bean->fetchAs('image')->avatar) )
  {
    $em = new EntityManager();
    return $em->getRepository('image')->load(1);
  }
  
  return $this->bean->fetchAs('image')->avatar;
}
```

What's bizarre though, is that the `is_null()` doesn't seem to be getting executed. For example, using the original method signature of:

```php
public function getAvatar()
{
  if( is_null($this->bean->avatar) )
  {
    die('here');
    $em = new EntityManager();
    return $em->getRepository('image')->load(1);
  }
  
  return $this->bean->fetchAs('image')->avatar;
}
```

We never see the `here` died out. 

Anyway, it seems that checking `is_null()` and using `fetchAs()` seems to solve the issue. Thanks for your time!

**Comment by Lynesth** [comment]
Doing `if( is_null($this->bean->avatar) )` calls the magic __get which actually tries to retrieve an avatar bean. Since it can't, it sets it to an empty bean.

If I understood correctly, what you probably want to do is:
```php
public function getAvatar()
{
  $avatar = $this->bean->fetchAs('image')->avatar;

  if (empty($avatar->id)) {
    $em = new EntityManager();
    return $em->getRepository('image')->load(1);
  }
  
  return $avatar;
}
```

**Comment by benmajor** [comment]
Yes, it seems odd though that `if( is_null($this->bean->fetchAs('image')->avatar) )` was returning `false` (since the `die()` was never executed). Anyway, changing the test around as indicated seems to have done the trick!

Thanks as always!
