### ISSUE TITLE
Get bean parameter type

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#847]
This is more of a question than an issue, so apologies!

Is it possible for us to determine the schema type of a field without using `R::inspect()`? For example, I am currently using models and extending a base entity that has a magic getter defined as follows:

```php
public function __call($method, $params)
{
	$start = substr($method, 0, 3);

	if( $start == 'get' || $start == 'set' )
	{
		$property = lcfirst(substr($method, 3));

		# It's a getter:
		if( $start == 'get' )
		{
			return $this->bean->$property;
		}

		# Below here is a setter:

		# If there aren't any params:
		if( ! count($params) )
		{
			throw new EntityExcpetion('Setter for '.$property.' expects at least 1 parameter.');
		}

		$this->bean->$property = $params[0];

		# Return self to preserve method-chaining:
		return $this;
	}
}
```

What I would like to do, is if the type of field being accessed is a `DateTime` field, the getter should return a new `DateTime` object in PHP.  What is the best way to determine the field type of `$this->bean->$property` given the above scenario?

**Comment by gabordemooij** [comment]
I would say:

`$date = new DateTime( $this->bean->date );`


I see nothing wrong with that, why would you add this to the 'magic' ?

**Comment by Lynesth** [comment]
Github issues are also for questions :)
There are a couple "solutions" to what you want to achieve.

**First** of all, you can use `inspect()`. Do it only once per model and cache the values.

**Second**, if you don't have too many different types to process, you can analyze the value to see if it maches something specific.
```php
# It's a getter:
if( $start == 'get' ) {
	$value = $this->bean->{$property};
	if ($date = DateTime::createFromFormat('Y-m-d H:i:s', $value) && $date->format('Y-m-d H:i:s') === $value) {
		// It's a date !
		return $date;
	}
	return $value;
}
```

**Third** you can tell your getter what kind of value you are retrieving
```php
# It's a getter:
if( $start == 'get' ) {
	$value = $this->bean->{$property};
	if (empty($params)) {
		return $value
	}
	switch ($params[0]) {
		case 'date':
			return new DateTime($value);
		default:
			return $value;
	}
}

// Then you'd call it like
$user->getLastlogin('date');

// Note that I'd recommend using constants and not strings for the types
```

**Comment by benmajor** [comment]
Thanks for the replies as usual guys!

Actually having given this a little more thought, I think that regexing the bean's value and then returning a `DateTime` object may be the best approach. I just wanted to check to see if there was a more convenient way of doing it inside RedBean.
