### ISSUE TITLE
Parse Error : Parse error: syntax error, unexpected namespaced name "implements\IteratorAggregate", expecting "{" in {PATH\htdocs OR www}\rb.php on line 1615

### ISSUE THREAD

**Issue by Shabasha** [gabordemooij/redbean#848]
[ First of all , I apologize for the Bad English Writting or Spelling i may have ]

After downloading the latest version of RedBean PHP Class , i could not be able to fix this issue while attempting to include or require the PHP Class in my script. The Problem is generating when trying to parse the rb.php Class , so my script is similar to a simple require or require_once :

`<?php require_once('rb.php'); `

Nothing else.

**Comment by gabordemooij** [comment]
It's a change in PHP8.
This has been fixed in the master branch, a new version has been released:

https://redbeanphp.com/index.php?p=/download
https://redbeanphp.com/index.php?p=/changelog#v562
e55db41195030c14b4309081d937f4102e126e75
