### ISSUE TITLE
Counting in trees

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#851]
Once again, a question rather than a bug!

In our schema, we have Collection beans, which have ownCategory lists assigned to them. Categories are treated as trees, and can be of unlimited depth. Item beans are then added to Categories at any depth. A simple demo is as follows:

```
Collection 1
  - Category 1
    - Item C
  - Category 2
    - Category 2.2
      - Item A
      - Item B
```

I am currently trying to figure out the most efficient way of counting all Item beans that have a parent of a specific Collection bean. Since Items can exist at any depth within the Category tree, and only top-level Categories hold a reference to the Collection bean, we can't simply look against the Collection ID. 

Given the above example, we would like to retrieve `3` as the number of Item beans ultimately contained within `Collection 1`.

What are the options here, if any, without resorting to messy lists or indeed using the `traverse()` method?

**Comment by Rayraz** [comment]
Not an RB-specific solution, but you might want to look into Modified Preorder Tree Traversal (MPTT for short): https://www.sitepoint.com/hierarchical-data-database-2/

It's been a while since I used something like that, but I recall great performance for things like retrieving sub-trees. It does come at a performance cost when modifying the tree though, due to the need to re-order it.

**Comment by gabordemooij** [comment]
If your database is modern enough, I recommend to use

```
$count = R::countChildren( $newsArticle, ' WHERE title = ? ', [ $t ] );
$count = R::countParents( $newsArticle, ' WHERE title = :t ', [ ':t' => $t ] );
```

these make use of CTE (common table expressions) a native DB mechanism to deal with tree structures.
Also see: https://redbeanphp.com/index.php?p=/trees

**Comment by benmajor** [comment]
Thanks for the answers, but they seem to be related to counting hierarchies. The issue we have with our schema is that we want to count all Item beans that ultimately exist in a Collection bean, not to count the number of Category beans at any depth.

**Comment by Rayraz** [comment]
Off the top of my head I can think of three approaches, though there are probably many others.

**1st approach:**
- First retrieve all top-level categories that reference the desired collection ID.
- Then use MPTT to retrieve the sub-trees of these top-level categories.
- Finally retrieve all items that reference at least one of the categories in the retrieved sub-trees.

The advantage of this approach is that it limits your pre-ordered tree to only the categories. Assuming there will be far fewer categories than items this might help to keep update performance in check. The disadvantage is that your search still might require more and possibly slower queries than you'd like.


**2nd approach:**
Create a new bean type that describes the relationships between collections, categories and items. Let's call this bean type "Node" for simplicity. A "Node" bean would have the following fields: 
- id (pk)
- beantype (collection, category, item)
- beanid (the id of the collection or category or item)
- left (MPTT)
- right (MPTT)
You can then retrieve all nodes in the tree with a beantype of 'item' which belong to the subtree of the node that references the desired collection.

The advantage of this is that lookup queries will be relatively simple and quite fast. The disadvantage is that update performance will suffer, in particular if there will be many items.

**3rd approach**
Use MPTT for the category tree itself, making it easy to retrieve the ancestry of any category. Then, any time you attach an item to a category, you retrieve the ancestry of that category and store a list linking the item directly to each ancestor. This way you're basically building a flat list that links an item directly to all it's ancestors.

The advantage of this is that you're keeping update performance in check when moving items within the tree, even if there are many items. You'll also still have pretty good lookup performance.

The downside is that things might get complicated and slow when you move a category with many items from one location in the tree to another, though it should be possible to work out some optimizations if you include the depth of an item's ancestor for each item-ancestor relation.

**wildcard**
Another option might be to use a graph database. It seems to me that could possibly be more suited to what you're trying to do, but to be honest I have no experience with those.

**Comment by benmajor** [comment]
Yes, having given it some more thought, I'm also beginning to think that option 1 is the most viable. I don't think there's any other way to do it than to use an iterable and generate the category IDs that exist within the Collection. The method won't be called too regularly, so it could be combined to generate the total number of categories inside the collection at the same time. 

Thanks for your time and input on this -- I'll go ahead and close the issue since this seems to be the most efficient use.
