### ISSUE TITLE
Deprecated functions in PHP7.4

### ISSUE THREAD

**Issue by BOAWEB** [gabordemooij/redbean#853]
When using the latest version of RedBeanPHP (dev-master) on PHP7.4, I get a deprecation warning:

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /vendor/gabordemooij/redbean/RedBeanPHP/OODBBean.php on line 1199

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /vendor/gabordemooij/redbean/RedBeanPHP/OODBBean.php on line 1177

Could this be resolved?
Thanks!

**Comment by gabordemooij** [comment]
Oh God.. Why on earth do they deprecate this? PHP is written by complete and utter incompetent morons.

**Comment by gabordemooij** [comment]
Don't worry, I will update RedBeanPHP

**Comment by gabordemooij** [comment]
I will replace those array_key_exists calls with property_exists calls.

**Comment by gabordemooij** [comment]
This seems quite strange, the properties property should be an array, so this warning should not occur, can you by any chance dump the contents of $this->properties at that stage? Just to be sure?

**Comment by gabordemooij** [comment]
Unable to reproduce this issue with proper arguments.
