### ISSUE TITLE
Need a way to force own and shared lists to be reloaded.

### ISSUE THREAD

**Issue by rivets** [gabordemooij/redbean#854]
In-memory own and shared lists seem to persist across deletions of objects in the lists and across calls of fresh on the bean. There needs to be a way of forcing the lists to clear or to be reloaded. (For some example code that shows the issue see my recent forum post)

**Comment by gabordemooij** [comment]
Euh, nope.

**Comment by gabordemooij** [comment]
`$bean = $bean->fresh;`

clearing the bean's state is quite complex, this will just do the trick.

**Comment by rivets** [comment]
No it doesn't

**Comment by rivets** [comment]
Can you explain why that works.

**Comment by Lynesth** [comment]
`fresh` does not modify the bean in place but returns a new bean, that's why you need to assign it to a variable.

**Comment by rivets** [comment]
OK - that's not how I would implement it, but never mind.

**Comment by rivets** [comment]
BUT....how do I use this inside a model?

$this->bean = $this->bean->fresh();

will that work? If you have methods returning own/shared that may have been modified then you need to do this every time you call the method to guarantee a correct list.

**Comment by Lynesth** [comment]
I'm not sure I understand. If you want to simply reload an ownList, you can either `unset` it or use `all()`.
Using your example from the forum:
```php
\R::trashAll([$bns[3], $bns[4]]);
echo count($mb->all()->ownBeanxList).PHP_EOL;
// OR
\R::trashAll([$bns[3], $bns[4]]);
unset($mb->ownBeanxList);
echo count($mb->ownBeanxList).PHP_EOL;
```
This information can be found [here](https://redbeanphp.com/index.php?p=/using_sql_snippets) in the "Reloading a list" section.

**Comment by rivets** [comment]
Ok. I have not seen that all() call before
