### ISSUE TITLE
Combining aliases

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#856]
Another question for the community, really. Please consider the following schema:

**user:**
| id | name |
| --- | --- |
| 1 | John Doe |
| 2 | Jane Doe |

**conversation:**
| id | sender_id | recipient_id | date | last_message |
| -- | --- | --- | --- | -- |
| 1 | 2 | 1 | 2021-02-09 10:00:00 | 2021-02-09 10:00:00 |
| 2 | 1 | 2 | 2021-02-10 09:58:58 | 2021-02-10 09:58:58 |

Both `conversation.sender_id` and `conversation.recipient_id` are foreign keys to `user.id`. Typically, to get a list of conversations where a specific user is the sender, we can do the following:

```php
$user->alias('sender')->ownConversationList
```

However, if I want to obtain all `conversation` beans where a specific user is *either* the sender or the recipient, at the moment I have to hand-craft the `find()` method using something like:

```php
R::find(
  'conversation', 
  'sender_id = ? OR recipient_id = ?', 
  [ $user->id, $user->id ]
);
```

This isn't a huge issue, but it would be nice to be able to use RedBean's built-in counting and retrieval functions, for example something like:

```php
$user->alias(['sender', 'recipient'])->countOwn('conversation');
$user->alias(['sender', 'recipient'])->ownConversationList;
```

Would it be possible to add such functionality, or is this outside the scope of the project?

**Comment by gabordemooij** [comment]
Interesting idea, thanks for reporting, I will look into this.

**Comment by gabordemooij** [comment]
It seems that this poses a problem with the other way around, if you add new beans to a doubly aliased list, it's impossible to determine to which list these beans should be added (i.e. what parent link should be set). Of course, we could fix this by requiring the user to explicitly add beans to a list but that would become rather cumbersome. It seems that using plain SQL would be the best option here.

**Comment by benmajor** [comment]
No problem, @gabordemooij. Thank you for investigating!
