### ISSUE TITLE
Composer notice

### ISSUE THREAD

**Issue by vytsci** [gabordemooij/redbean#857]
How on earth you came on a conclusion about not using package managers? Do you realize how much time is being saved while using package managers? Please stop misleading people. Injection can happen any time, package managers are not responsible for this. It just happens because of simplicity of installing libraries and not because of manager itself.
If you hammer your hand with a hammer every time you try to hammer a nail, is it hammers fault?

**Comment by gabordemooij** [comment]
Fuck off faggot.

**Comment by gabordemooij** [comment]
Your comment makes no sense. Not using package managers reduces the risk of injection.

**Comment by vytsci** [comment]
Your code is unknown, how downloading it via single file is more risk than via package manager? Package manager is a tool and if someone uses a tool incorrectly there are consequences, but its not a tools fault. Downloading a file philosophy is even more dangerous imagine everyone downloading files and injecting them manually, without any checks performed by package managers, rating systems. I understand your point, but you should put your effort into teaching people how to use a good tool rather than lead to even more riskier habit of downloading random files.
