### ISSUE TITLE
Spatial datatype support

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#859]
Are there any plans to support spatial datatypes in MySQL for RedBean, or is this something that should be handled via a plugin?

I often work with lots of long/lat data, and it would be nice to be able to leverage the power of MySQL's `POINT` datatype (and others) directly inside RedBean. At the moment, we have to rely on passing in the longitude and latitude as `DOUBLE` types.

Thanks!

**Comment by benmajor** [comment]
Sorry, just found in the docs that we can pass in  `(1,2)`...

**Comment by benmajor** [comment]
Sorry to re-open this issue, but is there any possibility we can get this support in MySQL? It's fairly well rolled out (MySQL >= 8), and would be extremely useful support to add into RedBean!

I saw @gabordemooij's issue (https://github.com/gabordemooij/redbean/issues/64) where he seemed to indicate that support for this should be handled via community plugins. Is that still the consensus?

**Comment by gabordemooij** [comment]
I will look into this again. Times change, who knows!

**Comment by gabordemooij** [comment]
As far as I can see, GIS support is still rather an after thought with MariaBD, it still needs functions to insert or read geo-data (https://mariadb.com/kb/en/multilinestring/). You can use this using R::bind() (https://redbeanphp.com/index.php?p=/database#column_functions) - Unless MariaDB/MySQL starts implementing proper, native support for GIS, it will be quite difficult to support this in fluid mode. Same applies to MySQL (https://dev.mysql.com/doc/refman/8.0/en/gis-data-formats.html).
