### ISSUE TITLE
Problem with exportAll()

### ISSUE THREAD

**Issue by russeljo** [gabordemooij/redbean#861]
Manufacturer has many Products (One2Many)
Each Product has Manufacturer and other parent Entities. And Product has childrens(One2Many) and Many2Many relations.
When i do R::exportAll($Manufacturers) and R::exportAll($Manufacturers, TRUE) - result array includes for every manufacturer list of all related products:
"ownProducts" => [ list of products ]
And there one thing: products in this list has only "own" and "shared"(many2many) relations, but there's no parents, so, to get f.e. manufacturer of this product or another parent relation i need to do extended query for every poduct. But i need all in one array :) 
suggestion?

**Comment by russeljo** [comment]
And each time i need to keep in mind this issue and loop every time to add parents to element.

**Comment by benmajor** [comment]
Can you post your schema, along with your expected output? It's a little confusing from your description what you're trying to achieve here.

**Comment by russeljo** [comment]
Sorry for bad english.

![image](https://user-images.githubusercontent.com/11944160/111630828-324fae80-880c-11eb-867f-71f65688fcfc.png)
Manufacturer don't have parens, but has childrens. When i do exportAll() for Manufacturer, in array we have ["ownStages"]=>[].
In ["ownStages"] we have list of stages with their childs and many2many: ["ownSections"], ["sharedShafts"],["ownShafts_stages"].
```
Manufacturer: [
id=> 1,
["ownStages"] => [
    [
        stageId=> 45,
        ["ownSections"]=>[...], 
        ["sharedShafts"]=>[...],
        ["ownShafts_stages"]=>[...]
    ],
     ...
]
];
```

But every stage have parents: manufaturer and housing. When do exportAll(stage, true) for stage, in array exist 2 parent fields maufacturer and housing.
```
$stage: [
        stageId=> 45,
        manufacturer=>[],
        housing=>[],
        ["ownSections"]=>[...], 
        ["sharedShafts"]=>[...],
        ["ownShafts_stages"]=>[...]

]
```

So, problem, when i do exportAll($manufacturer, true) - there is no parent's fields in child stage. And i need loop all stages to get parens. Task is get stages grouped by manufacturers, and every stage need complete information like it was exportAll(stage, true). 
Now, i do exportAll for all manufacturers and for all stages and then loop manufacturers and ownStages to replace with stages with complete info.
