### ISSUE TITLE
Issue with extensions loading via Composer

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#862]
There seems to be an issue with loading extensions via Composer. Please see https://github.com/benmajor/RedSeed/issues/1.

In the above repo, extensions have been loaded via the `R::ext()` method, but when Composer is used, it's necessary to run `class_exists()` in order to have RedBean register that the class itself exists. For example, the following will throw an exception in RedBean:

```php

require 'vendor/autoload.php';

use RedBeanPHP\R;

R::setup(
    'mysql:dbname=redseed;host=localhost',
    'root',
    'root'
);

R::seed('user', 10, [
    'forename' => 'word(3,10)',
    'surname' => 'word(5,15)',
    'email' => 'email()'
]);
```

Such as:

> Plugin 'seed' does not exist, add this plugin using: `R::ext('seed')`

But running the following works as expected:

```php
require 'vendor/autoload.php';

use RedBeanPHP\R;

class_exists('BenMajor\\RedSeed\\RedSeed');

R::setup(
    'mysql:dbname=redseed;host=localhost',
    'root',
    'root'
);

R::seed('user', 10, [
    'forename' => 'word(3,10)',
    'surname' => 'word(5,15)',
    'email' => 'email()'
]);
```

Are there any known bugs for `R::ext()`? It seems strange that even calling `class_exists()` seems to fix whatever issue there is?

**Comment by gabordemooij** [comment]
Might be related to this old issue: https://github.com/gabordemooij/redbean/issues/294 ?

**Comment by gabordemooij** [comment]
and https://github.com/gabordemooij/redbean/issues/221
