### ISSUE TITLE
is there some way to get bean or array with values with type same in DB?

### ISSUE THREAD

**Issue by russeljo** [gabordemooij/redbean#863]
All methods descriped in docs return values in string type. Maybe i miss something, and there some way to get typed values?
I use MySQL, maybe better use Postgres or smth else?

i found that:
$mysqli->options(MYSQLI_OPT_INT_AND_FLOAT_NATIVE, TRUE);
How can i set it for R? at least for getAll()

I found that mysqlnd - return floats, integers

**Comment by russeljo** [comment]
i found that:
$mysqli->options(MYSQLI_OPT_INT_AND_FLOAT_NATIVE, TRUE);

How can i set it for R?

**Comment by gabordemooij** [comment]
PHP is a dynamically typed language, so you can just cast a string to a boolean or a number. Also, type systems between programming languages and database engines might not map perfectly. So I would recommend to just use the string values.
