### ISSUE TITLE
R::exportAll() low performance when a lot of childes

### ISSUE THREAD

**Issue by russeljo** [gabordemooij/redbean#864]
I have 3 records in table 'manufacturers', and each manufacturer has ~1000 stages (manufacturer 'ownStages').
I try get list of manufacturers: $this->list = R::exportAll( $beans  );
And it took a lot of time, when only 3 records in table. 
Is it possible get list in array without childrens?

**Comment by russeljo** [comment]
look like sql be better
$list = R::getAll( 'SELECT * FROM tablename ' );

**Comment by gabordemooij** [comment]
I recommend to use just SQL here.
