### ISSUE TITLE
Deprecation warnings in PHP 8.1

### ISSUE THREAD

**Issue by ipsod** [gabordemooij/redbean#871]
I'm using redbean 5.7 and PHP 8.1.0RC2 with `error_reporting(E_ALL)`.
I don't know if this is an issue - it happens upon `require('rb.php');`.

> Deprecated: Return type of RedBeanPHP\OODBBean::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/php/rb.php on line 2062
> 
> Deprecated: Return type of RedBeanPHP\OODBBean::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/php/rb.php on line 3072
> 
> Deprecated: Return type of & RedBeanPHP\OODBBean::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/php/rb.php on line 3108
> 
> Deprecated: Return type of RedBeanPHP\OODBBean::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/php/rb.php on line 3055
> 
> Deprecated: Return type of RedBeanPHP\OODBBean::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/php/rb.php on line 3090
> 
> Deprecated: Return type of RedBeanPHP\OODBBean::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/php/rb.php on line 3248
> 
> Deprecated: Return type of RedBeanPHP\OODBBean::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/php/rb.php on line 3855

**Comment by gabordemooij** [comment]
Thanks will look into this

**Comment by gabordemooij** [comment]
Thanks for pointing this out @Lynesth - Must have mistyped that annotation.
Thanks @ipsod for testing it again. I have fixed the typo and I also fixed the null-warning you're getting. Hopefully it will work again, would you mind testing it again please?

Here is the new version:
https://redbeanphp.com/downloads/RedBeanPHP5_7_1RC2.tar.gz

For now I will keep using the ReturnTypeWillChange, when PHP 9 comes around, I will introduce a patch for older PHP-versions and probably a separate package, so you'll get RedBeanPHP5_7_X-Mysql-PHP9plus.tar.gz and -PHPClassic or so. Too bad PHP is breaking backward compatibility, they had an impressive BC-record with PHP5-7. RedBeanPHP will remain backward compatible with PHP 5.3 though (we still have PHP 5.2 users!), for at least another 10 years or so . Once people choose for RedBeanPHP they have to be sure they can really depend on it.

**Comment by ipsod** [comment]
I get no warnings with this version.  Thank you!

**Comment by gabordemooij** [comment]
Thanks for testing! If you encounter any other compat. issues pls let me know!

**Comment by ipsod** [comment]
I just found another deprecation warning:
```
 trim(): Passing null to parameter #1 ($string) of type string is deprecated in
/var/www/html/php/rb_new.php
on line
6191


Deprecated
```

**Comment by ipsod** [comment]
Still another:
`Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/php/rb_new.php on line 6302`

**Comment by fabswt** [comment]
Spotted this one (running v5.7.1):

```txt
trim(): Passing null to parameter #1 ($string) of type string is deprecated

File: /var/www/html/.../vendor/gabordemooij/redbean/RedBeanPHP/QueryWriter/AQueryWriter.php
Line: 869
```

**Comment by prochor666** [comment]
trim(): Passing null to parameter #1 ($string) of type string is deprecated
File: D:\dev\Goat\vendor\gabordemooij\redbean\RedBeanPHP\QueryWriter\AQueryWriter.php (line: 869)

Working fix: 

REPLACE: 
if ( trim( $sql ) === '' ) {

WITH: 
if ( is_null($sql) || trim( $sql ) === '' ) {

Maybe not ideal, but it's working for me.
