### ISSUE TITLE
R::trash() causing issues with FastCGI

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#880]
This is a very strange bug that I have encountered for the first time. I'm at a loss in trying to debug the situation, so will try to provide as much information as possible.

PHP version: 7.4.2
MySQL: 8 (DigitalOcean managed cluster, no read-only nodes)

Whenever I attempt to trash a bean using `R::trash()`, I receive a 500 error from Apache. Digging into the logs, the code is throwing the following error:

> [Fri Nov 12 22:55:52 2021] [error] [client ::1] FastCGI: incomplete headers (0 bytes) received from server "/Applications/MAMP/fcgi-bin/php7.4.2.fcgi", referer: MY_URL

The following code produces this error:

```php
// Get the repositories:
$repo = $this->getRepository(Article::class);
$article = $repo->load($id);
R::trash($article);
```

I am using a custom Bean Helper to manage namespacing of Models (as mentioned in my other issue and suggested by @Lynesth), but that doesn't seem to be the cause of the issue here, since dumping `$article` from the snippet above produces the following:

```
RedBeanPHP\OODBBean Object
(
    [properties:protected] => Array
        (
            [id] => 3
            [title] => aaa
            [slug] => aaa
            [excerpt] => a
            [content] => asd
            [desktop_instructions] => 
            [mobile_instructions] => 
            [published_date] => 2021-11-12
            [published] => 0
            [feedback_enabled] => 1
            [crawling_enabled] => 1
            [meta_title] => aaa
            [meta_description] => a
            [positive_count] => 0
            [negative_count] => 0
            [created] => 2021-11-12 22:43:14
            [modified] => 
            [category_id] => 2
        )

    [__info:protected] => Array
        (
            [type] => article
            [sys.id] => id
            [sys.orig] => Array
                (
                    [id] => 3
                    [title] => aaa
                    [slug] => aaa
                    [excerpt] => a
                    [content] => asd
                    [desktop_instructions] => 
                    [mobile_instructions] => 
                    [published_date] => 2021-11-12
                    [published] => 0
                    [feedback_enabled] => 1
                    [crawling_enabled] => 1
                    [meta_title] => aaa
                    [meta_description] => a
                    [positive_count] => 0
                    [negative_count] => 0
                    [created] => 2021-11-12 22:43:14
                    [modified] => 
                    [category_id] => 2
                )

            [tainted] => 
            [changed] => 
            [changelist] => Array
                (
                )

            [model] => App\Entity\Support\Article Object
                (
                    [bean:protected] => RedBeanPHP\OODBBean Object
 *RECURSION*
                )

        )

    [beanHelper:protected] => App\Helper\BeanHelper Object
        (
            [namespace:App\Helper\BeanHelper:private] => \Support
        )

    [fetchType:protected] => 
    [withSql:protected] => 
    [withParams:protected] => Array
        (
        )

    [aliasName:protected] => 
    [via:protected] => 
    [noLoad:protected] => 
    [all:protected] => 
)
```

Curiously, the following works without an issue:

```php
R::exec('
    DELETE FROM
        article
    WHERE
        id = ?
', [ $article->getId() ]);
```

Any insights as to what's wrong here?

**Comment by gabordemooij** [comment]
Maybe the server runs out of memory due to the hooks associated with R::trash()?

**Comment by benmajor** [comment]
I don't think so, other entities can be deleted without issue in the same environment.

**Comment by Lynesth** [comment]
Hmmm, let's try to narrow it down ! Here come the questions :D

Are you just trying to delete 1 article and it gives you this ?
Do you have a `delete` function in your model ? Or an `after_delete` one ?
Could you turn on Redbean's logging to see what queries are actually made ?
Could you check the fpm logs after getting the error a few times and post relevant lines ?
Also, out of curiosity, could you enable fpm's slow_log and post relevant lines here as well ?

Thanks !

**Comment by benmajor** [comment]
After some investigation, and changing some environment variables, I've been able to get a more useful error from a different server. This is from a completely different project, but also seems to be failing when running `R::trash()`:

> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /home/teamtsb/public_html/vendor/gabordemooij/redbean/RedBeanPHP/OODBBean.php on line 1393

The line that's referenced above is empty, by the way.

I'll continue digging though, in case the above isn't useful.  And below are the answers to your questions:

> Are you just trying to delete 1 article and it gives you this ?

Yes, although I'm also getting the error on a completely different project, now.

> Do you have a delete function in your model ? Or an after_delete one ?

Yes, here it is:

```php
/**
 * Delete the bean
 */
public function trash()
{
    return R::trash(
        $this->bean
    );
}

/**
 * Delete the bean (alias of trash())
 */
public function delete()
{
    return $this->trash();
}
```

I will have to get the answers to your other questions tomorrow ;)

**Comment by Lynesth** [comment]
Wait... if the `delete` function you have here is in the model then you've got recursion, since `delete` is called by the FUSE system when... `trash` is called.

This would explain your issue :)

**Comment by benmajor** [comment]
Ah that would make sense! My apologies.

**Comment by Lynesth** [comment]
Good to know it was just that ! :)

**Comment by benmajor** [comment]
Just following this up, if we remove the delete() alias and rely on the trash() method in the model, will this similarly cause a memory leak?

We like having the ability to delete an entity this way, and so I think using trash() should avoid the conflict with the fused call to delete()?

**Comment by Lynesth** [comment]
Yes, this is fine.
