### ISSUE TITLE
Problems with 8.1

### ISSUE THREAD

**Issue by rivets** [gabordemooij/redbean#883]
There's two calls on string handling (trim and str_start I think) functions in AQueryWriter.php which get NULL passed to them sometimes and this raises a deprecation error.  Easily fixed by testing the value before making the call.

**Comment by ipsod** [comment]
These line numbers are off, but here are some such errors:

```
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/php/rb_new.php on line 6221

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/php/rb_new.php on line 6332
```

**Comment by gabordemooij** [comment]
Thanks for reporting.

**Comment by dandrei** [comment]
Also the `trim` on line `6191` (in `glueSQLCondition`) in version `5.7.1`.
I temporarily fixed it by editing `rb-mysql.php` and changing the `trim` command to `trim( $sql ?? '' )`.

**Comment by gabordemooij** [comment]
Resolved in master, anymore issues with 8.1?

**Comment by robbplo** [comment]
Found one in `QueryWriter::parseJoin()`: Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /Users/robbinploeger/projects/bit-academy/byof-review/helpers/rb.php on line 6302

**Comment by prochor666** [comment]
I temporarily solved issue bellow:

```
trim(): Passing null to parameter #1 ($string) of type string is deprecated
File: D:\dev\...\vendor\gabordemooij\redbean\RedBeanPHP\QueryWriter\AQueryWriter.php (line: 869)
```

Working fix:

On line 869 REPLACE:

```
if ( trim( $sql ) === '' ) {
```

WITH:

```
if ( is_null($sql) || trim( $sql ) === '' ) {
```

Maybe not ideal, but it's working for me.

**Comment by rivets** [comment]
See my recent post about 8.1.2. I had some weirdness with composer but I may also have found some other things that needed updating.
