### ISSUE TITLE
genSlots() issue passing filtered array

### ISSUE THREAD

**Issue by Nux007** [gabordemooij/redbean#884]
Hello,

I noticed a strange behavior with genSlots(), a fatal error is thrown when attempting to pass an array filtered with array_filter. It sounds like the method dislike when numeric keys does not follow a natural range.

```php
// imagine a product array with products id.
$ids = [1, 3, 4, 5, 6, 9, 15, 57, 65, 98, 12];

// Filtering the products id to get an array of odd ones.
$oddIds = array_filter($ids, function($id){
    return $id % 2 !== 0;
});

// Using SF var dumper
dump([
    "Id's" => $ids,
    "Filtered ones" => $oddIds,
]);

// Getting beans will thrown a fata error
$products = R::find('product', 'id IN ('. R::genSlots($oddIds) .')', $oddIds);
```

The dump output the following:

![Capture d’écran_2021-12-22_10-05-26](https://user-images.githubusercontent.com/17247565/147066917-ac5ffe4d-9175-4c46-8f41-e84b2d8d4321.png)

Will thrown this error:

![Capture d’écran_2021-12-22_10-05-27](https://user-images.githubusercontent.com/17247565/147067228-a35c7110-6222-4526-bee9-c7c78adbfd96.png)

A solution is to use array_values to reset the array keys as follow:

```php
$oddIds = array_values(array_filter($ids, function($id){
    return $id % 2 !== 0;
}));
```

And the error does not appear anymore.

**Comment by Lynesth** [comment]
Hey there,

I haven't tried yet but I would be tempted to believe that the issue doesn't lie with genSlots but with the fact that you're passing that array to the bindings, specifically in this function: https://github.com/gabordemooij/redbean/blob/edee651d01a6b77ecf4cc16e3ac4b245a2c843a6/RedBeanPHP/Driver/RPDO.php#L121

**Comment by Nux007** [comment]
Hello,

You're right, it sound like array_values outside RedBean is the only option I have for now.

Thank's :-)
