### ISSUE TITLE
Feature: copyBeansTo

### ISSUE THREAD

**Issue by fmp777** [gabordemooij/redbean#885]
First, I need to say I am brand new to redbean.

While implementing I had the need to copy some records to another table before trashing them with redbean. I really dug around redbean code and docs trying to find the redbean-way, but I couldn't find it. Purpose of this would be like a log of deletions that could be restored if needed by an admin.

I tried find then importFrom after dispense on the new table, but no go. I looked for an importAll, but no go. I tried setMeta('type', 'newtable') before storing, but that doesn't work. So I wrote my own method to handle this. 

If there's a redbean way please do tell, otherwise, can I recommend this method get added? If you like the code as is, I can do a pull request, just let me know. I added this to the R facade

```php
    /**
     * Copy array of beans to another table ($type), omitting columns from $omit
     *
     * @param string $type table to copy to
     * @param array $beans array of beans, like retrieved with find()
     *
     * @return array array of ids created from the copy
     */
    public static function copyBeansTo($type, $beans = [], $omit = [])
    {
        $results = [];
        foreach ($beans as $record)
        {
            $target = self::dispense($type);
            $data = $record->export(false, false, true);
            foreach ($omit as $col)
                unset($data[$col]);
            $target->import($data);
            $results[] = self::store($target);
        }

        return $results;
    }
```

**Comment by Lynesth** [comment]
Hey there,

Does this work for what you are looking for ?

```php
$export = R::exportAll($beans);
$copies = R::convertToBeans('newtype', $export);
R::storeAll($copies);

// Or in one line

R::storeAll(R::convertToBeans('newtype', R::exportAll($beans)));
```

**Comment by fmp777** [comment]
Hi Lynesth, its certainly more eloquent than my copyBeansTo, but is missing a vital $omit - since in my case i don't want the 'id' field and redbean seams to quietly do nothing if you include it (no error, no data stored)

**Comment by Lynesth** [comment]
Right, that's actually expected, my bad.
I still don't have time to dive completely into this because of Christmas but here's something that should work:
```php
foreach ($beans as $bean) {
    R::store(R::dispense('newtype')->inject($bean));
}

// Or a more verbose version
$results = [];
foreach ($beans as $bean) {
    $newBean = R::dispense('newtype');
    $newBean->inject($bean);
    $results[] = $newBean;
}
R::storeAll($results);
```

**Comment by gabordemooij** [comment]
Hi, sorry I have been late to the party but I had to manage the new release of my other project (Citrine, https://citrine-lang.org/). To be honest, I would simply use SQL for this:

`R::exec('insert into newtype select * from oldtype');
`

or (new versions of mysql):


`R::exec('insert into newtype table oldtype');
`

https://dev.mysql.com/doc/refman/8.0/en/insert-select.html

So yeah, sure we could wrap this in a function R::copyBeansInto() but what would be the point, doing this with CRUD-operations would be x1000 times slower and the SQL-syntax is pretty straight forward.

**Comment by fmp777** [comment]
Well, the point would be if the other table wasn't created yet, or had all the same fields yet. To do it the redbean way. When I use a project like this, i try not to break out of it, otherwise why not just go all pure SQL.

**Comment by fmp777** [comment]
> If you don't want to create copies, you can also probably do something like this (although it looks more rough and there might be some side effects I haven't thought about, so I most likely wouldn't advise it):
> 
> ```
> foreach ($beans as $bean) {
>     $bean->id = 0;
>     $bean->setMeta('type', 'newtype');
> }
> R::storeAll($beans);
> ```

I've tried using setMeta type but it did nothing in the end, no error, no changes. But maybe its the setting of ID to 0 that makes it work? would unset($bean->id) work the same? for more clear code?

**Comment by gabordemooij** [comment]
> Well, the point would be if the other table wasn't created yet, or had all the same fields yet. To do it the redbean way. When I use a project like this, i try not to break out of it, otherwise why not just go all pure SQL.

One of the principles behind RedBeanPHP was to play friendly with SQL. It was never intended to replace or hide SQL. The CRUD-stuff, extended SQL-syntax and other functions just make life easier compared to doing everything manually. That does not mean you should not use SQL at all. If you can solve things by just using SQL, just do it. It's just that some things like CRUD are very cumbersome (all those queries look the same etc, do I need INSERT/UPDATE/UPSERT/REPLACE etc...) - RedBeanPHP just fixes those parts of SQL. This is also the reason why R::find() does not use it's own SQL dialect like Doctrine does (DQL). We just play nice with SQL.
