### ISSUE TITLE
`class Model_Band extends RedBean_SimpleModel { ... }` -- correct syntax?

### ISSUE THREAD

**Issue by fabswt** [gabordemooij/redbean#886]
Is [this example from the docs](https://redbeanphp.com/index.php?p=/models) actually correct?

```php
 class Model_Band extends RedBean_SimpleModel { ... }
```

I get this error when I try to use it:

```txt
Parse error: syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING) in ‹source file›
```

Instead, I have to use this (with `define('REDBEAN_MODEL_PREFIX', '\\Model\\');` defined earlier in the app):

```php
namespace Model;
class Band extends \RedBeanPHP\SimpleModel
```

This tripped me up a few times, so wondering if I missed something or if the docs are just being inaccurate on this one.

Thanks!

**Comment by gabordemooij** [comment]
It depends on the PHP version

**Comment by gabordemooij** [comment]
If you use the single file version rb.php there is a backward compatibility line:

![image](https://user-images.githubusercontent.com/89826/150115499-29754920-bdbe-4642-a716-c0639dbcfccc.png)


It allows older PHP-versions to use this feature. I just tested it. It should work like that.
But it's only available if you use one of the official all-in-one packages.
