### ISSUE TITLE
Problems with 8.1.2

### ISSUE THREAD

**Issue by rivets** [gabordemooij/redbean#888]
Deprecation warnings for passing NULL in several places and also return type errors for quite a few functions.

*UPDATE* these may all have been fixed already - composer was behaving very oddly for me yesterday and I am not sure what was going on, some old files seemed to appear in another package.

**Comment by rivets** [comment]
diff --git a/RedBeanPHP/Driver/RPDO.php b/RedBeanPHP/Driver/RPDO.php
index cfed9e2..994552f 100644
--- a/RedBeanPHP/Driver/RPDO.php
+++ b/RedBeanPHP/Driver/RPDO.php
@@ -187,7 +187,7 @@ class RPDO implements Driver
 					$this->resultArray = array();
 					return $statement;
 				}
-				$this->resultArray = $statement->fetchAll( $fetchStyle );
+				$this->resultArray = $statement->fetchAll( $fetchStyle != NULL ?  $fetchStyle : \PDO::FETCH_DEFAULT );
 				if ( $this->loggingEnabled && $this->logger ) {
 					$this->logger->log( 'resultset: ' . count( $this->resultArray ) . ' rows' );
 				}
@@ -312,7 +312,7 @@ class RPDO implements Driver
 			$this->isConnected = TRUE;
 			$this->setEncoding();
 			$this->pdo->setAttribute( \PDO::ATTR_ERRMODE,\PDO::ERRMODE_EXCEPTION );
-			$this->pdo->setAttribute( \PDO::ATTR_DEFAULT_FETCH_MODE,\PDO::FETCH_ASSOC );
+			$this->pdo->setAttribute( \PDO::ATTR_DEFAULT_FETCH_MODE,\CH_ASSOC );
 			// make sure that the dsn at least contains the type
 			$this->dsn = $this->getDatabaseType();
 		} else {
diff --git a/RedBeanPHP/OODBBean.php b/RedBeanPHP/OODBBean.php
index 4d6195a..5d35f07 100644
--- a/RedBeanPHP/OODBBean.php
+++ b/RedBeanPHP/OODBBean.php
@@ -477,7 +477,7 @@ class OODBBean implements \IteratorAggregate,\ArrayAccess,\Countable,Jsonable
 	 *
 	 * @return ArrayIterator
 	 */
-	public function getIterator()
+	public function getIterator() : \ArrayIterator
 	{
 		return new \ArrayIterator( $this->properties );
 	}
@@ -1470,7 +1470,7 @@ class OODBBean implements \IteratorAggregate,\ArrayAccess,\Countable,Jsonable
 	 *
 	 * @return void
 	 */
-	public function offsetSet( $offset, $value )
+	public function offsetSet( $offset, $value ) : void
 	{
 		$this->__set( $offset, $value );
 	}
@@ -1487,7 +1487,7 @@ class OODBBean implements \IteratorAggregate,\ArrayAccess,\Countable,Jsonable
 	 *
 	 * @return boolean
 	 */
-	public function offsetExists( $offset )
+	public function offsetExists( $offset ) : bool
 	{
 		return $this->__isset( $offset );
 	}
@@ -1505,7 +1505,7 @@ class OODBBean implements \IteratorAggregate,\ArrayAccess,\Countable,Jsonable
 	 *
 	 * @return void
 	 */
-	public function offsetUnset( $offset )
+	public function offsetUnset( $offset ) : void
 	{
 		$this->__unset( $offset );
 	}
@@ -1523,7 +1523,7 @@ class OODBBean implements \IteratorAggregate,\ArrayAccess,\Countable,Jsonable
 	 *
 	 * @return mixed
 	 */
-	public function &offsetGet( $offset )
+	public function &offsetGet( $offset ) : mixed
 	{
 		return $this->__get( $offset );
 	}
@@ -1663,7 +1663,7 @@ class OODBBean implements \IteratorAggregate,\ArrayAccess,\Countable,Jsonable
 	 *
 	 * @return integer
 	 */
-	public function count()
+	public function count() : int
 	{
 		return count( $this->properties );
 	}
@@ -2270,7 +2270,7 @@ class OODBBean implements \IteratorAggregate,\ArrayAccess,\Countable,Jsonable
 	 *
 	 * @return array
 	 */
-	public function jsonSerialize()
+	public function jsonSerialize() : mixed
 	{
 		$json = $this->__call( '@__jsonSerialize', array( ) );
 
diff --git a/RedBeanPHP/QueryWriter/AQueryWriter.php b/RedBeanPHP/QueryWriter/AQueryWriter.php
index 77b494c..8197b92 100644
--- a/RedBeanPHP/QueryWriter/AQueryWriter.php
+++ b/RedBeanPHP/QueryWriter/AQueryWriter.php
@@ -864,7 +864,7 @@ abstract class AQueryWriter
 	{
 		static $snippetCache = array();
 
-		if ( trim( $sql ) === '' ) {
+		if ($sql == NULL ||  trim( $sql ) === '' ) {
 			return $sql;
 		}
 
@@ -975,7 +975,7 @@ abstract class AQueryWriter
 	 */
 	public function parseJoin( $type, $sql, $cteType = NULL )
 	{
-		if ( strpos( $sql, '@' ) === FALSE ) {
+		if ( $sql == NULL ||  strpos( $sql, '@' ) === FALSE ) {
 			return $sql;
 		}

**Comment by rivets** [comment]
However 

$this->resultArray = $statement->fetchAll( $fetchStyle != NULL ?  $fetchStyle : \PDO::FETCH_DEFAULT );

should probably be

$this->resultArray = $statement->fetchAll( $fetchStyle  ??  \PDO::FETCH_DEFAULT );

Unless there is a backward compatibility issue.

**Comment by gabordemooij** [comment]
I try to keep it backward compatible as much as possible. Seems like those statements are functionally the same right? Or do I miss something here?

**Comment by rivets** [comment]
They are functionally the same, so no problem with either and the long one is backward compatible. (I confess to being all in on 8.* in my code :-)

**Comment by gabordemooij** [comment]
Ok, the I'll close this issue if you don't mind. If any other issue pops up, feel free to re-open.
