### ISSUE TITLE
Mistake in guideline post on website

### ISSUE THREAD

**Issue by HairlessUncle** [gabordemooij/redbean#892]
Hi, I'm a beginner trying to learn this ORM library, I spent hours and identified a small mistake on official website.
https://redbeanphp.com/index.php?p=/quick_tour

   `$post = R::dispense( 'post' );
    $post->title = 'My holiday';
    $id = R::store( $post );`
but
    `$posts = R::find(
    'post', ' title LIKE ?', [ 'holiday' ] ); //missing %, else return nothing`

**Comment by gabordemooij** [comment]
Thanks for reporting this issue, I will correct it asap.

**Comment by gabordemooij** [comment]
The error in the manual had been corrected, can you confirm?

**Comment by HairlessUncle** [comment]
> The error in the manual had been corrected, can you confirm?

Hi, it is updated, thanks
