### ISSUE TITLE
class_exists can cause performance issues.

### ISSUE THREAD

**Issue by gnysek** [gabordemooij/redbean#893]
In my own code, I've got custom autoloader, which just scans all subfolders of application for class (there's not much), and doesn't cache results in any way, so it performs scan on every `new xxx();` or `class_exists()`.

This causes BIG performance issues, in my case script was executing for about 2.0 - 3.5 seconds, cause class_exists() is called about 3-4 times for every SQL result row, but when I changed all `class_exists($class)` occurrences to `class_exists($class, false)`, same code was executing for 0.1 - 0.2 seconds, so it's a 350 times faster.

While I customized `rb.php` script myself which solves my issue, my proposal is to either add some property/constant which can force this setting, or cache subsequent calls for same class. Solution 1. seems to be easiest, as it only requires changing 4 lines of code to something like: `class_exists( $modelName, defined( 'REDBEAN_CLASS_AUTOLOAD' ) ? REDBEAN_CLASS_AUTOLOAD : true )`, and then `const REDBEAN_CLASS_AUTOLOAD = false;` would help with performance issues if someone doesn't want autoload for RB.

`class_exists` is called in `\RedBeanPHP\BeanHelper\SimpleFacadeBeanHelper::resolveModel` and in pure php as `if (!class_exists('R'))`.

**Comment by gabordemooij** [comment]
I like the first solution, there should be an option to just bypass the default auto loader.

**Comment by gabordemooij** [comment]
https://github.com/gabordemooij/redbean/commit/3d0988c28159405013e2b07ca2f27a50f3d724f5
