### ISSUE TITLE
R::loadJoined() on null value

### ISSUE THREAD

**Issue by marios88** [gabordemooij/redbean#900]
PHP 8.1.7
RB 5.7.2

$user->company_id is `NULL`

```php
$user = \R::load('user', 1);
\R::loadJoined([$user], 'company');
```
Throws on https://github.com/gabordemooij/redbean/blob/0a599233f3c5a11b67afc17ca5601a334378554e/RedBeanPHP/Finder.php#L554
```
ErrorException Undefined array key
```
Not sure where the problem originates

**Comment by gabordemooij** [comment]
It looks like in previous versions of PHP this triggered a warning. Anyway it was just returning null for those properties anyway.

**Comment by gabordemooij** [comment]
Should have been fixed now!
