### ISSUE TITLE
what is the purpose of this line that affects tables with underscore more than 2 on table names

### ISSUE THREAD

**Issue by laupkram** [gabordemooij/redbean#904]
This code affects me as I do a lot of underscore on my table names for convention as an example I have a table name `zn_host_userdata` but in other functions like `R::findAll()` I don't face the issue while using the same table

```
$type = AQueryWriter::camelsSnake( $type );
		if ( count( explode( '_', $type ) ) > 2 ) {
			throw new RedException( 'Invalid type for count.' );
		}
```

what is the purpose of` if ( count( explode( '_', $type ) ) > 2 ) { `and throwing an exception for invalid type for count?

https://github.com/gabordemooij/redbean/blob/0a599233f3c5a11b67afc17ca5601a334378554e/RedBeanPHP/Repository.php#L654

**Comment by gabordemooij** [comment]
RedBeanPHP has been designed with certain schema limitations in mind. So for instance it expects tables/types to consist of only one word (book, page) and shared lists have an underscore between the types (book_page). This seems like a rudimentary type check, to be honest I have to look it up in the git history, I don't remember. I'll look into it.

**Comment by gabordemooij** [comment]
Okay, so the RedBeanPHP schema policy has been described here:
https://redbeanphp.com/index.php?p=/about#restrictions

This is how you should use RedBeanPHP, i.e. let it generate the schema for you or adhere to the policy.
As described in:

https://redbeanphp.com/index.php?p=/prefixes

You can circumvent these checks if you wish, but note that some special features might not work.

Anyway, I do not see a reason why you cannot count those beans. So I updated the master branch to reflect this change. All tests seem to work (except the ones that check this check).

https://github.com/gabordemooij/redbean/commit/e91adf5d25b0e7a354c3a8ee943cecaef323cc5c

Hope this helps.

cheers,
Gabor
