### ISSUE TITLE
Call to undefined function mb_strlen on php8.2

### ISSUE THREAD

**Issue by JamesKingdom** [gabordemooij/redbean#908]
Hi,
I'm really loving Redbean so far, it's really useful and saves lots of time 😁, anyway- 
I was just testing an application on php8.2, and I'm getting this error: (works fine on php7.3)
`[Sun Dec 04 00:43:04.583327 2022] [php:error] [pid 27846] [client***] PHP Fatal error:  Uncaught Error: Call to undefined function RedBeanPHP\\QueryWriter\\mb_strlen() in /var/www/***/includes/rb-mysql.php:7389\nStack trace:\n#0 /var/www/***/includes/rb-mysql.php(8857): RedBeanPHP\\QueryWriter\\MySQL->scanType()\n#1 /var/www/***/includes/rb-mysql.php(8967): RedBeanPHP\\Repository\\Fluid->modifySchema()\n#2 /var/www/***/includes/rb-mysql.php(8523): RedBeanPHP\\Repository\\Fluid->storeBean()\n#3 /var/www/***/includes/rb-mysql.php(9634): RedBeanPHP\\Repository->store()\n#4 /var/www/***/includes/rb-mysql.php(12598): RedBeanPHP\\OODB->store()\n#5 /var/www/***/roles/addRoleHandler.php(43): RedBeanPHP\\Facade::store()\n#6 {main}\n  thrown in /var/www/***/includes/rb-mysql.php on line 7389, referer: ***
`
Am I missing something obvious?
Thanks!
James

**Comment by gabordemooij** [comment]
probably mb_str functions not installed?
https://www.php.net/manual/en/mbstring.installation.php
https://redbeanphp.com/index.php?p=/requirements
