### ISSUE TITLE
why does rb remove the letter "s" at the end of the table name during crud operations in freeze mode

### ISSUE THREAD

**Issue by relaxdd** [gabordemooij/redbean#912]
after I designed my tables and corrected their types, I decided that it was possible to freeze redbeanphp and ran into an unexpected problem, it started deleting the letter 's' at the end of my tables' names during crud operations, my tables are called 'users', 'configs' and 'tokens'

the simplest solution is most likely to just rename the tables, but why have to I do that?

**Comment by gabordemooij** [comment]
RedBeanPHP does not do such thing I believe, are you sure? Can you show me a simple test case?

**Comment by gabordemooij** [comment]
The following code seems to work just fine:
```

$user = R::dispense('user');
$user->name = 'me';
R::store($user);
print_r(R::inspect());
```


Gives a table "user":

```
Array
(
    [0] => user
)

```

**Comment by relaxdd** [comment]
why are you creating a "dispense" component named "user", I said about
"users"

чт, 16 февр. 2023 г. в 02:53, Gabor de Mooij ***@***.***>:

**Comment by gabordemooij** [comment]
Okay, my bet, sorry, I read it wrong.

But still:

```

$user = R::dispense('users');
$user->name = 'me';
R::store($user);
print_r(R::inspect());


```
gives:

```
Array
(
    [0] => users
)

```

I am not really a fan of automatic inflection, so I would never implement anything like that in RedBeanPHP.  Can you give me a counter example like this that demonstrates the issue?

**Comment by gabordemooij** [comment]
This also just works fine?

```
$user = R::dispense('users');
$user->name = 'me';
R::store($user);
R::freeze(1);
print_r(R::find('users'));

```

**Comment by Lynesth** [comment]
> after I designed my tables

Did you manually rename your tables to plural versions of the words?
Redbean will not add or remove `s` at the end of the tables. As Gabor mentioned, It doesn't do the whole user -> users, person -> people inflections that some other ORMs do.

**Comment by relaxdd** [comment]
I will try to show an example in the near future, there is a lot of work now, at that moment I just renamed my tables from "users" to "user" and so on, but I remember for sure that there were problems with the last option and the action "R::dispense('users')" or "R::find('users')" I received an error saying that the "user" table does not exist, that is, he was looking for or trying to create without the letter "s" at the end of the table name, and this happened only in the "freeze" mode

**Comment by gabordemooij** [comment]
I am pretty sure I never wrote such logic, but I will test it anyway.

**Comment by zerecargo** [comment]
> RedBeanPHP does not do such thing I believe, are you sure? Can you show me a simple test case?

You have the name of the table 'user' and not 'users', if you used the second option, then with a 95% probability you would get an error that "the table 'user' was not found" despite the fact that you have a table 'users' and not 'user', I'm writing this because I ran into it again with this error, maybe it's some kind of table naming convention without the letter 's' at the end that I'm not aware of, or is it really a redbeanphp error?

**Comment by relaxdd** [comment]
> This also just works fine over here?
> 
> ```
> $user = R::dispense('users');
> $user->name = 'me';
> R::store($user);
> R::freeze(1);
> print_r(R::find('users'));
> ```

For some reason, this does not work for me personally, it gives the error "the 'user' table was not found, despite the fact that I actually wrote 'users' in the code"

**Comment by relaxdd** [comment]
> > after I designed my tables
> 
> Did you manually rename your tables to plural versions of the words? Redbean will not add or remove `s` at the end of the tables. As Gabor mentioned, It doesn't do the whole user -> users, person -> people inflections that some other ORMs do.

I have it happening for some reason

**Comment by relaxdd** [comment]
> I am pretty sure I never wrote such logic, but I will test it anyway.

is it possible that PDO does this?
