### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by KrYpToDeN** [gabordemooij/redbean#915]
Hello.

1. Thanks for your development. Good solution!
2. I'm using PHP 8.2 and RedBeanPHP 5.7.3 MySQL Driver from 08.10.2022 (last release).
Also i'm using your commit to correct defrecation warnings for PHP 8.2 from 12.11.2022 (last commit).

But in nginx log files i have lot's of errors, exactly:
`2023/02/11 14:37:09 [error] 114293#114293: *23559 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Creation of dynamic property RedBeanPHP\QueryWriter\MySQL::$svalue is deprecated in /var/www/domain.ru/public_html/rb-mysql.php on line 7353" while reading response header from upstream....`

How can o solve it?

**Comment by gabordemooij** [comment]
This variable seems to be no longer in use anyway, I deleted it.

**Comment by gabordemooij** [comment]
Tests might be failing, we ran out of open source credits, I filed a new request to add new credits to the project acount.
