### ISSUE TITLE
Mysql PDO transaction problem

### ISSUE THREAD

**Issue by marios88** [gabordemooij/redbean#918]
I have run into this "bug" when using transactional grouped inserts https://bugs.php.net/bug.php?id=61613

But unfortunately i cannot access the prepared statement to run `nextRowset()`

For now my solution is to run each insert in a loop, but i am looking for a more elegant solution
```php
\R::begin();
$queries =[ ... ];
try{
    foreach ($queries as $query) {
        \R::exec($query);
    }
    \R::commit();
}catch (Exception $e) {
    \R::rollback();
}
```

**Comment by gabordemooij** [comment]
Interesting, I will take a look.

**Comment by gabordemooij** [comment]
You have to invoke runQuery yourself then on the PDO instance, obtain it like this:

`$pdo = R::getDatabaseAdapter()->getDatabase()->getPDO();`


https://redbeanphp.com/api/classes/RedBeanPHP.Driver.RPDO.html#method_getPDO

I think that should work?

**Comment by gabordemooij** [comment]
Fixed https://github.com/gabordemooij/redbean/commit/184954ff320b6d8e48ee40b878b88c7bac387a52
