### ISSUE TITLE
Php 8.2 issue

### ISSUE THREAD

**Issue by rivets** [gabordemooij/redbean#919]
I'm sure this is being dealt with but just in case :

System Error - Error 8192 Creation of dynamic property RedBeanPHP\QueryWriter\MySQL::$svalue is deprecated /opt/httpd/htdocs/vendor/gabordemooij/redbean/RedBeanPHP/QueryWriter/MySQL.php | 263 | 8192 | Error 8192 Creation of dynamic property RedBeanPHP\QueryWriter\MySQL::$svalue is deprecated

**Comment by gabordemooij** [comment]
did you use the latest master?

**Comment by gabordemooij** [comment]
Latest master passes all tests on CI for 8.2.

https://app.travis-ci.com/github/gabordemooij/redbean/builds/260775540

**Comment by rivets** [comment]
Sorry, haven't had a chance to test, got covid.
