### ISSUE TITLE
Sqlite connection don`t close

### ISSUE THREAD

**Issue by rnr1721** [gabordemooij/redbean#928]
Hi!

```php

use RedBeanPHP\R;

        R::setup();
        var_dump(R::testConnection());
        R::close();
        var_dump(R::testConnection());
```
result:
```
bool(true)
bool(true)
```

Why does that connection not want to close?
Or is it specific to sqlite?

Redbean 5.7 from composer

**Comment by Lynesth** [comment]
`testConnection` doesn't just tell you whether or not you're connected, but it actually does all the necessary steps in order to connect and *then* tells you whether you're connected or not.

**Comment by rnr1721** [comment]
Yes, I did not think to look at the code of this method.  Thank you!
