### ISSUE TITLE
Why can't we use PascalCase column names?

### ISSUE THREAD

**Issue by hamsbrar** [gabordemooij/redbean#930]
It looks like column names undergo a mandatory transformation into snake case.

I understand the rationale behind underscore(`_`) restrictions but can someone explain What's the issue with PascalCase?

**Comment by gabordemooij** [comment]
Because it is/was the most compatible way. Some OS/DB-versions are case insensitive.

**Comment by Lynesth** [comment]
Hi @hamsbrar 

The reason it's now "the only behaviour available"  was a choice by the creator of RedBean to keep things simple.
But that doesn't mean a PR that adds the behaviour you wish for wouldn't be welcomed.

On a side note, you can still write your code using PascalCase to access beans properties (ie. `$bean->MyProperty`), as RedBean takes care of transforming that into snake_case before querying the database. But I assume it's the fact that the columns are not PascalCase in the database that bothers you?

**Comment by Lynesth** [comment]
You can use `RedBeanPHP\Util\DispenseHelper::setEnforceNamingPolicy(false)` to prevent it to change your tables names, but there isn't anything for columns at the moment.

Also, given that you're probably not using a database with case sensitive columns names anyway (and if you are, I'm curious as to what setup it is), and if you don't need to have RedBean modify the database (so if you can work in Frozen mode), then you can probably just write all your properties in lowercase.

```php
R::setup( ... );
R::freeze(true);

$test = R::dispense('mytable');
$test->mycolumn = 'This works'; // column is actually 'MyColumn' in the db
R::store($test);
```

Probably not a real solution to your problem, but a solution nonetheless :)

**Comment by Lynesth** [comment]
If you're using FUSE Models, you can probably just get away changing the `__get` and `__set` by adding a little `strtolower()` in there.

If not, and if you're just working with a frozen database, modifying RedBean's code to add a
```php
if ( ctype_upper( $property[0] ) ) return $property;
```
at the start of the `OODBBean::beau()` function should allow you to use PascalCase properties directly.

_Note: None of this is tested, but it should work (again, just in Frozen mode, as fluid mode includes schema checks which will most likely still not function)._

**Comment by gabordemooij** [comment]
Let's re-open this issue if it becomes relevant again.
