### ISSUE TITLE
Framework integration

### ISSUE THREAD

**Issue by flip111** [gabordemooij/redbean#936]
Would it be an idea to officially support some of the biggest PHP frameworks such as providing a symfony bundle and laravel package?

On the one hand it could be said that 3rd parties can integrate this. On the other hand it's becoming more common that software libraries provide integrations with things in the ecosystem. Making it 1st party would give best of class integration and promote the use of redbeanphp.

**Comment by gabordemooij** [comment]
People are always welcome to package RedBeanPHP in their favorite framework. I can even add links to the packages/plugins on the main website, no problem.

Personally, I do not rely that much on frameworks, So I would not know where to begin. I believe this is best done by people who know more about their favourite framework than I do.

**Comment by flip111** [comment]
What about if someone else did it but still it's described on the main site (i mean a bit larger description). For example tailwind does this https://tailwindcss.com/docs/guides/symfony

**Comment by gabordemooij** [comment]
Sure, of course.
The website is also open source, you can send in a PR if you want (just plain HTML).
Just select the "manual" branch.

**Comment by flip111** [comment]
That's nice, something i was thinking about for some years already. I'm not sure if i will do it soon. I will close this ticket because i don't see a reason to keep it as active item. If anyone else wants to do it they can search the issues and find it by keyword.
