### ISSUE TITLE
Best way to link to self?

### ISSUE THREAD

**Issue by Josh5A** [gabordemooij/redbean#942]
Hello, 

I'm not sure where to ask this question. Can RedBean do many-to-many self references? I have a table of articles and I need to record which ones will link to others internally. 

So I want to be able to do something like $article→sharedArticleList. 

In the database, the table I want is:
CREATE TABLE article_article (
    article_id1 INT NOT NULL,
    article_id2 INT NOT NULL,
    PRIMARY KEY(article_id1, article_id2)
);

**Comment by Lynesth** [comment]
You should be able to do it as you'd do any other shared lists.
