### ISSUE TITLE
Phpstan Complains about missing type CustomModel

### ISSUE THREAD

**Issue by mattimatti** [gabordemooij/redbean#953]
Hello

While overriding SimpleFacadeBeanHelper::getModelForBean

I'm wandering if the type CustomModel is needed.

https://github.com/gabordemooij/redbean/blob/1bb7b5b93031d1a458a503ee91b595c8f7a8c83d/RedBeanPHP/BeanHelper.php#L57

https://github.com/gabordemooij/redbean/blob/1bb7b5b93031d1a458a503ee91b595c8f7a8c83d/RedBeanPHP/BeanHelper/SimpleFacadeBeanHelper.php#L93

**Comment by gabordemooij** [comment]
CustomModel was meant as a marker interface, but it's not used I think. I removed it.
https://github.com/gabordemooij/redbean/pull/954

**Comment by mattimatti** [comment]
Thank you Gabor!
